"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminNotice, AdminShell } from "../_components/AdminShell";
import "./training-operations.css";

type Season={id:string;year:number;name:string;isCurrent:boolean};
type Drill={id:string;title:string;phase:string;intensity:string;minMinutes:number;maxMinutes:number;description:string;coachingPoints:string;relevance:number};
type Need={group:string;groupLabel:string;unit:string;skillKey:string;skillLabel:string;category:string;current:number;target:number;coveragePct:number;needScore:number;trainingScore:number;state:string;drills:Drill[]};
type Period={id:string;phase:string;unit:string;positionGroup:string;title:string;drillId:string|null;minutes:number;sourceType:string;sourceKey:string;sourceScore:number|null;coachingPoints:string;note:string};
type Session={id:string;title:string;startsAt:string|null;durationMinutes:number;status:string;objective:string;coachNote:string;updatedBy:string;updatedAt:string;periods:Period[];review:null|{completionPct:number;executionRating:number|null;intensityRating:number|null;objectiveMet:boolean;whatWorked:string;nextFocus:string;reviewedBy:string;reviewedAt:string}};
type Payload={seasons:Season[];season:Season;sessions:Session[];needs:Need[];summary:{players:number;gameReady:number;focusNeeds:number;evaluateFirst:number;attendancePct:number|null}};
type Tab="plan"|"needs"|"drills"|"attendance"|"review";

export function TrainingOperationsManager(){
 const[data,setData]=useState<Payload|null>(null),[seasonId,setSeasonId]=useState(""),[sessionId,setSessionId]=useState(""),[tab,setTab]=useState<Tab>("plan"),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const[title,setTitle]=useState("Team Training"),[startsAt,setStartsAt]=useState(""),[duration,setDuration]=useState(120),[objective,setObjective]=useState(""),[coachNote,setCoachNote]=useState(""),[periods,setPeriods]=useState<Period[]>([]);
 useEffect(()=>{void boot()},[]);
 async function boot(){const params=new URLSearchParams(window.location.search);const sid=params.get("season")||undefined;await load(sid);}
 async function load(sid?:string,keepSession?:string){setLoading(true);setNotice("");try{const p=new URLSearchParams();if(sid)p.set("seasonId",sid);const r=await fetch(`/admin/api/training-operations?${p}`);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||"Training Operations konnte nicht geladen werden.")}const b=await r.json() as Payload;setData(b);setSeasonId(b.season.id);const selected=b.sessions.find(s=>s.id===keepSession)||b.sessions[0]||null;if(selected){selectSession(selected)}else{setSessionId("");setPeriods([])}}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 function selectSession(s:Session){setSessionId(s.id);setTitle(s.title);setStartsAt(toLocal(s.startsAt));setDuration(s.durationMinutes);setObjective(s.objective);setCoachNote(s.coachNote);setPeriods(s.periods.map(p=>({...p})));}
 async function changeSeason(id:string){setSeasonId(id);setSessionId("");window.history.replaceState(null,"",`/admin/training-operations?season=${encodeURIComponent(id)}`);await load(id)}
 async function createSession(){if(!seasonId)return;setSaving(true);try{const r=await fetch("/admin/api/training-operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-session",seasonId,title:"Team Training",durationMinutes:120})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Training konnte nicht angelegt werden.");await load(seasonId,b.id);setNotice("Neue Trainingseinheit angelegt.")}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Anlegen.")}finally{setSaving(false)}}
 async function save(){if(!sessionId)return;setSaving(true);try{const r=await fetch("/admin/api/training-operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save-session",sessionId,title,startsAt:startsAt?new Date(startsAt).toISOString():null,durationMinutes:duration,status:"planned",objective,coachNote,periods})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Speichern fehlgeschlagen.");await load(seasonId,sessionId);setNotice("Trainingsplan gespeichert.")}catch(e){setNotice(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setSaving(false)}}
 async function generate(){if(!sessionId)return;setSaving(true);try{await save();const r=await fetch("/admin/api/training-operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"generate-plan",sessionId})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Plan konnte nicht erzeugt werden.");await load(seasonId,sessionId);setNotice(`Development-basierter Trainingsvorschlag erstellt · ${b.duration} Minuten.`)}catch(e){setNotice(e instanceof Error?e.message:"Plan konnte nicht erzeugt werden.")}finally{setSaving(false)}}
 function patchPeriod(id:string,patch:Partial<Period>){setPeriods(cur=>cur.map(p=>p.id===id?{...p,...patch}:p))}
 function addPeriod(){setPeriods(cur=>[...cur,{id:crypto.randomUUID(),phase:"team",unit:"team",positionGroup:"",title:"Neuer Period",drillId:null,minutes:10,sourceType:"manual",sourceKey:"",sourceScore:null,coachingPoints:"",note:""}])}
 function removePeriod(id:string){setPeriods(cur=>cur.filter(p=>p.id!==id))}
 async function complete(){if(!sessionId)return;const nextFocus=prompt("Nächster Trainingsfokus / Follow-up:","")??"";setSaving(true);try{const r=await fetch("/admin/api/training-operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete-session",sessionId,review:{completionPct:100,objectiveMet:true,nextFocus}})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Review fehlgeschlagen.");await load(seasonId,sessionId);setTab("review");setNotice("Training abgeschlossen und Review gespeichert.")}catch(e){setNotice(e instanceof Error?e.message:"Review fehlgeschlagen.")}finally{setSaving(false)}}
 const selected=data?.sessions.find(s=>s.id===sessionId)||null;const totalMinutes=periods.reduce((s,p)=>s+Number(p.minutes||0),0);const drillMap=useMemo(()=>{const m=new Map<string,Drill>();for(const n of data?.needs??[])for(const d of n.drills)m.set(d.id,d);return [...m.values()]},[data]);
 return <AdminShell active="trainingops" title="Training Operations" eyebrow="RASCALS OS · PERFORMANCE LOOP" actions={<><button className="cms-button secondary" onClick={()=>void createSession()} disabled={saving}>＋ Training</button>{sessionId&&<button className="cms-button" onClick={()=>void save()} disabled={saving}>{saving?"Speichert…":"Plan speichern"}</button>}</>}>
  {notice&&<AdminNotice tone={notice.includes("fehl")||notice.includes("Fehler")?"error":"success"}>{notice}</AdminNotice>}
  <AdminCard className="to-header"><div><small>TRAINING COMMAND</small><h2>Development-Daten in konkrete Trainingszeit übersetzen.</h2><p>Team Needs, Position Needs, Drill Library, Trainingsplan und Session Review laufen über einen gemeinsamen Workflow.</p></div><div className="to-selectors"><label><span>Saison</span><select value={seasonId} onChange={e=>void changeSeason(e.target.value)}>{data?.seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span>Training</span><select value={sessionId} onChange={e=>{const s=data?.sessions.find(x=>x.id===e.target.value);if(s)selectSession(s)}}><option value="">— Einheit wählen —</option>{data?.sessions.map(s=><option key={s.id} value={s.id}>{formatDate(s.startsAt)} · {s.title}</option>)}</select></label></div></AdminCard>
  <div className="to-kpis"><Metric label="PLAYERS" value={data?.summary.players??0}/><Metric label="GAME READY" value={data?.summary.gameReady??0}/><Metric label="FOCUS NEEDS" value={data?.summary.focusNeeds??0}/><Metric label="EVALUATE FIRST" value={data?.summary.evaluateFirst??0}/><Metric label="ATTENDANCE" value={data?.summary.attendancePct==null?"—":`${data.summary.attendancePct}%`}/><Metric label="PLAN MIN" value={`${totalMinutes}/${duration}`}/></div>
  <nav className="to-tabs">{(["plan","needs","drills","attendance","review"] as Tab[]).map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{({plan:"Trainingsplan",needs:"Training Needs",drills:"Drill Library",attendance:"Attendance",review:"Session Review"} as Record<Tab,string>)[t]}</button>)}</nav>
  {loading&&<AdminCard>Training Operations wird geladen…</AdminCard>}
  {!loading&&tab==="plan"&&<><AdminCard><div className="cms-section-head"><div><small>SESSION</small><h2>Planung</h2></div>{sessionId&&<div className="to-actions"><button className="cms-button secondary" onClick={()=>void generate()} disabled={saving}>Aus Development Needs erzeugen</button><button className="cms-button secondary" onClick={addPeriod}>＋ Period</button></div>}</div>{!sessionId?<p className="cms-muted">Lege eine Trainingseinheit an, um mit der Planung zu beginnen.</p>:<div className="to-form"><label><span>Titel</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span>Datum / Start</span><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label><span>Dauer Minuten</span><input type="number" min={30} max={240} value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label><label className="wide"><span>Session Objective</span><input value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Was soll nach diesem Training messbar besser sein?"/></label><label className="wide"><span>Coach Note</span><textarea rows={2} value={coachNote} onChange={e=>setCoachNote(e.target.value)}/></label></div>}</AdminCard>{sessionId&&<AdminCard><div className="cms-section-head"><div><small>PERIOD PLAN</small><h2>{totalMinutes} / {duration} Minuten</h2></div>{totalMinutes!==duration&&<span className="to-warning">{totalMinutes<duration?`${duration-totalMinutes} Min offen`:`${totalMinutes-duration} Min überplant`}</span>}</div><div className="to-periods">{periods.map((p,i)=><article key={p.id}><b>{i+1}</b><input value={p.title} onChange={e=>patchPeriod(p.id,{title:e.target.value})}/><select value={p.phase} onChange={e=>patchPeriod(p.id,{phase:e.target.value})}><option value="indy">INDY</option><option value="group">GROUP</option><option value="team">TEAM</option></select><input className="minutes" type="number" min={1} max={60} value={p.minutes} onChange={e=>patchPeriod(p.id,{minutes:Number(e.target.value)})}/><span className={`source ${p.sourceType}`}>{p.sourceType==="development-need"?`DATA · ${Math.round(p.sourceScore??0)}`:"MANUAL"}</span><button onClick={()=>removePeriod(p.id)}>×</button>{(p.note||p.coachingPoints)&&<small>{p.note}{p.coachingPoints?` · ${p.coachingPoints}`:""}</small>}</article>)}</div></AdminCard>}</>}
  {!loading&&tab==="needs"&&<AdminCard><div className="cms-section-head"><div><small>DATA-DRIVEN PRIORITIES</small><h2>Aktuelle Training Needs</h2></div></div><div className="to-needs">{data?.needs.map((n,i)=><article key={`${n.group}-${n.skillKey}`}><b>{i+1}</b><div><strong>{n.skillLabel}</strong><small>{n.groupLabel} · {n.category}</small></div><span>Need {n.needScore}</span><span>Coverage {n.coveragePct}%</span><em>{n.state.toUpperCase()}</em><small>{n.drills[0]?`Drill: ${n.drills[0].title}`:"Noch kein Drill verknüpft"}</small></article>)}</div></AdminCard>}
  {!loading&&tab==="drills"&&<AdminCard><div className="cms-section-head"><div><small>COACHING LIBRARY</small><h2>Drill Library</h2></div></div><div className="to-drills">{drillMap.map(d=><article key={d.id}><small>{d.phase.toUpperCase()} · {d.intensity.toUpperCase()} · {d.minMinutes}-{d.maxMinutes} MIN</small><h3>{d.title}</h3><p>{d.description}</p><strong>Coaching Points</strong><p>{d.coachingPoints}</p></article>)}</div></AdminCard>}
  {!loading&&tab==="attendance"&&<AdminCard><div className="cms-section-head"><div><small>AVAILABILITY & PARTICIPATION</small><h2>Attendance</h2></div></div><p className="cms-muted">Saisonweite Trainingsbeteiligung: <b>{data?.summary.attendancePct==null?"noch keine belastbaren Daten":`${data.summary.attendancePct}% Present`}</b>. Die detaillierte Erfassung bleibt mit den Performance-Einträgen verknüpft, damit Attendance und Spielerentwicklung dieselbe Datenbasis verwenden.</p><a className="cms-button" href="/admin/player-analysis?tab=performance">Spieler Performance öffnen →</a></AdminCard>}
  {!loading&&tab==="review"&&<AdminCard><div className="cms-section-head"><div><small>CLOSE THE LOOP</small><h2>Session Review</h2></div>{sessionId&&selected?.status!=="completed"&&<button className="cms-button" onClick={()=>void complete()} disabled={saving}>Training abschließen</button>}</div>{!selected?<p className="cms-muted">Training auswählen.</p>:selected.review?<div className="to-review"><Metric label="COMPLETION" value={`${selected.review.completionPct}%`}/><Metric label="OBJECTIVE" value={selected.review.objectiveMet?"MET":"OPEN"}/><div><small>WHAT WORKED</small><p>{selected.review.whatWorked||"—"}</p></div><div><small>NEXT FOCUS</small><p>{selected.review.nextFocus||"—"}</p></div><small>Review: {selected.review.reviewedBy} · {formatDate(selected.review.reviewedAt)}</small></div>:<p className="cms-muted">Nach dem Training wird hier dokumentiert, ob das Objective erreicht wurde, was funktioniert hat und welcher Fokus in die nächste Einheit übernommen wird.</p>}</AdminCard>}
 </AdminShell>
}
function Metric({label,value}:{label:string;value:string|number}){return <article className="to-metric"><small>{label}</small><b>{value}</b></article>}
function toLocal(value:string|null){if(!value)return"";const d=new Date(value),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,16)}
function formatDate(value:string|null){if(!value)return"Termin offen";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
