import { bindings, ensureCmsSchema } from "./cms";

export type BuilderSectionType="hero"|"text"|"split"|"stats"|"cards"|"gallery"|"timeline"|"cta"|"spacer"|"games"|"news"|"sponsors";
export type BuilderAlign="left"|"center"|"right";
export type BuilderBackgroundMode="color"|"gradient"|"image"|"video";
export type BuilderItem={id:string;eyebrow?:string;title?:string;subtitle?:string;text?:string;value?:string;image?:string;icon?:string;linkLabel?:string;linkUrl?:string};
export type BuilderResponsiveStyle={paddingTop?:number;paddingBottom?:number;minHeight?:number;align?:BuilderAlign;maxWidth?:number;headingScale?:number};
export type BuilderSectionStyle={background?:string;textColor?:string;accentColor?:string;paddingTop?:number;paddingBottom?:number;minHeight?:number;align?:BuilderAlign;maxWidth?:number;rounded?:number;border?:string;headingScale?:number;backgroundMode?:BuilderBackgroundMode;backgroundImage?:string;backgroundVideo?:string;backgroundGradient?:string;overlayColor?:string;overlayOpacity?:number;backgroundPosition?:string;backgroundFixed?:boolean;tablet?:BuilderResponsiveStyle;mobile?:BuilderResponsiveStyle};
export type BuilderSection={id:string;type:BuilderSectionType;variant?:string;visible:boolean;eyebrow?:string;title?:string;accent?:string;text?:string;image?:string;image2?:string;buttonLabel?:string;buttonUrl?:string;style:BuilderSectionStyle;items:BuilderItem[]};
export type BuilderPage={id:string;name:string;slug:string;enabled:boolean;showInNav:boolean;navLabel:string;title?:string;description?:string;sections:BuilderSection[]};
export type BuilderTheme={background:string;surface:string;text:string;muted:string;accent:string;headerBackground:string;headerText:string;contentWidth:number;radius:number;logoUrl:string;brandTop:string;brandBottom:string;navCtaLabel:string;navCtaUrl:string;footerTitle:string;footerSubtitle:string;headingFont:string;bodyFont:string;headingWeight:number;headingTracking:number;bodyLineHeight:number;headingTransform:"uppercase"|"none"};
export type SiteBuilderState={version:number;theme:BuilderTheme;pages:BuilderPage[]};

const LEGACY_KEY="site_builder";
const DRAFT_KEY="site_builder_draft_v3";
const PUBLISHED_KEY="site_builder_published_v3";
const icon=(name:string,color="e7192d")=>`https://api.iconify.design/${name.replace(":","/")}.svg?color=%23${color}`;
const sid=(name:string)=>`seed-${name}`;
const isLight=(bg:string)=>["#fff","#ffffff","#f4f4f1","#f5f5f2"].includes(bg.toLowerCase());
const style=(background="#050d18",align:BuilderAlign="left",minHeight=0):BuilderSectionStyle=>({background,textColor:isLight(background)?"#071421":"#ffffff",accentColor:"#e7192d",paddingTop:70,paddingBottom:70,minHeight,align,maxWidth:1600,rounded:0,border:"",headingScale:1,backgroundMode:"color",backgroundImage:"",backgroundVideo:"",backgroundGradient:"linear-gradient(135deg,#050d18,#0b1725)",overlayColor:"#020812",overlayOpacity:.45,backgroundPosition:"center",backgroundFixed:false,tablet:{paddingTop:58,paddingBottom:58,minHeight,align,maxWidth:1200,headingScale:.9},mobile:{paddingTop:42,paddingBottom:42,minHeight:0,align,maxWidth:720,headingScale:.72}});
const hero=(id:string,eyebrow:string,title:string,accent:string,text:string,image:string):BuilderSection=>({id:sid(id),type:"hero",variant:"cinematic",visible:true,eyebrow,title,accent,text,image,buttonLabel:"",buttonUrl:"",style:style("#050d18","left",560),items:[]});
const cta=(id:string):BuilderSection=>({id:sid(id),type:"cta",variant:"panel",visible:true,eyebrow:"YOUR NEXT PLAY",title:"READY TO JOIN",accent:"THE FAMILY?",text:"Du brauchst keine Erfahrung. Nur den Willen, Teil von etwas Größerem zu werden.",buttonLabel:"Probetraining anfragen",buttonUrl:"mailto:football@hsb1846.de",style:style("#071421","center",360),items:[]});

function templates():BuilderPage[]{return [
{id:"page-home",name:"Startseite",slug:"",enabled:false,showInNav:false,navLabel:"Startseite",title:"Hellenstein Rascals",description:"American Football in Heidenheim",sections:[
{...hero("home-hero","AMERICAN FOOTBALL · HEIDENHEIM","HART. ECHT.","RASCALS.","Ein Team. Eine Familie. Bereit für den nächsten Snap.","/helmet-hero-4k.webp"),buttonLabel:"Teil des Teams werden",buttonUrl:"mailto:football@hsb1846.de"},
{id:sid("home-stats"),type:"stats",variant:"strip",visible:true,eyebrow:"HELLENSTEIN RASCALS",title:"TEAM IN ZAHLEN",style:style("#071421","center"),items:[{id:"founded",value:"2023",title:"GEGRÜNDET"},{id:"field",value:"11",title:"SPIELER AUF DEM FELD"},{id:"family",value:"1",title:"RASCALS FAMILY"},{id:"home",value:"100%",title:"HEIDENHEIM"}]},
{id:sid("home-games"),type:"games",variant:"scoreboard",visible:true,eyebrow:"SAISON",title:"NÄCHSTE GAMES.",text:"Alle bestätigten Begegnungen der Rascals auf einen Blick.",style:style("#050d18","left"),items:[]},
{id:sid("home-story"),type:"split",variant:"image-left",visible:true,eyebrow:"MEHR ALS FOOTBALL",title:"EIN TEAM.",accent:"EINE FAMILIE.",text:"Seit 2023 bringen wir American Football zurück unter den Hellenstein. Bei uns zählen Einsatz, Fairness und der Mensch unter dem Helm.",image:"/team-victory-4k.webp",buttonLabel:"Unsere Geschichte",buttonUrl:"/ueber-uns",style:style("#ffffff","left"),items:[]},
{id:sid("home-news"),type:"news",variant:"editorial",visible:true,eyebrow:"INSIDE RASCALS",title:"FROM THE HUDDLE.",style:style("#f4f4f1","left"),items:[]},
{id:sid("home-sponsors"),type:"sponsors",variant:"ticker",visible:true,title:"PROUDLY POWERED BY",style:style("#ffffff","center"),items:[]},cta("home-cta")]},
{id:"page-about",name:"Über uns",slug:"ueber-uns",enabled:false,showInNav:true,navLabel:"Über uns",title:"Über uns · Hellenstein Rascals",description:"Die Geschichte der Hellenstein Rascals.",sections:[hero("about-hero","ÜBER UNS","HELLENSTEIN","RASCALS","Ein Team. Eine Stadt. Eine Mission.","/helmet-hero-4k.webp"),{id:sid("about-intro"),type:"text",variant:"editorial",visible:true,eyebrow:"DER ERSTE SNAP",title:"FOOTBALL IST TEAMARBEIT.",text:"Am 24. Mai 2023 wurde die American-Football-Abteilung des Heidenheimer Sportbunds gegründet. Das Ziel: sportlichen Ehrgeiz, Spaß und familiäre Identität zusammenbringen.",style:style("#ffffff","left"),items:[]},{id:sid("about-timeline"),type:"timeline",variant:"drive",visible:true,eyebrow:"UNSERE REISE.",title:"FROM FIRST SNAP TO NEXT LEVEL.",style:style("#030a13","center"),items:[{id:"2023",title:"2023",subtitle:"KICKOFF · AUFBAULIGA",text:"Gründung der Hellenstein Rascals. Der erste Schritt auf unserem Weg.",icon:icon("mdi:whistle-outline")},{id:"2025",title:"2025",subtitle:"NEXT DOWN · KREISLIGA",value:"139 : 137",text:"Viele Spiele, viele Lektionen und ein Team, das zusammen gewachsen ist.",icon:icon("ion:american-football-outline")},{id:"2026",title:"2026",subtitle:"MOVING THE CHAINS · KREISOBERLIGA",value:"170 : 66",text:"Mehr Erfahrung, mehr Wille, mehr Team. Der verdiente Aufstieg in die Kreisoberliga.",icon:icon("streamline-ultimate:american-football-helmet")},{id:"2027",title:"2027",subtitle:"NEXT LEVEL · BEZIRKSLIGA",text:"Unser nächstes Ziel: die Bezirksliga. Wir arbeiten. Wir glauben. Wir werden bereit sein.",icon:icon("bi:trophy")}]},{id:sid("about-values"),type:"cards",variant:"grid",visible:true,eyebrow:"WOFÜR WIR STEHEN",title:"RASCALS VALUES",style:style("#071421","left"),items:[{id:"team",title:"TEAMGEIST",text:"Wir gewinnen zusammen, wir lernen zusammen.",icon:icon("mdi:account-group-outline")},{id:"fair",title:"FAIRNESS",text:"Respekt gilt auf und neben dem Feld.",icon:icon("mdi:shield-check-outline")},{id:"dev",title:"ENTWICKLUNG",text:"Jeder Rep bringt uns als Team weiter.",icon:icon("mdi:trending-up")},{id:"home",title:"HEIMAT",text:"Heidenheim ist in unserem Namen und Herzen.",icon:icon("mdi:map-marker-outline")}]},cta("about-cta")]},
{id:"page-team",name:"Team",slug:"team",enabled:false,showInNav:true,navLabel:"Team",title:"Team · Hellenstein Rascals",description:"Roster, Coaches und Teams der Hellenstein Rascals.",sections:[hero("team-hero","ROSTER & COACHES","ONE TEAM.","ALL IN.","Auf dem Feld zählt nicht, wo du angefangen hast – sondern was du für das Team gibst.","/team-juniors-new-4k.webp"),{id:sid("team-cards"),type:"cards",variant:"editorial",visible:true,eyebrow:"RASCALS FAMILY",title:"DEIN PLATZ IM TEAM.",text:"Football-Erfahrung ist für den Einstieg nicht nötig; Motivation und Verlässlichkeit schon.",style:style("#ffffff","left"),items:[{id:"seniors",title:"TACKLE FOOTBALL",subtitle:"SENIORS · AB 18",text:"Wettkampf, Technik und Athletik – mit einem Team, das dich fordert und trägt.",image:"/team-walk-4k.webp"},{id:"juniors",title:"NEXT GENERATION",subtitle:"JUNIORS · 14–18",text:"Grundlagen sicher lernen, Verantwortung übernehmen und als Spieler wachsen.",image:"/team-juniors-new-4k.webp"}]},cta("team-cta")]},
{id:"page-sponsoring",name:"Sponsoring",slug:"sponsoring",enabled:false,showInNav:true,navLabel:"Sponsoring",title:"Sponsoring · Hellenstein Rascals",description:"Partner und Sponsoring der Hellenstein Rascals.",sections:[hero("sponsor-hero","PARTNER DER RASCALS","BUILD WITH","THE RASCALS.","Gemeinsam schaffen wir Sichtbarkeit, Nachwuchsarbeit und Football in der Region.","/team-entry-4k.webp"),{id:sid("sponsor-live"),type:"sponsors",variant:"ticker",visible:true,title:"UNSERE PARTNER",style:style("#ffffff","center"),items:[]},cta("sponsor-cta")]},
{id:"page-shop",name:"Shop",slug:"shop",enabled:false,showInNav:true,navLabel:"Shop",title:"Shop · Hellenstein Rascals",description:"Offizielle Rascals Teamwear.",sections:[hero("shop-hero","OFFICIAL TEAMWEAR","WEAR THE","RASCALS.","Zeig deine Farben – auf der Tribüne, im Training und überall dazwischen.","/shop-product-4k.webp"),{id:sid("shop-cta"),type:"cta",variant:"panel",visible:true,eyebrow:"RASCALS SHOP",title:"OFFICIAL",accent:"TEAMWEAR.",text:"Direkt im offiziellen Rascals Shop bestellen.",buttonLabel:"Zum Shop",buttonUrl:"https://hellenstein-rascals.myshopify.com",style:style("#071421","center",360),items:[]}]},
{id:"page-news",name:"News",slug:"news",enabled:false,showInNav:true,navLabel:"News",title:"News · Hellenstein Rascals",description:"News und Stories der Hellenstein Rascals.",sections:[hero("news-hero","INSIDE RASCALS","FROM THE","HUDDLE.","News, Gamedays und Geschichten aus der Rascals Family.","/team-players-4k.webp"),{id:sid("news-feed"),type:"news",variant:"editorial",visible:true,eyebrow:"LATEST",title:"NEWS & STORIES",style:style("#f4f4f1","left"),items:[]}]},
{id:"page-gallery",name:"Galerie",slug:"galerie",enabled:false,showInNav:true,navLabel:"Galerie",title:"Galerie · Hellenstein Rascals",description:"Bilder der Hellenstein Rascals.",sections:[hero("gallery-hero","RASCALS IN ACTION","GAME DAY.","CAPTURED.","Momente auf und neben dem Feld.","/team-huddle-4k.webp"),{id:sid("gallery-grid"),type:"gallery",variant:"masonry",visible:true,eyebrow:"SIDELINE STORIES",title:"GALERIE",style:style("#050d18","left"),items:[{id:"g1",image:"/team-entry-4k.webp",title:"Game Day"},{id:"g2",image:"/team-players-4k.webp",title:"Rascals"},{id:"g3",image:"/team-celebrate-4k.webp",title:"Team"},{id:"g4",image:"/team-huddle-4k.webp",title:"Huddle"},{id:"g5",image:"/team-walk-4k.webp",title:"All In"}]}]}
]}

export const defaultSiteBuilderState:SiteBuilderState={version:3,theme:{background:"#050d18",surface:"#0b1725",text:"#ffffff",muted:"#9aa7b7",accent:"#e7192d",headerBackground:"#050d18",headerText:"#ffffff",contentWidth:1600,radius:0,logoUrl:"/rascals-logo-transparent-4k.png",brandTop:"HELLENSTEIN",brandBottom:"RASCALS",navCtaLabel:"Mitmachen",navCtaUrl:"mailto:football@hsb1846.de",footerTitle:"HELLENSTEIN RASCALS",footerSubtitle:"American Football · Heidenheim",headingFont:"Inter, Arial, sans-serif",bodyFont:"Inter, Arial, sans-serif",headingWeight:950,headingTracking:-.04,bodyLineHeight:1.65,headingTransform:"uppercase"},pages:templates()};

function cleanSlug(value:string){return value.trim().toLowerCase().replace(/^\/+|\/+$/g,"").replace(/[^a-z0-9äöüß-]+/g,"-").replace(/-+/g,"-")}
function numberOr(value:unknown,fallback:number){const n=Number(value);return Number.isFinite(n)?n:fallback}
function clamp(value:unknown,min:number,max:number,fallback:number){return Math.min(max,Math.max(min,numberOr(value,fallback)))}
function alignOr(value:unknown,fallback:BuilderAlign="left"):BuilderAlign{return value==="center"||value==="right"||value==="left"?value:fallback}
function normalizeResponsive(input:BuilderResponsiveStyle|undefined,fallback:BuilderResponsiveStyle):BuilderResponsiveStyle{const value=input??{};return{paddingTop:Math.max(0,numberOr(value.paddingTop,fallback.paddingTop??0)),paddingBottom:Math.max(0,numberOr(value.paddingBottom,fallback.paddingBottom??0)),minHeight:Math.max(0,numberOr(value.minHeight,fallback.minHeight??0)),align:alignOr(value.align,fallback.align??"left"),maxWidth:Math.max(280,numberOr(value.maxWidth,fallback.maxWidth??1200)),headingScale:clamp(value.headingScale,.45,1.8,fallback.headingScale??1)}}
function normalizeSection(section:Partial<BuilderSection>):BuilderSection{const s=section.style??{};const desktopAlign=alignOr(s.align,"left");const desktopMin=Math.max(0,numberOr(s.minHeight,0));return{id:section.id||crypto.randomUUID(),type:section.type||"text",variant:section.variant||"default",visible:section.visible!==false,eyebrow:section.eyebrow??"",title:section.title??"",accent:section.accent??"",text:section.text??"",image:section.image??"",image2:section.image2??"",buttonLabel:section.buttonLabel??"",buttonUrl:section.buttonUrl??"",style:{background:s.background||"#050d18",textColor:s.textColor||"#ffffff",accentColor:s.accentColor||"#e7192d",paddingTop:Math.max(0,numberOr(s.paddingTop,64)),paddingBottom:Math.max(0,numberOr(s.paddingBottom,64)),minHeight:desktopMin,align:desktopAlign,maxWidth:Math.max(320,numberOr(s.maxWidth,1600)),rounded:Math.max(0,numberOr(s.rounded,0)),border:s.border||"",headingScale:clamp(s.headingScale,.45,1.8,1),backgroundMode:s.backgroundMode==="gradient"||s.backgroundMode==="image"||s.backgroundMode==="video"?s.backgroundMode:"color",backgroundImage:s.backgroundImage||"",backgroundVideo:s.backgroundVideo||"",backgroundGradient:s.backgroundGradient||"linear-gradient(135deg,#050d18,#0b1725)",overlayColor:s.overlayColor||"#020812",overlayOpacity:clamp(s.overlayOpacity,0,1,.45),backgroundPosition:s.backgroundPosition||"center",backgroundFixed:s.backgroundFixed===true,tablet:normalizeResponsive(s.tablet,{paddingTop:56,paddingBottom:56,minHeight:desktopMin,align:desktopAlign,maxWidth:1200,headingScale:.9}),mobile:normalizeResponsive(s.mobile,{paddingTop:40,paddingBottom:40,minHeight:0,align:desktopAlign,maxWidth:720,headingScale:.72})},items:Array.isArray(section.items)?section.items.map(item=>({id:item.id||crypto.randomUUID(),...item})):[]}}
function normalizePage(page:Partial<BuilderPage>):BuilderPage{return{id:page.id||crypto.randomUUID(),name:page.name||"Neue Seite",slug:cleanSlug(page.slug||""),enabled:page.enabled===true,showInNav:page.showInNav===true,navLabel:page.navLabel||page.name||"Seite",title:page.title||"",description:page.description||"",sections:Array.isArray(page.sections)?page.sections.map(normalizeSection):[]}}
function migratePages(input:Partial<SiteBuilderState>):BuilderPage[]{const incoming=Array.isArray(input.pages)?input.pages:[];const base=templates();const merged=base.map(template=>{const previous=incoming.find(page=>page.id===template.id||cleanSlug(page.slug||"")===template.slug);if(!previous)return template;const normalized=normalizePage(previous);return normalized.sections.length?normalized:{...template,enabled:normalized.enabled,showInNav:normalized.showInNav,navLabel:normalized.navLabel,title:normalized.title||template.title,description:normalized.description||template.description}});const custom=incoming.filter(page=>!base.some(template=>template.id===page.id||template.slug===cleanSlug(page.slug||""))).map(normalizePage);return[...merged,...custom]}
function normalizeState(input:Partial<SiteBuilderState>):SiteBuilderState{const raw=input.theme??{};const theme:BuilderTheme={...defaultSiteBuilderState.theme,...raw,contentWidth:Math.max(800,numberOr(raw.contentWidth,1600)),radius:Math.max(0,numberOr(raw.radius,0)),headingWeight:clamp(raw.headingWeight,100,1000,950),headingTracking:clamp(raw.headingTracking,-.12,.2,-.04),bodyLineHeight:clamp(raw.bodyLineHeight,1,2.4,1.65),headingTransform:raw.headingTransform==="none"?"none":"uppercase"};const pages=numberOr(input.version,1)<2?migratePages(input):Array.isArray(input.pages)?input.pages.map(normalizePage):templates();return{version:3,theme,pages}}
async function readKey(key:string):Promise<SiteBuilderState|null>{await ensureCmsSchema();const{DB}=bindings();const row=await DB.prepare("SELECT value FROM cms_settings WHERE key = ?").bind(key).first<{value:string}>();if(!row?.value)return null;try{return normalizeState(JSON.parse(row.value) as SiteBuilderState)}catch{return null}}
async function writeKey(key:string,state:SiteBuilderState){await ensureCmsSchema();const normalized=normalizeState(state);const{DB}=bindings();await DB.prepare(`INSERT INTO cms_settings (key,value,updated_at) VALUES (?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(key,JSON.stringify(normalized)).run();return normalized}
export async function readSiteBuilderState():Promise<SiteBuilderState>{return await readKey(DRAFT_KEY)??await readKey(LEGACY_KEY)??defaultSiteBuilderState}
export async function writeSiteBuilderState(state:SiteBuilderState){return await writeKey(DRAFT_KEY,state)}
export async function readPublishedSiteBuilderState():Promise<SiteBuilderState>{return await readKey(PUBLISHED_KEY)??await readKey(LEGACY_KEY)??defaultSiteBuilderState}
export async function publishSiteBuilderState(state:SiteBuilderState){const normalized=await writeKey(PUBLISHED_KEY,state);await writeKey(DRAFT_KEY,normalized);return normalized}
export function normalizeSiteBuilderState(state:Partial<SiteBuilderState>){return normalizeState(state)}
export function findBuilderPage(state:SiteBuilderState,slug:string){const normalized=cleanSlug(slug);return state.pages.find(page=>page.slug===normalized)}
