"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminNotice, AdminShell } from "../../_components/AdminShell";
import "./game-operations.css";

type Game = {
  id:string; slug:string; opponent:string; opponentLogo:string; venue:string; homeAway:string; kickoff:string|null; status:string;
  rascalsScore:number; opponentScore:number; quarter:string; gameClock:string; seasonId:string; seasonYear:number|null; seasonName:string;
  rosterStatus:string; lockedAt:string|null; lockedBy:string; activeRoster:number; inactiveRoster:number; eventCount:number; provisionalStats:number; reviewedStats:number; officialStats:number;
};
type RosterEntry={status:string;starter:boolean;captain:boolean;emergency:boolean;specialTeamsRole:string;availability:string;position:string;firstName:string;lastName:string;jerseyNumber:number|null};
type EventItem={id:string;eventType:string;points:number;quarter:string;gameClock:string;text:string;createdAt:string};
type Payload={games:Game[];game:Game|null;roster:RosterEntry[];recentEvents:EventItem[];readiness:{scheduleComplete:boolean;opponentLogo:boolean;rosterInitialized:boolean;rosterLocked:boolean;availabilityClear:boolean;postgameReviewed:boolean};summary:{totalGames:number;upcomingGames:number;finalGames:number;liveGames:number;nextGameId:string|null;activeRoster:number;inactiveRoster:number;eventCount:number;provisionalStats:number;reviewedStats:number;officialStats:number}};
type Mode="overview"|"schedule"|"roster"|"live"|"postgame";

export function GameOperationsManager(){
 const[data,setData]=useState<Payload|null>(null);const[gameId,setGameId]=useState("");const[mode,setMode]=useState<Mode>("overview");const[loading,setLoading]=useState(true);const[notice,setNotice]=useState("");
 useEffect(()=>{void boot()},[]);
 async function boot(){const q=new URLSearchParams(window.location.search);await load(q.get("game")||undefined)}
 async function load(id?:string){setLoading(true);setNotice("");try{const q=new URLSearchParams();if(id)q.set("gameId",id);const r=await fetch(`/admin/api/game-operations?${q}`);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Spielbetrieb konnte nicht geladen werden.")}const b=await r.json() as Payload;setData(b);setGameId(b.game?.id??"");}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 async function changeGame(id:string){setGameId(id);window.history.replaceState(null,"",`/admin/game-operations?game=${encodeURIComponent(id)}`);await load(id)}
 const selected=data?.game;
 const readiness=useMemo(()=>data?Object.entries(data.readiness):[],[data]);
 const rosterWarnings=(data?.roster??[]).filter(x=>x.status==="active"&&x.availability==="out");
 const starters=(data?.roster??[]).filter(x=>x.status==="active"&&x.starter);
 return <AdminShell active="gameoperations" title="Spielbetrieb" eyebrow="RASCALS OS · GAME OPERATIONS CENTER" actions={<>{selected&&<a className="cms-button secondary" href={`/admin/games?game=${encodeURIComponent(selected.id)}`}>Spiel bearbeiten</a>}{selected&&<a className="cms-button" href={`/admin/gameday?game=${encodeURIComponent(selected.id)}`}>Gameday öffnen</a>}</>}>
  {notice&&<AdminNotice tone="error">{notice}</AdminNotice>}
  <AdminCard className="go-hero"><div><small>GAME WEEK COMMAND</small><h2>Schedule, Roster, Live-Betrieb und Postgame in einem Workflow.</h2><p>Der Head Coach oder Gameday Lead arbeitet aus einem einzigen Spielkontext heraus. Spezialeditoren bleiben verfügbar, aber die operative Steuerung liegt hier zentral.</p></div><label className="cms-field"><span>Spiel auswählen</span><select disabled={loading} value={gameId} onChange={e=>void changeGame(e.target.value)}>{data?.games.map(g=><option key={g.id} value={g.id}>{g.status==="live"?"LIVE · ":""}{formatDate(g.kickoff)} · {g.homeAway==="away"?"@":"vs"} {g.opponent}</option>)}</select></label></AdminCard>
  {!selected&&!loading&&<AdminNotice tone="info">Noch kein Spiel vorhanden.</AdminNotice>}
  {selected&&<>
   <AdminCard className="go-matchup"><div className="go-logo"><img src="/rascals-logo-transparent-4k.png" alt="Rascals"/></div><div className="go-center"><small>{selected.seasonName||"SAISON"} · {formatDate(selected.kickoff)}</small><h2>RASCALS <span>{selected.homeAway==="away"?"@":"VS"}</span> {selected.opponent}</h2><p>{selected.venue||"Ort noch offen"}</p><div className="go-score">{selected.status==="final"||selected.status==="live"?<><b>{selected.rascalsScore}</b><span>:</span><b>{selected.opponentScore}</b></>:<strong>{statusLabel(selected.status)}</strong>}</div></div><div className="go-logo">{selected.opponentLogo?<img src={selected.opponentLogo} alt={selected.opponent}/>:<div className="go-placeholder">?</div>}</div></AdminCard>
   <div className="go-kpis"><Metric label="Active Roster" value={data?.summary.activeRoster}/><Metric label="Inactive" value={data?.summary.inactiveRoster}/><Metric label="Live Events" value={data?.summary.eventCount}/><Metric label="Provisional" value={data?.summary.provisionalStats} risk={Boolean(data?.summary.provisionalStats)}/><Metric label="Reviewed" value={data?.summary.reviewedStats}/><Metric label="Official" value={data?.summary.officialStats}/></div>
   <div className="go-tabs"><button className={mode==="overview"?"active":""} onClick={()=>setMode("overview")}>Übersicht</button><button className={mode==="schedule"?"active":""} onClick={()=>setMode("schedule")}>Schedule</button><button className={mode==="roster"?"active":""} onClick={()=>setMode("roster")}>Gameday Roster</button><button className={mode==="live"?"active":""} onClick={()=>setMode("live")}>Live Command</button><button className={mode==="postgame"?"active":""} onClick={()=>setMode("postgame")}>Postgame</button></div>
   {mode==="overview"&&<div className="go-grid"><AdminCard><div className="cms-section-head"><div><small>READINESS</small><h2>Game Readiness</h2></div></div><div className="go-checks">{readiness.map(([k,v])=><div key={k} className={v?"ok":"warn"}><b>{v?"✓":"!"}</b><span>{readinessLabel(k)}</span><em>{v?"OK":"Prüfen"}</em></div>)}</div></AdminCard><AdminCard><div className="cms-section-head"><div><small>NEXT ACTION</small><h2>Operative Schritte</h2></div></div><div className="go-actions"><a href={`/admin/gameday-roster?game=${selected.id}`}>Gameday Roster {selected.rosterStatus==="locked"?"prüfen":"vorbereiten"} →</a><a href={`/admin/gameday?game=${selected.id}`}>Live Command öffnen →</a><a href={`/admin/stats?game=${selected.id}`}>Stats Review öffnen →</a><a href={`/admin/stats/analytics?game=${selected.id}`}>Box Score / Analytics →</a></div></AdminCard></div>}
   {mode==="schedule"&&<AdminCard><div className="cms-section-head"><div><small>SEASON SCHEDULE</small><h2>Spiele</h2></div><a className="cms-button" href="/admin/games">Spielplan bearbeiten</a></div><div className="go-schedule">{data?.games.map(g=><button key={g.id} className={g.id===selected.id?"active":""} onClick={()=>void changeGame(g.id)}><span>{formatDate(g.kickoff)}</span><b>{g.homeAway==="away"?"@":"vs"} {g.opponent}</b><em>{g.status==="final"?`${g.rascalsScore}:${g.opponentScore}`:statusLabel(g.status)}</em><small>Roster: {g.rosterStatus}</small></button>)}</div></AdminCard>}
   {mode==="roster"&&<><div className="go-grid"><AdminCard><div className="cms-section-head"><div><small>ROSTER STATUS</small><h2>{selected.rosterStatus.toUpperCase()}</h2></div><a className="cms-button" href={`/admin/gameday-roster?game=${selected.id}`}>Roster bearbeiten</a></div><p className="cms-muted">{selected.rosterStatus==="locked"?`Historisch gesperrt${selected.lockedAt?` am ${formatDateTime(selected.lockedAt)}`:""}.`:`Der Spieltagskader ist ${selected.rosterStatus==="not-started"?"noch nicht initialisiert":"noch bearbeitbar"}.`}</p>{rosterWarnings.length>0&&<AdminNotice tone="info">{rosterWarnings.length} OUT-Spieler stehen noch auf ACTIVE.</AdminNotice>}</AdminCard><AdminCard><div className="cms-section-head"><div><small>STARTING PERSONNEL</small><h2>{starters.length} Starter</h2></div></div><div className="go-personnel">{starters.slice(0,16).map(p=><span key={`${p.firstName}-${p.lastName}-${p.position}`}>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName}<small>{p.position}</small></span>)}</div></AdminCard></div><AdminCard><div className="cms-section-head"><div><small>GAME DAY PERSONNEL</small><h2>Active / Inactive</h2></div></div><div className="go-roster-list">{data?.roster.map((p,i)=><div key={`${p.firstName}-${p.lastName}-${i}`} className={p.status}><b>#{p.jerseyNumber??"–"}</b><span>{p.firstName} {p.lastName}<small>{p.position} · {p.availability.toUpperCase()}</small></span><em>{p.status.toUpperCase()}</em>{p.captain&&<strong>C</strong>}{p.emergency&&<strong>E</strong>}</div>)}</div></AdminCard></>}
   {mode==="live"&&<div className="go-grid"><AdminCard><div className="cms-section-head"><div><small>LIVE STATE</small><h2>{statusLabel(selected.status)}</h2></div><a className="cms-button" href={`/admin/gameday?game=${selected.id}`}>Command öffnen</a></div><div className="go-live-score"><b>{selected.rascalsScore}</b><span>:</span><b>{selected.opponentScore}</b></div><p className="cms-muted">{selected.quarter||"Quarter –"} · {selected.gameClock||"Clock –"}</p></AdminCard><AdminCard><div className="cms-section-head"><div><small>RECENT FEED</small><h2>Letzte Events</h2></div></div><div className="go-events">{data?.recentEvents.map(e=><article key={e.id}><small>{e.quarter||"–"} {e.gameClock||""}</small><b>{e.text||e.eventType}</b>{e.points!==0&&<em>+{e.points}</em>}</article>)}{!data?.recentEvents.length&&<p className="cms-muted">Noch keine Live-Events.</p>}</div></AdminCard></div>}
   {mode==="postgame"&&<div className="go-grid"><AdminCard><div className="cms-section-head"><div><small>STAT WORKFLOW</small><h2>Review Status</h2></div><a className="cms-button" href={`/admin/stats?game=${selected.id}`}>Stats Review</a></div><div className="go-stat-status"><span><b>{selected.provisionalStats}</b><small>PROVISIONAL</small></span><span><b>{selected.reviewedStats}</b><small>REVIEWED</small></span><span><b>{selected.officialStats}</b><small>OFFICIAL</small></span></div>{data?.readiness.postgameReviewed?<AdminNotice tone="success">Postgame-Stats sind vollständig auf Official.</AdminNotice>:<AdminNotice tone="info">Postgame ist noch nicht abgeschlossen. Provisional/Reviewed Stats prüfen und final freigeben.</AdminNotice>}</AdminCard><AdminCard><div className="cms-section-head"><div><small>POSTGAME OUTPUT</small><h2>Ergebnis & Analyse</h2></div></div><div className="go-actions"><a href={`/admin/stats/analytics?game=${selected.id}`}>Official Box Score →</a><a href={`/admin/player-analysis?season=${selected.seasonId}`}>Spieler & Analyse →</a><a href={`/admin/development/team?season=${selected.seasonId}`}>Team Development →</a></div></AdminCard></div>}
  </>}
 </AdminShell>
}
function Metric({label,value,risk=false}:{label:string;value:number|undefined;risk?:boolean}){return <article className={risk?"risk":""}><small>{label}</small><b>{value??0}</b></article>}
function formatDate(value:string|null){if(!value)return"Termin offen";return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(value))}
function formatDateTime(value:string|null){return value?new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"–"}
function statusLabel(status:string){return ({upcoming:"UPCOMING",live:"LIVE",final:"FINAL",postponed:"POSTPONED",cancelled:"CANCELLED"} as Record<string,string>)[status]??status.toUpperCase()}
function readinessLabel(key:string){return ({scheduleComplete:"Spielinformationen vollständig",opponentLogo:"Gegnerlogo hinterlegt",rosterInitialized:"Gameday Roster aufgebaut",rosterLocked:"Gameday Roster gesperrt",availabilityClear:"Keine OUT-Spieler auf ACTIVE",postgameReviewed:"Postgame Stats official"} as Record<string,string>)[key]??key}
