"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminNotice, AdminShell } from "../_components/AdminShell";
import { ImageUploadField } from "../_components/ImageUploadField";
import "./sponsors.css";

type Sponsor={id:string;name:string;logo:string;url:string;tier:"premium"|"gold"|"silver"|"partner";sortOrder:number;active:boolean;startsAt:string|null;endsAt:string|null;createdAt:string;updatedAt:string;deletedAt?:string|null};
const empty:Sponsor={id:"",name:"",logo:"",url:"",tier:"partner",sortOrder:0,active:true,startsAt:null,endsAt:null,createdAt:"",updatedAt:"",deletedAt:null};

export function SponsorsManager(){
 const[items,setItems]=useState<Sponsor[]>([]);const[selected,setSelected]=useState<Sponsor>(empty);const[query,setQuery]=useState("");const[notice,setNotice]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);try{const s=await fetch("/admin/api/sponsors");if(!s.ok)throw new Error("Sponsoren konnten nicht geladen werden.");const sb=await s.json() as {items:Sponsor[]};setItems(sb.items);setSelected(sb.items[0]??empty)}catch(e){setNotice(e instanceof Error?e.message:"Unbekannter Fehler")}finally{setLoading(false)}}
 async function save(){if(!selected.name.trim()){setNotice("Bitte Sponsor-Namen eingeben.");return}setSaving(true);const r=await fetch("/admin/api/sponsors",{method:selected.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(selected)});if(!r.ok){setNotice("Speichern fehlgeschlagen.");setSaving(false);return}const b=await r.json() as {item:Sponsor};setItems(cur=>selected.id?cur.map(x=>x.id===b.item.id?b.item:x):[...cur,b.item]);setSelected(b.item);setNotice("Sponsor gespeichert.");setSaving(false)}
 async function remove(){if(!selected.id||!confirm(`„${selected.name}“ in den Papierkorb verschieben?`))return;const r=await fetch(`/admin/api/sponsors?id=${encodeURIComponent(selected.id)}`,{method:"DELETE"});if(!r.ok){setNotice("Verschieben in den Papierkorb fehlgeschlagen.");return}const next=items.filter(x=>x.id!==selected.id);setItems(next);setSelected(next[0]??empty);setNotice("Sponsor wurde in den Papierkorb verschoben.")}
 const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.tier}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 return <AdminShell active="sponsors" title="Sponsoren verwalten" actions={<button className="cms-button" disabled={saving||loading} onClick={()=>void save()}>{saving?"Speichert…":"Speichern"}</button>}>
  {notice&&<AdminNotice tone={notice.includes("fehl")?"error":"success"}>{notice}</AdminNotice>}
  <div className="sponsors-cms-grid">
   <AdminCard><div className="cms-section-head"><div><small>PARTNER</small><h2>Sponsoren</h2></div><button className="cms-button secondary" onClick={()=>setSelected(empty)}>＋ Sponsor</button></div><input className="sponsor-search" placeholder="Sponsoren durchsuchen…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="sponsor-items">{filtered.map(item=><button key={item.id} className={selected.id===item.id?"active":""} onClick={()=>setSelected(item)}><b>{item.name}</b><small>{item.tier.toUpperCase()} · {item.active?"AKTIV":"INAKTIV"}</small></button>)}</div></AdminCard>
   <div className="sponsor-editor-stack"><AdminCard><div className="cms-section-head"><div><small>DETAILS</small><h2>{selected.id?"Sponsor bearbeiten":"Sponsor hinzufügen"}</h2></div>{selected.id&&<button className="cms-button secondary danger" onClick={()=>void remove()}>In Papierkorb</button>}</div><div className="cms-grid-2"><label className="cms-field"><span>Name</span><input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label className="cms-field"><span>Website</span><input value={selected.url} onChange={e=>setSelected({...selected,url:e.target.value})} placeholder="https://..."/></label><label className="cms-field"><span>Kategorie</span><select value={selected.tier} onChange={e=>setSelected({...selected,tier:e.target.value as Sponsor["tier"]})}><option value="premium">Premium</option><option value="gold">Gold</option><option value="silver">Silver</option><option value="partner">Partner</option></select></label><label className="cms-field"><span>Reihenfolge</span><input type="number" value={selected.sortOrder} onChange={e=>setSelected({...selected,sortOrder:Number(e.target.value)})}/></label><ImageUploadField label="Logo" value={selected.logo} onChange={logo=>setSelected({...selected,logo})} helper="Logo direkt hochladen. Es wird automatisch in der Medienablage gespeichert und dem Sponsor zugeordnet."/></div></AdminCard><AdminCard><div className="cms-section-head"><div><small>LAUFZEIT</small><h2>Sichtbarkeit</h2></div></div><div className="sponsor-schedule"><label className="hero-switch"><input type="checkbox" checked={selected.active} onChange={e=>setSelected({...selected,active:e.target.checked})}/><span/><b>{selected.active?"Aktiv":"Inaktiv"}</b></label><label className="cms-field"><span>Start (optional)</span><input type="datetime-local" value={toLocal(selected.startsAt)} onChange={e=>setSelected({...selected,startsAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label><label className="cms-field"><span>Ende (optional)</span><input type="datetime-local" value={toLocal(selected.endsAt)} onChange={e=>setSelected({...selected,endsAt:e.target.value?new Date(e.target.value).toISOString():null})}/></label></div></AdminCard><AdminCard><small>LIVE-VORSCHAU</small><div className={`sponsor-live-preview ${selected.tier}`}>{selected.logo?<img src={selected.logo} alt=""/>:<span>LOGO</span>}<b>{selected.name||"Sponsorname"}</b><em>{selected.tier.toUpperCase()}</em></div></AdminCard></div>
  </div>
 </AdminShell>
}
function toLocal(value:string|null){if(!value)return"";const d=new Date(value),offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,16)}
