"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminNotice, AdminShell } from "../_components/AdminShell";
import "./team-management.css";

type Season={id:string;year:number;name:string;status:string;isCurrent:boolean};
type Player={id:string;playerId:string;jerseyNumber:number|null;firstName:string;lastName:string;nickname:string;portrait:string;primaryPosition:string;secondaryPosition:string;unit:string;rosterStatus:string;availability:string;planningStatus:string;starter:boolean;captain:boolean;rookie:boolean;leadershipRole:string;heightCm:number|null;weightKg:number|null};
type Depth={positionGroup:string;position:string;rank:number;playerId:string;firstName:string;lastName:string;jerseyNumber:number|null};
type Coach={id:string;firstName:string;lastName:string;role:string;photo:string;active:boolean};
type PositionGroup={label:string;players:number;gameReady:number;starters:number;limited:number};
type Payload={seasons:Season[];season:Season;roster:Player[];depth:Depth[];coaches:Coach[];positionGroups:PositionGroup[];planning:{returning:number;unsure:number;leaving:number;unknown:number};summary:{roster:number;gameReady:number;gameReadyPct:number;limited:number;out:number;starters:number;captains:number;rookies:number;coaches:number;depthPositions:number}};
type Tab="overview"|"roster"|"depth"|"availability"|"planning"|"coaches";

const rosterOptions=["active","practice-squad","reserve","injured","suspended","left","alumni"];
const availabilityOptions=["full","limited","questionable","out","return-to-play"];
const planningOptions=["unknown","returning","unsure","leaving"];

export function TeamManagementManager(){
 const[data,setData]=useState<Payload|null>(null);const[seasonId,setSeasonId]=useState("");const[tab,setTab]=useState<Tab>("overview");const[query,setQuery]=useState("");const[unit,setUnit]=useState("all");const[notice,setNotice]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState("");
 useEffect(()=>{void boot()},[]);
 async function boot(){const p=new URLSearchParams(window.location.search);const initialTab=(p.get("tab")||"overview") as Tab;setTab(["overview","roster","depth","availability","planning","coaches"].includes(initialTab)?initialTab:"overview");await load(p.get("season")||undefined)}
 async function load(nextSeason?:string){setLoading(true);setNotice("");try{const q=new URLSearchParams();if(nextSeason)q.set("seasonId",nextSeason);const r=await fetch(`/admin/api/team-management?${q}`);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Team & Kader konnte nicht geladen werden.")}const b=await r.json() as Payload;setData(b);setSeasonId(b.season.id)}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 function changeTab(next:Tab){setTab(next);const p=new URLSearchParams(window.location.search);p.set("tab",next);if(seasonId)p.set("season",seasonId);window.history.replaceState(null,"",`/admin/team-management?${p}`)}
 async function changeSeason(next:string){setSeasonId(next);const p=new URLSearchParams(window.location.search);p.set("season",next);p.set("tab",tab);window.history.replaceState(null,"",`/admin/team-management?${p}`);await load(next)}
 async function updatePlayer(player:Player,patch:Partial<Player>){if(!data)return;const next={...player,...patch};setData(cur=>cur?{...cur,roster:cur.roster.map(p=>p.playerId===player.playerId?next:p)}:cur);setSaving(player.playerId);setNotice("");try{const r=await fetch("/admin/api/team-management",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({action:"roster-update",seasonId:data.season.id,playerId:player.playerId,rosterStatus:next.rosterStatus,availability:next.availability,planningStatus:next.planningStatus,starter:next.starter,captain:next.captain})});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Änderung konnte nicht gespeichert werden.")}await load(data.season.id);setNotice(`Kaderstatus von ${player.firstName} ${player.lastName} aktualisiert.`)}catch(e){setNotice(e instanceof Error?e.message:"Speichern fehlgeschlagen.");await load(data.season.id)}finally{setSaving("")}}
 const filtered=useMemo(()=>data?.roster.filter(p=>(unit==="all"||p.unit===unit)&&`${p.firstName} ${p.lastName} ${p.primaryPosition} ${p.jerseyNumber??""}`.toLowerCase().includes(query.toLowerCase()))??[],[data,unit,query]);
 return <AdminShell active="teammanagement" title="Team & Kader" eyebrow="RASCALS OS · FOOTBALL OPERATIONS" actions={<><a className="cms-button secondary" href="/admin/player-analysis">Spieler & Analyse</a><a className="cms-button secondary" href="/admin/game-operations">Spielbetrieb</a></>}>
  {notice&&<AdminNotice tone={notice.includes("aktualisiert")?"success":"error"}>{notice}</AdminNotice>}
  <AdminCard className="tm-hero"><div><small>ONE TEAM WORKSPACE</small><h2>Kader, Depth, Availability und Saisonplanung in einer Oberfläche.</h2><p>Die technischen Module bleiben getrennt. Für Coaches und Football Operations werden sie hier als ein zusammenhängender Workflow dargestellt.</p></div><label className="cms-field"><span>Saison</span><select disabled={loading} value={seasonId} onChange={e=>void changeSeason(e.target.value)}>{data?.seasons.map(s=><option key={s.id} value={s.id}>{s.name}{s.isCurrent?" · AKTUELL":""}</option>)}</select></label></AdminCard>
  <div className="tm-tabs">{([['overview','Übersicht'],['roster','Roster'],['depth','Depth Chart'],['availability','Availability'],['planning','Planning'],['coaches','Coaches']] as [Tab,string][]).map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>changeTab(key)}>{label}</button>)}</div>
  <div className="tm-kpis"><Metric label="Roster" value={data?.summary.roster}/><Metric label="Game Ready" value={data?.summary.gameReady} suffix={data?` · ${data.summary.gameReadyPct}%`:""}/><Metric label="Limited" value={data?.summary.limited}/><Metric label="Out" value={data?.summary.out} risk/><Metric label="Starter" value={data?.summary.starters}/><Metric label="Captains" value={data?.summary.captains}/></div>
  {tab==="overview"&&data&&<><div className="tm-overview-grid"><AdminCard><div className="cms-section-head"><div><small>POSITION HEALTH</small><h2>Kaderstärke nach Positionsgruppe</h2></div></div><div className="tm-position-grid">{data.positionGroups.map(g=><article key={g.label}><div><b>{g.label}</b><small>{g.players} Spieler</small></div><span><b>{g.gameReady}</b><small>READY</small></span><span><b>{g.starters}</b><small>START</small></span><span className={g.limited?"warn":""}><b>{g.limited}</b><small>LIMITED</small></span></article>)}</div></AdminCard><AdminCard><div className="cms-section-head"><div><small>NEXT SEASON</small><h2>Roster Planning</h2></div></div><div className="tm-planning-summary"><span><b>{data.planning.returning}</b><small>RETURNING</small></span><span><b>{data.planning.unsure}</b><small>UNSURE</small></span><span><b>{data.planning.leaving}</b><small>LEAVING</small></span><span><b>{data.planning.unknown}</b><small>OPEN</small></span></div><button className="cms-button secondary" onClick={()=>changeTab("planning")}>Planning öffnen</button></AdminCard></div><AdminCard><div className="cms-section-head"><div><small>COMMAND VIEW</small><h2>Operational Alerts</h2></div></div><div className="tm-alerts"><Alert risk={Boolean(data.summary.out)} title={`${data.summary.out} Spieler nicht game-ready`} text="OUT, verletzt oder gesperrt – Availability vor dem nächsten Gameday prüfen."/><Alert risk={data.planning.unknown>0} title={`${data.planning.unknown} Spieler ohne Saisonplanung`} text="Returning / Unsure / Leaving frühzeitig pflegen, damit Recruiting Needs belastbar werden."/><Alert risk={data.summary.depthPositions===0} title={`${data.summary.depthPositions} Positionen im aktuellen Depth Chart`} text="Depth Chart Coverage beeinflusst Gameday-Roster und Roster Health."/></div></AdminCard></>}
  {tab==="roster"&&data&&<><AdminCard className="tm-filterbar"><input placeholder="Spieler, Position oder Nummer suchen…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="all">Alle Units</option><option value="offense">Offense</option><option value="defense">Defense</option><option value="special-teams">Special Teams</option></select><a className="cms-button secondary" href="/admin/roster">Erweiterte Roster-Pflege ↗</a></AdminCard><RosterTable players={filtered} saving={saving} onUpdate={updatePlayer}/></>}
  {tab==="availability"&&data&&<><AdminCard><div className="cms-section-head"><div><small>PLAYER AVAILABILITY</small><h2>Game Readiness</h2></div></div><p className="cms-muted">Availability kann hier direkt gepflegt werden. Medizinische Detailinformationen gehören nicht in diese Ansicht.</p></AdminCard><RosterTable players={filtered.slice().sort((a,b)=>availabilityRank(a.availability)-availabilityRank(b.availability))} saving={saving} onUpdate={updatePlayer} compact="availability"/></>}
  {tab==="planning"&&data&&<><AdminCard><div className="cms-section-head"><div><small>FUTURE ROSTER</small><h2>Saisonplanung</h2></div></div><p className="cms-muted">Status pro Spieler pflegen: Returning, Unsure oder Leaving. Offene Spieler bleiben bewusst sichtbar.</p></AdminCard><RosterTable players={filtered} saving={saving} onUpdate={updatePlayer} compact="planning"/></>}
  {tab==="depth"&&data&&<><AdminCard><div className="cms-section-head"><div><small>DEPTH CHART</small><h2>Aktueller Snapshot</h2></div><a className="cms-button secondary" href="/admin/depth-chart">Depth Chart bearbeiten ↗</a></div><div className="tm-depth-grid">{Object.entries(groupDepth(data.depth)).map(([position,entries])=><article key={position}><h3>{position}</h3>{entries.map(e=><div key={`${e.playerId}-${e.rank}`}><b>{e.rank}</b><span>#{e.jerseyNumber??"–"} {e.firstName} {e.lastName}</span></div>)}</article>)}{!data.depth.length&&<p className="cms-muted">Noch kein aktueller Depth Chart vorhanden.</p>}</div></AdminCard></>}
  {tab==="coaches"&&data&&<AdminCard><div className="cms-section-head"><div><small>COACHING STAFF</small><h2>{data.summary.coaches} aktive Coaches</h2></div><a className="cms-button secondary" href="/admin/coaches">Coaches bearbeiten ↗</a></div><div className="tm-coach-grid">{data.coaches.map(c=><article key={c.id} className={!c.active?"inactive":""}>{c.photo?<img src={c.photo} alt=""/>:<div className="tm-coach-avatar">{c.firstName[0]}{c.lastName[0]}</div>}<div><b>{c.firstName} {c.lastName}</b><small>{c.role||"Coach"}</small></div></article>)}</div></AdminCard>}
 </AdminShell>
}

function RosterTable({players,saving,onUpdate,compact}:{players:Player[];saving:string;onUpdate:(p:Player,patch:Partial<Player>)=>void;compact?:"availability"|"planning"}){return <AdminCard><div className="tm-table-wrap"><table className="tm-table"><thead><tr><th>Spieler</th><th>Pos</th>{compact!=="planning"&&<th>Roster</th>}{compact!=="planning"&&<th>Availability</th>}{compact!=="availability"&&<th>Planning</th>}<th>Starter</th><th>Captain</th></tr></thead><tbody>{players.map(p=><tr key={p.playerId}><td><b>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName}</b><small>{p.unit}</small></td><td>{p.primaryPosition}{p.secondaryPosition?` / ${p.secondaryPosition}`:""}</td>{compact!=="planning"&&<td><select disabled={saving===p.playerId} value={p.rosterStatus} onChange={e=>void onUpdate(p,{rosterStatus:e.target.value})}>{rosterOptions.map(o=><option key={o} value={o}>{o}</option>)}</select></td>}{compact!=="planning"&&<td><select disabled={saving===p.playerId} value={p.availability} onChange={e=>void onUpdate(p,{availability:e.target.value})}>{availabilityOptions.map(o=><option key={o} value={o}>{o}</option>)}</select></td>}{compact!=="availability"&&<td><select disabled={saving===p.playerId} value={p.planningStatus} onChange={e=>void onUpdate(p,{planningStatus:e.target.value})}>{planningOptions.map(o=><option key={o} value={o}>{o}</option>)}</select></td>}<td><input type="checkbox" checked={p.starter} disabled={saving===p.playerId} onChange={e=>void onUpdate(p,{starter:e.target.checked})}/></td><td><input type="checkbox" checked={p.captain} disabled={saving===p.playerId} onChange={e=>void onUpdate(p,{captain:e.target.checked})}/></td></tr>)}</tbody></table></div></AdminCard>}
function Metric({label,value,suffix="",risk=false}:{label:string;value:number|undefined;suffix?:string;risk?:boolean}){return <div className={`tm-metric${risk?" risk":""}`}><small>{label}</small><b>{value??"–"}{suffix}</b></div>}
function Alert({risk,title,text}:{risk:boolean;title:string;text:string}){return <article className={risk?"risk":"ok"}><span>{risk?"!":"✓"}</span><div><b>{title}</b><p>{text}</p></div></article>}
function groupDepth(items:Depth[]){const out:Record<string,Depth[]>={};for(const item of items){if(!out[item.position])out[item.position]=[];out[item.position].push(item)}return out}
function availabilityRank(value:string){return value==="out"?0:value==="return-to-play"?1:value==="questionable"?2:value==="limited"?3:4}
