"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminNotice, AdminShell } from "../_components/AdminShell";
import "./development.css";

type Player={id:string;firstName:string;lastName:string;jerseyNumber:number|null;position:string;unit:string};
type Skill={key:string;label:string;category:string;current:number;target:number;priority:number;note:string;needScore:number;updatedAt?:string;updatedBy?:string};
type TeamNeed={key:string;label:string;category:string;current:number;target:number;priority:number;count:number;needScore:number};
type UnitNeed=TeamNeed&{unit:string};
type PlanBlock={key:string;label:string;category:string;needScore:number;minutes:number;drill:string;goal:string};

const drillIdeas:Record<string,{drill:string;goal:string}>={
 tackling:{drill:"Angle Tackling + Form Tackle Circuit",goal:"Pad Level, Head Placement, Finish und sichere Tackles unter Tempo"},
 movement:{drill:"Footwork & Change-of-Direction Circuit",goal:"Saubere Steps, Hüftbeweglichkeit und kontrollierte Richtungswechsel"},
 play_recognition:{drill:"Read & React / Key Recognition",goal:"Keys schneller erkennen und Entscheidungen früher treffen"},
 assignment:{drill:"Assignment Walkthrough → Tempo Reps",goal:"Verantwortung pro Call sicher erkennen und fehlerfrei ausführen"},
 pursuit:{drill:"Pursuit Angle Team Drill",goal:"Inside-out leverage, richtige Winkel und Rally to the Ball"},
 coverage:{drill:"Coverage Drops + Route Match",goal:"Spacing, Augenarbeit, Übergaben und Break on Ball verbessern"},
 block_shedding:{drill:"Strike-Separate-Escape",goal:"Hands, Extension und schneller Release vom Block"},
 route_running:{drill:"Route Stem & Breakpoint Circuit",goal:"Stem, Cuts, Separation und Timing stabilisieren"},
 blocking:{drill:"Fit & Finish Blocking",goal:"Leverage, Hand Placement und Drive verbessern"},
 ball_security:{drill:"Ball Security Gauntlet",goal:"5 Points of Pressure und Ballkontrolle unter Kontakt"},
 communication:{drill:"Pre-Snap Communication Period",goal:"Calls eindeutig, früh und positionsübergreifend kommunizieren"},
 technique:{drill:"Position Fundamentals Circuit",goal:"Grundtechnik unter steigender Geschwindigkeit sauber halten"},
 speed_agility:{drill:"Acceleration + COD",goal:"Explosiver erster Schritt und effizientere Richtungswechsel"},
 strength:{drill:"Contact & Power Period",goal:"Football-spezifische Kraftübertragung und Physicality"},
 conditioning:{drill:"Football Conditioning Intervals",goal:"Leistung über wiederholte intensive Reps stabil halten"},
 discipline:{drill:"Situational Discipline Period",goal:"Assignments, Cadence, Penalties und Entscheidungsqualität verbessern"},
};

export function DevelopmentManager(){
 const[mode,setMode]=useState<"player"|"team"|"planner">("player");const[players,setPlayers]=useState<Player[]>([]);const[playerId,setPlayerId]=useState("");const[skills,setSkills]=useState<Skill[]>([]);const[teamNeeds,setTeamNeeds]=useState<TeamNeed[]>([]);const[unitNeeds,setUnitNeeds]=useState<UnitNeed[]>([]);const[notice,setNotice]=useState("");const[saving,setSaving]=useState("");const[unit,setUnit]=useState("all");
 const[sessionMinutes,setSessionMinutes]=useState(120);const[focusCount,setFocusCount]=useState(3);
 const player=useMemo(()=>players.find(p=>p.id===playerId)??null,[players,playerId]);
 useEffect(()=>{void loadTeam()},[]);useEffect(()=>{if(playerId)void loadPlayer(playerId)},[playerId]);
 async function loadTeam(){const r=await fetch("/admin/api/development");if(!r.ok)return setNotice("Development-Daten konnten nicht geladen werden.");const b=await r.json() as {players:Player[];teamNeeds:TeamNeed[];unitNeeds:UnitNeed[]};setPlayers(b.players);setTeamNeeds(b.teamNeeds);setUnitNeeds(b.unitNeeds);setPlayerId(x=>x||b.players[0]?.id||"")}
 async function loadPlayer(id:string){const r=await fetch(`/admin/api/development?playerId=${encodeURIComponent(id)}`);if(!r.ok)return setNotice("Spielerentwicklung konnte nicht geladen werden.");const b=await r.json() as {skills:Skill[]};setSkills(b.skills)}
 function patch(key:string,field:keyof Skill,value:string|number){setSkills(s=>s.map(x=>x.key===key?{...x,[field]:value}:x))}
 async function saveSkill(skill:Skill){if(!playerId)return;setSaving(skill.key);setNotice("");try{const r=await fetch("/admin/api/development",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({playerId,skillKey:skill.key,current:skill.current,target:skill.target,priority:skill.priority,note:skill.note})});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Speichern fehlgeschlagen.")}setNotice(`${skill.label} gespeichert.`);await Promise.all([loadPlayer(playerId),loadTeam()])}catch(e){setNotice(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setSaving("")}}
 const shownNeeds=unit==="all"?teamNeeds:unitNeeds.filter(x=>x.unit===unit);
 const plan=useMemo(()=>buildTrainingPlan(shownNeeds,sessionMinutes,focusCount),[shownNeeds,sessionMinutes,focusCount]);
 const avgNeed=useMemo(()=>{const rated=shownNeeds.filter(x=>x.count>0);return rated.length?Math.round(rated.reduce((s,x)=>s+x.needScore,0)/rated.length):0},[shownNeeds]);
 return <AdminShell active="development" title="Player Development" eyebrow="RASCALS OS · FOOTBALL INTELLIGENCE">
  {notice&&<AdminNotice tone={notice.includes("gespeichert")?"success":"error"}>{notice}</AdminNotice>}
  <div className="dev-tabs"><button className={mode==="player"?"active":""} onClick={()=>setMode("player")}>Spielerentwicklung</button><button className={mode==="team"?"active":""} onClick={()=>setMode("team")}>Team Training Needs</button><button className={mode==="planner"?"active":""} onClick={()=>setMode("planner")}>Training Planner</button></div>
  {mode==="player"&&<>
   <AdminCard><div className="dev-head"><div><small>PLAYER DEVELOPMENT</small><h2>Stärken, Schwächen & Trainingsfelder</h2><p>Der Coach bewertet Ist-Zustand, Zielniveau und Priorität. Aus der Lücke berechnet RASCALS OS automatisch den Trainingsbedarf.</p></div><label className="cms-field"><span>Spieler</span><select value={playerId} onChange={e=>setPlayerId(e.target.value)}>{players.map(p=><option key={p.id} value={p.id}>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName} · {p.position}</option>)}</select></label></div></AdminCard>
   {player&&<div className="dev-skill-grid">{skills.map(skill=><AdminCard key={skill.key} className="dev-skill-card"><div className="dev-skill-title"><div><small>{skill.category}</small><h3>{skill.label}</h3></div><strong className={skill.needScore>=60?"hot":skill.needScore>=30?"mid":"low"}>{skill.needScore}</strong></div><div className="dev-ratings"><label>IST<select value={skill.current} onChange={e=>patch(skill.key,"current",Number(e.target.value))}>{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select></label><span>→</span><label>ZIEL<select value={skill.target} onChange={e=>patch(skill.key,"target",Number(e.target.value))}>{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select></label><label>PRIO<select value={skill.priority} onChange={e=>patch(skill.key,"priority",Number(e.target.value))}><option value={1}>1 · Normal</option><option value={2}>2 · Wichtig</option><option value={3}>3 · Fokus</option></select></label></div><div className="dev-gap"><span style={{width:`${Math.min(100,skill.needScore)}%`}}/></div><label className="cms-field"><span>Coach-Notiz / Trainingsziel</span><textarea rows={3} value={skill.note} onChange={e=>patch(skill.key,"note",e.target.value)} placeholder="z. B. Kopf oben halten, Hüfte tiefer, schnelleres Read-Step..."/></label><button className="cms-button" disabled={saving===skill.key} onClick={()=>void saveSkill(skill)}>{saving===skill.key?"Speichert…":"Skill speichern"}</button></AdminCard>)}</div>}
  </>}
  {mode==="team"&&<>
   <AdminCard><div className="dev-head"><div><small>TEAM INTELLIGENCE</small><h2>Wo müssen wir als Team trainieren?</h2><p>Die aggregierte Auswertung zeigt automatisch die größten gemeinsamen Entwicklungsfelder über alle bewerteten Spieler.</p></div><label className="cms-field"><span>Gruppe</span><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="all">Gesamtes Team</option><option value="offense">Offense</option><option value="defense">Defense</option><option value="special-teams">Special Teams</option></select></label></div></AdminCard>
   <div className="dev-team-layout"><AdminCard><div className="cms-section-head"><div><small>TRAINING PRIORITIES</small><h2>Top Entwicklungsfelder</h2></div></div><div className="dev-needs">{shownNeeds.filter(x=>x.count>0).slice(0,10).map((x,i)=><article key={`${x.unit??"team"}-${x.key}`}><b>{i+1}</b><div><strong>{x.label}</strong><span>{x.category} · {x.count} Spieler bewertet</span></div><div className="dev-need-score"><strong>{x.needScore}</strong><small>NEED</small></div><div className="dev-need-bar"><span style={{width:`${x.needScore}%`}}/></div></article>)}</div></AdminCard><AdminCard><div className="cms-section-head"><div><small>COACH DECISION SUPPORT</small><h2>Trainingsfokus</h2></div></div>{shownNeeds.filter(x=>x.count>0).slice(0,5).map(x=><div className="dev-focus" key={`focus-${x.unit??"team"}-${x.key}`}><b>{x.label}</b><p>Ø Ist {x.current.toFixed(1)} / Ziel {x.target.toFixed(1)} · Priorität {x.priority.toFixed(1)}</p><strong>{x.needScore>=60?"Hoher Trainingsbedarf":x.needScore>=30?"Gezielt verbessern":"Stabil halten"}</strong></div>)}{!shownNeeds.some(x=>x.count>0)&&<p className="cms-muted">Noch keine Skill-Bewertungen vorhanden. Sobald Coaches Spieler bewerten, entstehen hier automatisch Team-Trainingsprioritäten.</p>}</AdminCard></div>
  </>}
  {mode==="planner"&&<>
   <AdminCard><div className="dev-head"><div><small>TRAINING PLANNING INTELLIGENCE</small><h2>Aus Daten wird ein Trainingsplan</h2><p>RASCALS OS verteilt die verfügbare Trainingszeit automatisch auf die größten gemeinsamen Schwächen. Die Empfehlung ist Entscheidungshilfe – der Coaching Staff behält die Kontrolle.</p></div><div className="dev-plan-controls"><label className="cms-field"><span>Gruppe</span><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="all">Gesamtes Team</option><option value="offense">Offense</option><option value="defense">Defense</option><option value="special-teams">Special Teams</option></select></label><label className="cms-field"><span>Trainingsdauer</span><select value={sessionMinutes} onChange={e=>setSessionMinutes(Number(e.target.value))}><option value={60}>60 Minuten</option><option value={90}>90 Minuten</option><option value={120}>120 Minuten</option><option value={150}>150 Minuten</option><option value={180}>180 Minuten</option></select></label><label className="cms-field"><span>Fokusfelder</span><select value={focusCount} onChange={e=>setFocusCount(Number(e.target.value))}>{[2,3,4,5].map(v=><option key={v} value={v}>{v}</option>)}</select></label></div></div></AdminCard>
   <div className="dev-plan-kpis"><div><small>TEAM NEED INDEX</small><strong>{avgNeed}</strong><span>/100</span></div><div><small>FOCUS TIME</small><strong>{Math.round(sessionMinutes*.7)}</strong><span>MIN</span></div><div><small>TOP PRIORITÄT</small><strong className="dev-kpi-label">{plan.blocks[0]?.label??"–"}</strong></div><div><small>BEWERTETE FELDER</small><strong>{shownNeeds.filter(x=>x.count>0).length}</strong></div></div>
   <div className="dev-plan-layout"><AdminCard><div className="cms-section-head"><div><small>SESSION BLUEPRINT</small><h2>{sessionMinutes} Minuten Training</h2></div><span className="cms-muted">70 % datenbasierter Fokus</span></div><div className="dev-session-timeline"><article className="base"><b>{plan.warmup}</b><div><strong>Warm-up & Movement Prep</strong><span>Aktivierung, Mobilität, Position Footwork</span></div></article>{plan.blocks.map((block,i)=><article key={block.key} className={block.needScore>=60?"hot":block.needScore>=30?"mid":""}><b>{block.minutes}</b><div><small>FOCUS {i+1} · NEED {block.needScore}</small><strong>{block.label}</strong><span>{block.drill}</span><p>{block.goal}</p></div></article>)}<article className="base"><b>{plan.team}</b><div><strong>Team / Situational Finish</strong><span>Install, Situations, Competition und kontrollierter Abschluss</span></div></article></div></AdminCard>
    <AdminCard><div className="cms-section-head"><div><small>COACH BRIEF</small><h2>Warum diese Schwerpunkte?</h2></div></div>{plan.blocks.map(block=><div className="dev-focus" key={`plan-${block.key}`}><b>{block.label}</b><p>Need Score {block.needScore} · {block.category}</p><strong>{block.minutes} Minuten empfohlen</strong></div>)}{!plan.blocks.length&&<p className="cms-muted">Noch nicht genug Bewertungen für einen Trainingsvorschlag vorhanden.</p>}<div className="dev-plan-rule"><b>Planungslogik</b><p>15 % Warm-up · 70 % Entwicklungsfelder nach Need Score gewichtet · 15 % Team/Situational. Die Zeitverteilung aktualisiert sich automatisch mit den Coach-Bewertungen.</p></div></AdminCard></div>
  </>}
 </AdminShell>
}
function buildTrainingPlan(needs:(TeamNeed|UnitNeed)[],minutes:number,count:number){const rated=needs.filter(x=>x.count>0&&x.needScore>0).slice(0,count);const warmup=Math.max(5,Math.round(minutes*.15));const team=Math.max(5,Math.round(minutes*.15));const focusTotal=Math.max(0,minutes-warmup-team);const scoreTotal=rated.reduce((s,x)=>s+Math.max(1,x.needScore),0);let assigned=0;const blocks:PlanBlock[]=rated.map((x,i)=>{const mins=i===rated.length-1?Math.max(5,focusTotal-assigned):Math.max(5,Math.round(focusTotal*Math.max(1,x.needScore)/Math.max(1,scoreTotal)));assigned+=mins;const idea=drillIdeas[x.key]??{drill:`${x.label} Position Period`,goal:`Gezielte Wiederholungen für ${x.label} mit messbarem Coaching-Fokus`};return{key:x.key,label:x.label,category:x.category,needScore:x.needScore,minutes:mins,drill:idea.drill,goal:idea.goal}});return{warmup,team,blocks}}
