import { bindings } from "../../../lib/cms";
import { ensurePlaybookFoundationSchema, normalizePlaybookUnit } from "../../../lib/playbook-foundation";
import { requireCmsPermission } from "../../../lib/permissions";

type Row = Record<string, unknown>;
type SlotInput = { id?: string; slotKey: string; positionLabel: string; positionGroup?: string; roleLabel?: string; x?: number; y?: number; eligiblePositions?: string; sortOrder?: number };
type Body = { action?: "create-formation" | "update-formation" | "duplicate-formation" | "archive-formation" | "save-slots" | "create-play"; seasonId?: string; unit?: string; formationId?: string | null; name?: string; personnel?: string; family?: string; strengthRule?: string; description?: string; tags?: string; concept?: string; playType?: string; slots?: SlotInput[] };
function clampCoord(value: unknown, fallback = 50) { const n = Number(value); return Number.isFinite(n) ? Math.max(0, Math.min(100, n)) : fallback; }
function mapFormation(r: Row, slots: Row[] = []) { return { id:String(r.id),seasonId:String(r.season_id),unit:String(r.unit),name:String(r.name??""),personnel:String(r.personnel??""),family:String(r.family??""),strengthRule:String(r.strength_rule??""),description:String(r.description??""),tags:String(r.tags??""),active:Number(r.active??1)===1,updatedAt:String(r.updated_at??""),slots:slots.map(s=>({id:String(s.id),formationId:String(s.formation_id),slotKey:String(s.slot_key),positionLabel:String(s.position_label??""),positionGroup:String(s.position_group??""),roleLabel:String(s.role_label??""),x:Number(s.x??50),y:Number(s.y??50),eligiblePositions:String(s.eligible_positions??""),sortOrder:Number(s.sort_order??0)})) }; }
export async function GET(request: Request) {
 const actor=await requireCmsPermission("performance"); if(actor instanceof Response)return actor; await ensurePlaybookFoundationSchema(); const{DB}=bindings(); const url=new URL(request.url); const unit=normalizePlaybookUnit(url.searchParams.get("unit")); const seasonId=url.searchParams.get("seasonId")??""; const formationId=url.searchParams.get("formationId")??"";
 const formations=seasonId?await DB.prepare(`SELECT id,season_id,unit,name,personnel,family,strength_rule,description,tags,active,updated_at FROM playbook_formations WHERE season_id=? AND unit=? AND active=1 ORDER BY family,name`).bind(seasonId,unit).all<Row>():{results:[] as Row[]};
 const formationIds=formations.results.map(r=>String(r.id)); let slotRows:Row[]=[]; if(formationIds.length){const placeholders=formationIds.map(()=>"?").join(",");slotRows=(await DB.prepare(`SELECT * FROM playbook_formation_slots WHERE formation_id IN (${placeholders}) ORDER BY formation_id,sort_order,slot_key`).bind(...formationIds).all<Row>()).results} const slotsByFormation=new Map<string,Row[]>(); for(const row of slotRows){const key=String(row.formation_id);const list=slotsByFormation.get(key)??[];list.push(row);slotsByFormation.set(key,list)}
 const plays=seasonId?await DB.prepare(`SELECT p.id,p.season_id,p.formation_id,p.unit,p.name,p.call_name,p.concept,p.play_type,p.personnel,p.situation,p.down_distance,p.field_zone,p.hash,p.strength_call,p.front_call,p.coverage_call,p.checks_alerts,p.objective,p.coaching_points,p.tags,p.status,p.version,p.updated_at,f.name formation_name FROM playbook_plays p LEFT JOIN playbook_formations f ON f.id=p.formation_id WHERE p.season_id=? AND p.unit=? AND p.status!='archived' ORDER BY p.updated_at DESC,p.name`).bind(seasonId,unit).all<Row>():{results:[] as Row[]}; const selectedFormation=formationId?formations.results.find(r=>String(r.id)===formationId)??null:null;
 return Response.json({current:actor,seasonId,unit,formations:formations.results.map(r=>mapFormation(r,slotsByFormation.get(String(r.id))??[])),selectedFormation:selectedFormation?mapFormation(selectedFormation,slotsByFormation.get(formationId)??[]):null,plays:plays.results.map(r=>({id:String(r.id),seasonId:String(r.season_id),formationId:r.formation_id?String(r.formation_id):null,formationName:String(r.formation_name??""),unit:String(r.unit),name:String(r.name??""),callName:String(r.call_name??""),concept:String(r.concept??""),playType:String(r.play_type??""),personnel:String(r.personnel??""),situation:String(r.situation??""),downDistance:String(r.down_distance??""),fieldZone:String(r.field_zone??""),hash:String(r.hash??""),strengthCall:String(r.strength_call??""),frontCall:String(r.front_call??""),coverageCall:String(r.coverage_call??""),checksAlerts:String(r.checks_alerts??""),objective:String(r.objective??""),coachingPoints:String(r.coaching_points??""),tags:String(r.tags??""),status:String(r.status??"draft"),version:Number(r.version??1),updatedAt:String(r.updated_at??"")}))});
}
export async function POST(request: Request) {
 const actor=await requireCmsPermission("performance");if(actor instanceof Response)return actor;await ensurePlaybookFoundationSchema();const body=await request.json() as Body;const{DB}=bindings();const unit=normalizePlaybookUnit(body.unit);
 if(body.action==="create-formation"){if(!body.seasonId||!body.name?.trim())return Response.json({error:"Saison und Formationsname sind erforderlich."},{status:400});const duplicate=await DB.prepare("SELECT id FROM playbook_formations WHERE season_id=? AND unit=? AND lower(name)=lower(?) AND active=1 LIMIT 1").bind(body.seasonId,unit,body.name.trim()).first();if(duplicate)return Response.json({error:"Eine aktive Formation mit diesem Namen existiert bereits."},{status:409});const id=crypto.randomUUID();await DB.prepare(`INSERT INTO playbook_formations (id,season_id,unit,name,personnel,family,strength_rule,description,tags,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(id,body.seasonId,unit,body.name.trim(),body.personnel?.trim()??"",body.family?.trim()??"",body.strengthRule?.trim()??"",body.description?.trim()??"",body.tags?.trim()??"",actor.email,actor.email).run();return Response.json({ok:true,id},{status:201})}
 if(body.action==="update-formation"){if(!body.formationId||!body.name?.trim())return Response.json({error:"Formation und Name sind erforderlich."},{status:400});const existing=await DB.prepare("SELECT id,season_id,unit FROM playbook_formations WHERE id=? AND active=1 LIMIT 1").bind(body.formationId).first<Row>();if(!existing)return Response.json({error:"Formation wurde nicht gefunden."},{status:404});const duplicate=await DB.prepare("SELECT id FROM playbook_formations WHERE season_id=? AND unit=? AND lower(name)=lower(?) AND id<>? AND active=1 LIMIT 1").bind(String(existing.season_id),String(existing.unit),body.name.trim(),body.formationId).first();if(duplicate)return Response.json({error:"Eine andere aktive Formation mit diesem Namen existiert bereits."},{status:409});await DB.prepare(`UPDATE playbook_formations SET name=?,personnel=?,family=?,strength_rule=?,description=?,tags=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(body.name.trim(),body.personnel?.trim()??"",body.family?.trim()??"",body.strengthRule?.trim()??"",body.description?.trim()??"",body.tags?.trim()??"",actor.email,body.formationId).run();return Response.json({ok:true,id:body.formationId})}
 if(body.action==="save-slots"){if(!body.formationId)return Response.json({error:"Formation ist erforderlich."},{status:400});const formation=await DB.prepare("SELECT id FROM playbook_formations WHERE id=? AND active=1 LIMIT 1").bind(body.formationId).first();if(!formation)return Response.json({error:"Formation wurde nicht gefunden."},{status:404});const slots=body.slots??[];const keys=new Set<string>();for(const slot of slots){const key=slot.slotKey?.trim();if(!key||!slot.positionLabel?.trim())return Response.json({error:"Jeder Slot benötigt Slot-Key und Positionsbezeichnung."},{status:400});if(keys.has(key.toLowerCase()))return Response.json({error:`Slot-Key doppelt vergeben: ${key}`},{status:409});keys.add(key.toLowerCase())}const statements=[DB.prepare("DELETE FROM playbook_formation_slots WHERE formation_id=?").bind(body.formationId)];for(let index=0;index<slots.length;index++){const slot=slots[index];statements.push(DB.prepare(`INSERT INTO playbook_formation_slots (id,formation_id,slot_key,position_label,position_group,role_label,x,y,eligible_positions,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(slot.id||crypto.randomUUID(),body.formationId,slot.slotKey.trim(),slot.positionLabel.trim(),slot.positionGroup?.trim()??"",slot.roleLabel?.trim()??"",clampCoord(slot.x),clampCoord(slot.y),slot.eligiblePositions?.trim()??"",Number.isFinite(Number(slot.sortOrder))?Number(slot.sortOrder):index))}statements.push(DB.prepare("UPDATE playbook_formations SET updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(actor.email,body.formationId));await DB.batch(statements);return Response.json({ok:true,formationId:body.formationId,slotCount:slots.length})}
 if(body.action==="duplicate-formation"){if(!body.formationId)return Response.json({error:"Formation ist erforderlich."},{status:400});const source=await DB.prepare("SELECT * FROM playbook_formations WHERE id=? AND active=1 LIMIT 1").bind(body.formationId).first<Row>();if(!source)return Response.json({error:"Formation wurde nicht gefunden."},{status:404});const slots=await DB.prepare("SELECT * FROM playbook_formation_slots WHERE formation_id=? ORDER BY sort_order,slot_key").bind(body.formationId).all<Row>();const id=crypto.randomUUID();let newName=`${String(source.name)} Copy`;let suffix=2;while(await DB.prepare("SELECT id FROM playbook_formations WHERE season_id=? AND unit=? AND lower(name)=lower(?) AND active=1 LIMIT 1").bind(String(source.season_id),String(source.unit),newName).first())newName=`${String(source.name)} Copy ${suffix++}`;const statements=[DB.prepare(`INSERT INTO playbook_formations (id,season_id,unit,name,personnel,family,strength_rule,description,tags,active,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,1,?,?)`).bind(id,String(source.season_id),String(source.unit),newName,String(source.personnel??""),String(source.family??""),String(source.strength_rule??""),String(source.description??""),String(source.tags??""),actor.email,actor.email)];for(const slot of slots.results)statements.push(DB.prepare(`INSERT INTO playbook_formation_slots (id,formation_id,slot_key,position_label,position_group,role_label,x,y,eligible_positions,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),id,String(slot.slot_key),String(slot.position_label??""),String(slot.position_group??""),String(slot.role_label??""),Number(slot.x??50),Number(slot.y??50),String(slot.eligible_positions??""),Number(slot.sort_order??0)));await DB.batch(statements);return Response.json({ok:true,id,name:newName},{status:201})}
 if(body.action==="archive-formation"){if(!body.formationId)return Response.json({error:"Formation ist erforderlich."},{status:400});const playCount=await DB.prepare("SELECT COUNT(*) AS total FROM playbook_plays WHERE formation_id=? AND status!='archived'").bind(body.formationId).first<{total:number}>();await DB.prepare("UPDATE playbook_formations SET active=0,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(actor.email,body.formationId).run();return Response.json({ok:true,id:body.formationId,linkedActivePlays:Number(playCount?.total??0)})}
 if(body.action==="create-play"){if(!body.seasonId||!body.name?.trim())return Response.json({error:"Saison und Playname sind erforderlich."},{status:400});if(body.formationId){const formation=await DB.prepare("SELECT id,season_id,unit,personnel FROM playbook_formations WHERE id=? AND active=1 LIMIT 1").bind(body.formationId).first<Row>();if(!formation||String(formation.season_id)!==body.seasonId||String(formation.unit)!==unit)return Response.json({error:"Formation gehört nicht zu Saison und Unit des Plays."},{status:409})}const id=crypto.randomUUID();await DB.prepare(`INSERT INTO playbook_plays (id,season_id,formation_id,unit,name,concept,play_type,personnel,status,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?, 'draft',?,?)`).bind(id,body.seasonId,body.formationId??null,unit,body.name.trim(),body.concept?.trim()??"",body.playType?.trim()??"",body.personnel?.trim()??"",actor.email,actor.email).run();return Response.json({ok:true,id},{status:201})}
 return Response.json({error:"Unbekannte Aktion."},{status:400});
}
