"use client";

import { useState, type CSSProperties } from "react";
import { DynamicHomeFeeds } from "./DynamicHomeFeeds";
import { DynamicHomeGames } from "./DynamicHomeGames";
import type { BuilderElementStyle, BuilderItem, BuilderPage, BuilderSection, SiteBuilderState } from "./lib/site-builder";
import "./site-builder.css";
import "./builder-typography.css";
import "./builder-element-styles.css";

const footballIcon="https://api.iconify.design/noto/american-football.svg";
const legacySlugs=new Set(["ueber-uns","team","sponsoring","shop","news","galerie"]);
type VarStyle=CSSProperties&Record<string,string|number|undefined>;

/* Section colours are stored as data, so published pages still carry brand
   reds that were retired when the palette was unified. Mapping them at render
   time keeps the live site consistent without rewriting saved CMS content,
   and anything an editor picks from now on passes through untouched. */
const RETIRED_REDS=new Set(["#dc1726","#e72835","#d82b1d","#e02b21","#ef2d3d","#e7192d"]);
function brandColor(value?:string){return value&&RETIRED_REDS.has(value.trim().toLowerCase())?"var(--rascals-red)":value}

/* The CMS stores a font stack but cannot load a font, so a value like
   "Inter, Arial, sans-serif" silently renders as Arial. Insert the
   self-hosted design face directly after the editor's first choice: that
   choice still wins if it is ever actually loaded, and everything else
   falls to a real font instead of a system default. */
function withDesignFont(stack:string|undefined,fallbackVar:string){
  const parts=(stack??"").split(",").map(part=>part.trim()).filter(Boolean);
  if(!parts.length)return `var(${fallbackVar})`;
  return [parts[0],`var(${fallbackVar})`,...parts.slice(1)].join(", ");
}

function variant(section:BuilderSection){return`sb-variant-${(section.variant||"default").replace(/[^a-z0-9-]/gi,"-").toLowerCase()}`}
function bgMode(section:BuilderSection){return`sb-bgmode-${section.style.backgroundMode||"color"}`}
function shell(section:BuilderSection,extra=""){return`sb-section ${extra} ${variant(section)} ${bgMode(section)}`.trim()}
function sizeVars(scale:number,suffix:string):VarStyle{return{[`--sb-h1-min${suffix}`]:`${3.5*scale}rem`,[`--sb-h1-fluid${suffix}`]:`${7*scale}vw`,[`--sb-h1-max${suffix}`]:`${8*scale}rem`,[`--sb-h2-min${suffix}`]:`${2.4*scale}rem`,[`--sb-h2-fluid${suffix}`]:`${4.6*scale}vw`,[`--sb-h2-max${suffix}`]:`${5.4*scale}rem`}}
function sectionStyle(section:BuilderSection):CSSProperties{const t=section.style.tablet||{},m=section.style.mobile||{},mode=section.style.backgroundMode||"color",ds=section.style.headingScale??1,ts=t.headingScale??ds*.9,ms=m.headingScale??ds*.72,bg=mode==="gradient"?(section.style.backgroundGradient||brandColor(section.style.background)||"#050d18"):(brandColor(section.style.background)||"#050d18");const value:VarStyle={"--sb-bg":brandColor(section.style.background)||"#050d18","--sb-background":bg,"--sb-text":section.style.textColor||"#fff","--sb-accent":brandColor(section.style.accentColor)||"var(--rascals-red)","--sb-pt":`${section.style.paddingTop??64}px`,"--sb-pb":`${section.style.paddingBottom??64}px`,"--sb-min":`${section.style.minHeight??0}px`,"--sb-max":`${section.style.maxWidth??1600}px`,"--sb-radius":`${section.style.rounded??0}px`,"--sb-border":section.style.border||"transparent","--sb-pt-tablet":`${t.paddingTop??section.style.paddingTop??64}px`,"--sb-pb-tablet":`${t.paddingBottom??section.style.paddingBottom??64}px`,"--sb-min-tablet":`${t.minHeight??section.style.minHeight??0}px`,"--sb-max-tablet":`${t.maxWidth??section.style.maxWidth??1200}px`,"--sb-align-tablet":t.align||section.style.align||"left","--sb-pt-mobile":`${m.paddingTop??40}px`,"--sb-pb-mobile":`${m.paddingBottom??40}px`,"--sb-min-mobile":`${m.minHeight??0}px`,"--sb-max-mobile":`${m.maxWidth??720}px`,"--sb-align-mobile":m.align||section.style.align||"left","--sb-overlay":section.style.overlayColor||"#020812","--sb-overlay-opacity":String(section.style.overlayOpacity??.45),"--sb-bg-position":section.style.backgroundPosition||"center",...sizeVars(ds,""),...sizeVars(ts,"-tablet"),...sizeVars(ms,"-mobile"),textAlign:section.style.align||"left",background:bg,backgroundAttachment:section.style.backgroundFixed?"fixed":"scroll",borderWidth:section.style.borderWidth??(section.style.border?1:0),borderStyle:section.style.borderStyle||"solid",borderColor:section.style.border||"transparent",boxShadow:section.style.boxShadow||undefined,opacity:section.style.opacity??1};return value as CSSProperties}
function elementStyle(style?:BuilderElementStyle):CSSProperties{if(!style)return{};const t=style.tablet||{},m=style.mobile||{};const value:VarStyle={color:brandColor(style.color)||undefined,background:brandColor(style.background)||undefined,fontFamily:style.fontFamily||undefined,fontSize:style.fontSize==null?undefined:`${style.fontSize}px`,fontWeight:style.fontWeight,fontStyle:style.italic?"italic":undefined,letterSpacing:style.letterSpacing==null?undefined:`${style.letterSpacing}em`,lineHeight:style.lineHeight,textTransform:style.textTransform&&style.textTransform!=="none"?style.textTransform:undefined,textAlign:style.align,borderColor:brandColor(style.borderColor)||undefined,borderWidth:style.borderWidth,borderStyle:style.borderWidth?"solid":undefined,borderRadius:style.borderRadius,padding:style.paddingX!=null||style.paddingY!=null?`${style.paddingY??0}px ${style.paddingX??0}px`:undefined,opacity:style.opacity,objectPosition:style.objectPositionX!=null||style.objectPositionY!=null?`${style.objectPositionX??50}% ${style.objectPositionY??50}%`:undefined,transform:style.scale!=null&&style.scale!==1?`scale(${style.scale})`:undefined,boxShadow:style.boxShadow||undefined,"--be-font-size-tablet":t.fontSize==null?undefined:`${t.fontSize}px`,"--be-line-height-tablet":t.lineHeight,"--be-letter-spacing-tablet":t.letterSpacing==null?undefined:`${t.letterSpacing}em`,"--be-align-tablet":t.align,"--be-px-tablet":t.paddingX==null?undefined:`${t.paddingX}px`,"--be-py-tablet":t.paddingY==null?undefined:`${t.paddingY}px`,"--be-font-size-mobile":m.fontSize==null?undefined:`${m.fontSize}px`,"--be-line-height-mobile":m.lineHeight,"--be-letter-spacing-mobile":m.letterSpacing==null?undefined:`${m.letterSpacing}em`,"--be-align-mobile":m.align,"--be-px-mobile":m.paddingX==null?undefined:`${m.paddingX}px`,"--be-py-mobile":m.paddingY==null?undefined:`${m.paddingY}px`};return value as CSSProperties}
const ss=(section:BuilderSection,key:string)=>elementStyle(section.elementStyles?.[key]);
const is=(item:BuilderItem,key:string)=>elementStyle(item.elementStyles?.[key]);
function Background({section}:{section:BuilderSection}){const mode=section.style.backgroundMode||"color";if(mode==="image"&&section.style.backgroundImage)return<><img className="sb-bg-media" src={section.style.backgroundImage} alt=""/><span className="sb-bg-overlay"/></>;if(mode==="video"&&section.style.backgroundVideo)return<><video className="sb-bg-media" src={section.style.backgroundVideo} autoPlay muted loop playsInline/><span className="sb-bg-overlay"/></>;return null}
function Button({section}:{section:BuilderSection}){if(!section.buttonLabel||!section.buttonUrl)return null;return<a className="sb-button" href={section.buttonUrl} data-builder-element="button" style={ss(section,"button")}>{section.buttonLabel}<span>→</span></a>}
function Head({section}:{section:BuilderSection}){return<div className="sb-section-head">{section.eyebrow&&<span className="sb-kicker" data-builder-element="eyebrow" style={ss(section,"eyebrow")} data-reveal>{section.eyebrow}</span>}{section.title&&<h2 data-reveal data-reveal-delay="80"><span data-builder-element="title" style={ss(section,"title")}>{section.title}</span></h2>}{section.text&&<p data-builder-element="text" style={ss(section,"text")} data-reveal data-reveal-delay="160">{section.text}</p>}</div>}
function timelineLabel(value?:string){const[tag="",...rest]=(value||"").split(" · ");return{tag,league:rest.join(" · ")}}

export function BuilderSectionView({section}:{section:BuilderSection}){if(!section.visible)return null;const style=sectionStyle(section),data={"data-builder-section":section.id};
  if(section.type==="spacer")return<div {...data} className={`sb-spacer ${variant(section)}`} style={{height:section.style.minHeight||60,background:section.style.background}}/>;
  if(section.type==="hero")return<section {...data} className={shell(section,"sb-hero")} style={style}><Background section={section}/>{section.image&&<img data-builder-element="image" style={ss(section,"image")} className="sb-hero-image" src={section.image} alt="" data-parallax="10"/>}<div className="sb-hero-shade"/><div className="sb-inner sb-hero-copy">{section.eyebrow&&<span className="sb-kicker" data-builder-element="eyebrow" style={ss(section,"eyebrow")} data-reveal>{section.eyebrow}</span>}<h1 data-reveal data-reveal-delay="80"><span data-builder-element="title" style={ss(section,"title")}>{section.title}</span>{section.accent&&<><br/><i data-builder-element="accent" style={ss(section,"accent")}>{section.accent}</i></>}</h1>{section.text&&<p data-builder-element="text" style={ss(section,"text")} data-reveal data-reveal-delay="180">{section.text}</p>}<span data-reveal data-reveal-delay="240"><Button section={section}/></span></div></section>;
  if(section.type==="split")return<section {...data} className={shell(section,"sb-split-section")} style={style}><Background section={section}/><div className="sb-inner sb-split"><div className="sb-split-media" data-reveal>{section.image&&<img data-builder-element="image" style={ss(section,"image")} src={section.image} alt=""/>}</div><div className="sb-split-copy">{section.eyebrow&&<span className="sb-kicker" data-builder-element="eyebrow" style={ss(section,"eyebrow")} data-reveal>{section.eyebrow}</span>}<h2 data-reveal data-reveal-delay="80"><span data-builder-element="title" style={ss(section,"title")}>{section.title}</span>{section.accent&&<> <i data-builder-element="accent" style={ss(section,"accent")}>{section.accent}</i></>}</h2>{section.text&&<p data-builder-element="text" style={ss(section,"text")} data-reveal data-reveal-delay="160">{section.text}</p>}<span data-reveal data-reveal-delay="220"><Button section={section}/></span></div></div></section>;
  if(section.type==="stats")return<section {...data} className={shell(section,"sb-stats-section")} style={style}><Background section={section}/><div className="sb-inner"><Head section={section}/><div className="sb-stats">{section.items.map((item,index)=><article key={item.id} data-builder-element={`item:${item.id}:container`} style={is(item,"container")} data-reveal data-reveal-delay={index*80}><b data-builder-element={`item:${item.id}:value`} style={is(item,"value")}>{item.value}</b><strong data-builder-element={`item:${item.id}:title`} style={is(item,"title")}>{item.title}</strong>{item.text&&<span data-builder-element={`item:${item.id}:text`} style={is(item,"text")}>{item.text}</span>}</article>)}</div></div></section>;
  if(section.type==="cards")return<section {...data} className={shell(section,"sb-cards-section")} style={style}><Background section={section}/><div className="sb-inner"><Head section={section}/><div className="sb-cards">{section.items.map((item,index)=><article key={item.id} data-builder-element={`item:${item.id}:container`} style={is(item,"container")} data-reveal data-reveal-delay={index*90}>{item.image&&<img data-builder-element={`item:${item.id}:image`} style={is(item,"image")} src={item.image} alt=""/>}{item.icon&&<img data-builder-element={`item:${item.id}:icon`} style={is(item,"icon")} className="sb-card-icon" src={item.icon} alt=""/>}<div>{(item.eyebrow||item.subtitle)&&<small data-builder-element={`item:${item.id}:${item.eyebrow?"eyebrow":"subtitle"}`} style={is(item,item.eyebrow?"eyebrow":"subtitle")}>{item.eyebrow||item.subtitle}</small>}<h3 data-builder-element={`item:${item.id}:title`} style={is(item,"title")}>{item.title}</h3>{item.text&&<p data-builder-element={`item:${item.id}:text`} style={is(item,"text")}>{item.text}</p>}{item.linkLabel&&item.linkUrl&&<a data-builder-element={`item:${item.id}:link`} style={is(item,"link")} href={item.linkUrl}>{item.linkLabel} →</a>}</div></article>)}</div></div></section>;
  if(section.type==="gallery")return<section {...data} className={shell(section,"sb-gallery-section")} style={style}><Background section={section}/><div className="sb-inner"><Head section={section}/><div className="sb-gallery">{section.items.map(item=><figure key={item.id} data-builder-element={`item:${item.id}:container`} style={is(item,"container")}><img data-builder-element={`item:${item.id}:image`} style={is(item,"image")} src={item.image||"/team-entry-4k.webp"} alt={item.title||""}/>{(item.title||item.text)&&<figcaption>{item.title&&<b data-builder-element={`item:${item.id}:title`} style={is(item,"title")}>{item.title}</b>}{item.text&&<span data-builder-element={`item:${item.id}:text`} style={is(item,"text")}>{item.text}</span>}</figcaption>}</figure>)}</div></div></section>;
  if(section.type==="timeline")return<section {...data} className={shell(section,"sb-timeline-section")} style={style}><Background section={section}/><div className="sb-inner"><Head section={section}/><div className="sb-timeline"><div className="sb-drive-line"/><div className="sb-drive-arrow"/>{section.items.map((item,index)=>{const label=timelineLabel(item.subtitle);return<article key={item.id} className={index===section.items.length-1?"next":""} data-builder-element={`item:${item.id}:container`} style={is(item,"container")}><strong data-builder-element={`item:${item.id}:title`} style={is(item,"title")}>{item.title}</strong><span className="sb-ball"><img src={footballIcon} alt=""/></span>{label.tag&&<small data-builder-element={`item:${item.id}:subtitle`} style={is(item,"subtitle")}>{label.tag}</small>}{label.league&&<h3 data-builder-element={`item:${item.id}:subtitle`} style={is(item,"subtitle")}>{label.league}</h3>}{item.value&&<div className="sb-points"><span>POINTS</span><b data-builder-element={`item:${item.id}:value`} style={is(item,"value")}>{item.value}</b></div>}{item.icon&&<img data-builder-element={`item:${item.id}:icon`} style={is(item,"icon")} className="sb-timeline-icon" src={item.icon} alt=""/>}{item.text&&<p data-builder-element={`item:${item.id}:text`} style={is(item,"text")}>{item.text}</p>}</article>})}</div></div></section>;
  if(section.type==="cta")return<section {...data} className={shell(section,"sb-cta")} style={style}><Background section={section}/>{section.image&&<><img data-builder-element="image" style={ss(section,"image")} className="sb-cta-image" src={section.image} alt="" data-parallax="8"/><div className="sb-cta-shade"/></>}<div className="sb-inner">{section.eyebrow&&<span className="sb-kicker" data-builder-element="eyebrow" style={ss(section,"eyebrow")} data-reveal>{section.eyebrow}</span>}<h2 data-reveal data-reveal-delay="80"><span data-builder-element="title" style={ss(section,"title")}>{section.title}</span>{section.accent&&<> <i data-builder-element="accent" style={ss(section,"accent")}>{section.accent}</i></>}</h2>{section.text&&<p data-builder-element="text" style={ss(section,"text")} data-reveal data-reveal-delay="160">{section.text}</p>}<span data-reveal data-reveal-delay="220"><Button section={section}/></span></div></section>;
  if(section.type==="games")return<section {...data} id="spielplan" className={`section fixtures-section sb-native-section ${variant(section)} ${bgMode(section)}`} style={style}><Background section={section}/><div className="section-heading"><div>{section.eyebrow&&<span className="eyebrow red-text" data-builder-element="eyebrow" style={ss(section,"eyebrow")}>{section.eyebrow}</span>}<h2 data-builder-element="title" style={ss(section,"title")}>{section.title||"NÄCHSTE GAMES."}</h2></div>{section.text&&<p data-builder-element="text" style={ss(section,"text")}>{section.text}</p>}</div><div className="fixture-list"/></section>;
  if(section.type==="news")return<section {...data} className={`section news-preview sb-native-section ${variant(section)} ${bgMode(section)}`} style={style}><Background section={section}/><div className="section-heading"><div>{section.eyebrow&&<span className="eyebrow red-text" data-builder-element="eyebrow" style={ss(section,"eyebrow")}>{section.eyebrow}</span>}<h2 data-builder-element="title" style={ss(section,"title")}>{section.title||"FROM THE HUDDLE."}</h2></div></div><div className="news-grid"/></section>;
  if(section.type==="sponsors")return<section {...data} className={`sponsor-strip sb-native-section ${variant(section)} ${bgMode(section)}`} style={style}><Background section={section}/><p data-builder-element="title" style={ss(section,"title")}>{section.title||"PROUDLY POWERED BY"}</p><div className="ticker-window"><div className="ticker-track"/></div></section>;
  return<section {...data} className={shell(section,"sb-text-section")} style={style}><Background section={section}/><div className="sb-inner sb-text">{section.eyebrow&&<span className="sb-kicker" data-builder-element="eyebrow" style={ss(section,"eyebrow")}>{section.eyebrow}</span>}<h2><span data-builder-element="title" style={ss(section,"title")}>{section.title}</span>{section.accent&&<> <i data-builder-element="accent" style={ss(section,"accent")}>{section.accent}</i></>}</h2>{section.text&&<p data-builder-element="text" style={ss(section,"text")}>{section.text}</p>}<Button section={section}/></div></section>;
}

function BuilderHeader({state,current}:{state:SiteBuilderState;current:BuilderPage}){
  const[open,setOpen]=useState(false);
  const pages=state.pages.filter(page=>page.showInNav&&(page.enabled||legacySlugs.has(page.slug)));
  return<header data-builder-theme="header" className="sb-header" style={{background:state.theme.headerBackground,color:state.theme.headerText}}>
    <a data-builder-theme-element="brand" className="sb-brand" href="/"><img src={state.theme.logoUrl||"/rascals-logo-transparent-4k.png"} alt=""/><span><b>{state.theme.brandTop||"HELLENSTEIN"}</b><em>{state.theme.brandBottom||"RASCALS"}</em></span></a>
    <button className="sb-menu" onClick={()=>setOpen(!open)} aria-label="Menü" aria-expanded={open} aria-controls="sb-main-nav">☰</button>
    <nav id="sb-main-nav" className={open?"open":""} aria-label="Hauptnavigation">
      {/* The schedule is a standalone route, not a builder page, so it is not
          in state.pages. For a football club it is the most-wanted page, so it
          is pinned first rather than being reachable only from in-page links. */}
      <a href="/spielplan">Spielplan</a>
      {pages.map(page=><a key={page.id} className={page.id===current.id?"active":""} href={page.slug?`/${page.slug}`:"/"}>{page.navLabel}</a>)}
      {state.theme.navCtaLabel&&state.theme.navCtaUrl&&<a className="sb-nav-cta" href={state.theme.navCtaUrl}>{state.theme.navCtaLabel}</a>}
    </nav>
  </header>;
}

export function SiteBuilderPage({state,page}:{state:SiteBuilderState;page:BuilderPage}){const hasGames=page.sections.some(section=>section.visible&&section.type==="games"),hasFeeds=page.sections.some(section=>section.visible&&(section.type==="news"||section.type==="sponsors"));const vars:VarStyle={"--site-bg":state.theme.background,"--site-text":state.theme.text,"--site-accent":brandColor(state.theme.accent),"--site-surface":state.theme.surface,"--site-muted":state.theme.muted,"--site-max":`${state.theme.contentWidth}px`,"--site-radius":`${state.theme.radius}px`,"--site-heading-font":withDesignFont(state.theme.headingFont,"--font-display"),"--site-body-font":withDesignFont(state.theme.bodyFont,"--font-body"),"--site-heading-weight":String(state.theme.headingWeight),"--site-heading-tracking":`${state.theme.headingTracking}em`,"--site-body-line":String(state.theme.bodyLineHeight),"--site-heading-transform":state.theme.headingTransform,"--builder-body-size":`${state.theme.bodyFontSize??16}px`,"--builder-body-weight":String(state.theme.bodyFontWeight??400),"--builder-body-style":state.theme.bodyItalic?"italic":"normal","--builder-body-tracking":`${state.theme.bodyLetterSpacing??0}em`,"--builder-heading-style":state.theme.headingItalic?"italic":"normal"};return<div className="sb-site builder-type-scope" data-builder-site style={vars as CSSProperties}><BuilderHeader state={state} current={page}/><main>{page.sections.map(section=><BuilderSectionView key={section.id} section={section}/>)}</main>{hasGames&&<DynamicHomeGames/>}{hasFeeds&&<DynamicHomeFeeds/>}<footer data-builder-theme="footer" className="sb-footer"><span>{state.theme.footerTitle||"HELLENSTEIN RASCALS"}</span><small>{state.theme.footerSubtitle||"American Football · Heidenheim"}</small></footer></div>}
