"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminNotice, AdminShell } from "../../_components/AdminShell";
import { ImageUploadField } from "../../_components/ImageUploadField";
import "./games.css";

type Game = {
  id:string; slug:string; opponent:string; opponentLogo:string; venue:string; homeAway:"home"|"away"; kickoff:string|null;
  status:"upcoming"|"live"|"final"|"postponed"|"cancelled"; rascalsScore:number; opponentScore:number; quarter:string; gameClock:string;
  gamedayAssignee:string; createdAt:string; updatedAt:string;
};
type GamedayUser={email:string;display_name:string;role:"admin"|"coach"|"gameday"};
const emptyGame:Game={id:"",slug:"",opponent:"",opponentLogo:"",venue:"",homeAway:"home",kickoff:null,status:"upcoming",rascalsScore:0,opponentScore:0,quarter:"",gameClock:"",gamedayAssignee:"",createdAt:"",updatedAt:""};

export function GamesManager(){
 const[items,setItems]=useState<Game[]>([]);const[gamedayUsers,setGamedayUsers]=useState<GamedayUser[]>([]);const[selected,setSelected]=useState<Game>(emptyGame);const[query,setQuery]=useState("");const[notice,setNotice]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[removing,setRemoving]=useState(false);
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);try{const[gamesRes,usersRes]=await Promise.all([fetch("/admin/api/games"),fetch("/admin/api/gameday-users")]);if(!gamesRes.ok)throw new Error("Spielplan konnte nicht geladen werden.");const games=await gamesRes.json() as {items:Game[]};const users=usersRes.ok?await usersRes.json() as {items:GamedayUser[]}:{items:[]};setItems(games.items);setGamedayUsers(users.items);setSelected(games.items[0]??emptyGame)}catch(e){setNotice(e instanceof Error?e.message:"Unbekannter Fehler")}finally{setLoading(false)}}
 async function save(){if(!selected.opponent.trim()){setNotice("Bitte einen Gegner eintragen.");return}setSaving(true);setNotice("");try{const r=await fetch("/admin/api/games",{method:selected.id?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(selected)});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Speichern fehlgeschlagen.")}const b=await r.json() as {item:Game};setItems(cur=>selected.id?cur.map(x=>x.id===b.item.id?b.item:x):[...cur,b.item]);setSelected(b.item);setNotice("Spiel gespeichert.")}catch(e){setNotice(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setSaving(false)}}
 async function remove(){if(!selected.id)return;const confirmed=confirm(`Spiel gegen ${selected.opponent} wirklich aus dem Spielplan entfernen?\n\nDas Spiel verschwindet sofort aus dem aktiven Spielplan. Vorhandene Liveticker- und Statistikdaten bleiben zur Sicherheit im Papierkorb erhalten.`);if(!confirmed)return;setRemoving(true);setNotice("");try{const id=selected.id;const r=await fetch(`/admin/api/games?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Spiel konnte nicht entfernt werden.")}const remaining=items.filter(x=>x.id!==id);setItems(remaining);setSelected(remaining[0]??emptyGame);setNotice("Spiel wurde aus dem Spielplan entfernt.")}catch(e){setNotice(e instanceof Error?e.message:"Spiel konnte nicht entfernt werden.")}finally{setRemoving(false)}}
 const filtered=useMemo(()=>items.filter(x=>`${x.opponent} ${x.venue} ${x.status}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const isLive=selected.status==="live";const assignedUser=gamedayUsers.find(u=>u.email.toLowerCase()===selected.gamedayAssignee.toLowerCase());
 return <AdminShell active="games" title="Spielplan & Ergebnisse" actions={<div className="games-top-actions">{selected.id&&<button className="cms-button secondary danger" disabled={removing||saving||loading} onClick={()=>void remove()}>{removing?"Entfernt…":"Spiel entfernen"}</button>}<button className="cms-button" disabled={saving||removing||loading} onClick={()=>void save()}>{saving?"Speichert…":"Spiel speichern"}</button></div>}>
  {notice&&<AdminNotice tone={notice.includes("gespeichert")||notice.includes("entfernt")?"success":"error"}>{notice}</AdminNotice>}
  <div className="games-layout">
   <AdminCard className="games-list"><div className="cms-section-head"><div><small>SAISON 2026</small><h2>{items.length} Spiele</h2></div><button className="cms-button secondary" onClick={()=>setSelected(emptyGame)}>＋ Spiel</button></div><input className="games-search" placeholder="Gegner oder Ort…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="games-items">{filtered.map(game=><button key={game.id} className={selected.id===game.id?"active":""} onClick={()=>setSelected(game)}><span className={`game-status-dot ${game.status}`}/><span><b>{game.homeAway==="home"?"vs":"@"} {game.opponent}</b><small>{formatDate(game.kickoff)} · {statusLabel(game.status)}</small></span>{game.status==="final"||game.status==="live"?<strong>{game.rascalsScore}:{game.opponentScore}</strong>:null}</button>)}</div></AdminCard>
   <div className="games-editor">
    <AdminCard><div className="cms-section-head"><div><small>GAME CARD</small><h2>{selected.opponent||"Neues Spiel"}</h2></div>{selected.id&&<button className="cms-button secondary danger" disabled={removing} onClick={()=>void remove()}>{removing?"Entfernt…":"Spiel entfernen"}</button>}</div><div className={`game-score-preview ${isLive?"live":""}`}><div><img src="/rascals-logo-transparent-4k.png" alt="Rascals Logo"/><b>RASCALS</b><strong>{selected.rascalsScore}</strong></div><span>{isLive?"LIVE":statusLabel(selected.status)}</span><div>{selected.opponentLogo?<img src={selected.opponentLogo} alt={`${selected.opponent||"Gegner"} Logo`}/>:<div className="game-logo-placeholder">?</div>}<b>{selected.opponent||"GEGNER"}</b><strong>{selected.opponentScore}</strong></div></div></AdminCard>
    <AdminCard><div className="cms-grid-2">
      <label className="cms-field"><span>Gegner</span><input value={selected.opponent} onChange={e=>setSelected({...selected,opponent:e.target.value})}/></label>
      <ImageUploadField label="Gegnerlogo importieren" value={selected.opponentLogo} onChange={opponentLogo=>setSelected({...selected,opponentLogo})} helper="Logo direkt hochladen. Es wird automatisch gespeichert und diesem Spiel zugeordnet."/>
      <label className="cms-field"><span>Heim / Auswärts</span><select value={selected.homeAway} onChange={e=>setSelected({...selected,homeAway:e.target.value as Game["homeAway"]})}><option value="home">Heimspiel</option><option value="away">Auswärtsspiel</option></select></label>
      <label className="cms-field"><span>Datum & Kickoff</span><input type="datetime-local" value={toLocalInput(selected.kickoff)} onChange={e=>setSelected({...selected,kickoff:e.target.value||null})}/></label>
      <label className="cms-field hero-full"><span>Ort / Stadion</span><input value={selected.venue} onChange={e=>setSelected({...selected,venue:e.target.value})} placeholder="z. B. Heidenheim"/></label>
      <label className="cms-field"><span>Status</span><select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value as Game["status"]})}><option value="upcoming">Kommend</option><option value="live">Live</option><option value="final">Beendet</option><option value="postponed">Verschoben</option><option value="cancelled">Abgesagt</option></select></label>
      <label className="cms-field"><span>Quarter (optional)</span><select value={selected.quarter} onChange={e=>setSelected({...selected,quarter:e.target.value})}><option value="">—</option><option>Q1</option><option>Q2</option><option>HALFTIME</option><option>Q3</option><option>Q4</option><option>OT</option><option>FINAL</option></select></label>
      <label className="cms-field"><span>Liveticker-Verantwortlicher</span><select value={selected.gamedayAssignee} onChange={e=>setSelected({...selected,gamedayAssignee:e.target.value})}><option value="">Niemand fest zugewiesen</option>{gamedayUsers.map(u=><option key={u.email} value={u.email}>{u.display_name||u.email} · {u.role==="gameday"?"GAMEDAY":u.role.toUpperCase()}</option>)}</select><small>{assignedUser?`${assignedUser.display_name||assignedUser.email} übernimmt den Liveticker für dieses Spiel.`:"Optional: z. B. einen verletzten oder nicht aufgestellten Spieler mit Gameday-Rolle auswählen."}</small></label>
      <label className="cms-field"><span>Rascals Punkte</span><input type="number" min="0" value={selected.rascalsScore} onChange={e=>setSelected({...selected,rascalsScore:Math.max(0,Number(e.target.value))})}/></label>
      <label className="cms-field"><span>Gegner Punkte</span><input type="number" min="0" value={selected.opponentScore} onChange={e=>setSelected({...selected,opponentScore:Math.max(0,Number(e.target.value))})}/></label>
    </div><div className="quick-score"><span>Schnell ändern:</span><button onClick={()=>setSelected({...selected,rascalsScore:selected.rascalsScore+6})}>Rascals +6</button><button onClick={()=>setSelected({...selected,rascalsScore:selected.rascalsScore+1})}>+1</button><button onClick={()=>setSelected({...selected,rascalsScore:selected.rascalsScore+3})}>+3</button><button onClick={()=>setSelected({...selected,opponentScore:selected.opponentScore+6})}>Gegner +6</button><button onClick={()=>setSelected({...selected,opponentScore:selected.opponentScore+1})}>+1</button><button onClick={()=>setSelected({...selected,opponentScore:selected.opponentScore+3})}>+3</button></div></AdminCard>
    {selected.id&&<AdminCard><div className="cms-section-head"><div><small>SPIELTAG</small><h2>Einfacher Live-Ticker</h2></div><a className="cms-button secondary" href={`/admin/gameday?game=${selected.id}`}>Gameday öffnen →</a></div><p className="cms-muted">Nur wichtige Ereignisse erfassen: Touchdown, Interception, Sack, Halbzeit, Spielende oder Freitext.{assignedUser?` Zugewiesen an ${assignedUser.display_name||assignedUser.email}.`:""}</p></AdminCard>}
   </div>
  </div>
 </AdminShell>
}
function formatDate(value:string|null){if(!value)return"Noch kein Termin";const d=new Date(value);if(Number.isNaN(d.getTime()))return value.replace("T"," ");return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(d)}
function toLocalInput(value:string|null){return value?value.slice(0,16):""}
function statusLabel(status:Game["status"]){return({upcoming:"KOMMEND",live:"LIVE",final:"FINAL",postponed:"VERSCHOBEN",cancelled:"ABGESAGT"} as const)[status]}
