"use client";

import { useEffect, useState } from "react";
import { AdminCard, AdminNotice, AdminShell } from "../../_components/AdminShell";
import "./team-development.css";

type Season={id:string;year:number;name:string;isCurrent:boolean};
type Group={key:string;label:string;unit:string;players:number;coveragePct:number;currentIndex:number|null;needIndex:number|null;focusSkills:number;evaluateFirst:number;trend:number|null;openGoals:number};
type Need={group:string;groupLabel:string;unit:string;key:string;label:string;category:string;count:number;current:number;target:number;needScore:number;coveragePct:number;trend:number|null;state:string};
type Player={group:string;groupLabel:string;playerId:string;jerseyNumber:number|null;name:string;position:string;availability:string;coveragePct:number;currentIndex:number;needIndex:number;trend:number|null;openGoals:number};
type Goal={id:string;playerId:string;skillKey:string|null;title:string;status:string;dueDate:string|null;updatedAt:string};
type Payload={seasons:Season[];season:Season;summary:{players:number;coveragePct:number;currentIndex:number|null;needIndex:number|null;focusSkills:number;openGoals:number;overdueGoals:number};groups:Group[];topNeeds:Need[];playerWatchlist:Player[];goals:Goal[]};

export function TeamDevelopmentManager(){
 const[data,setData]=useState<Payload|null>(null);const[seasonId,setSeasonId]=useState("");const[loading,setLoading]=useState(true);const[notice,setNotice]=useState("");
 useEffect(()=>{void boot()},[]);
 async function boot(){const q=new URLSearchParams(window.location.search);await load(q.get("season")||undefined)}
 async function load(id?:string){setLoading(true);setNotice("");try{const q=new URLSearchParams();if(id)q.set("seasonId",id);const r=await fetch(`/admin/api/development/team?${q}`);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Team Development konnte nicht geladen werden.")}const b=await r.json() as Payload;setData(b);setSeasonId(b.season.id)}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 async function changeSeason(id:string){setSeasonId(id);window.history.replaceState(null,"",`/admin/development/team?season=${encodeURIComponent(id)}`);await load(id)}
 return <AdminShell active="teamdev" title="Team Development Command Center" eyebrow="RASCALS OS · HEAD COACH DEVELOPMENT" actions={<><a className="cms-button secondary" href="/admin/development/positions">Position Development</a><a className="cms-button secondary" href="/admin/stats/analytics">Stats Analytics</a></>}>
  {notice&&<AdminNotice tone="error">{notice}</AdminNotice>}
  <AdminCard className="td-hero"><div><small>HEAD COACH VIEW</small><h2>Gesamte sportliche Entwicklung auf einer Seite</h2><p>Alle Position Rooms werden hier zusammengeführt: Evaluation Coverage, aktuelle Skill-Stärke, Development Needs, Trends, offene Ziele und die Spieler mit dem höchsten Entwicklungsbedarf.</p></div><label className="cms-field"><span>Saison</span><select value={seasonId} disabled={loading} onChange={e=>void changeSeason(e.target.value)}>{data?.seasons.map(s=><option key={s.id} value={s.id}>{s.name}{s.isCurrent?" · AKTUELL":""}</option>)}</select></label></AdminCard>
  <div className="td-kpis"><Metric label="Players" value={data?.summary.players}/><Metric label="Evaluation Coverage" value={data?.summary.coveragePct} suffix="%"/><Metric label="Current Skill Index" value={data?.summary.currentIndex} suffix="/100"/><Metric label="Need Index" value={data?.summary.needIndex} suffix="/100" risk/><Metric label="Focus Skills" value={data?.summary.focusSkills}/><Metric label="Open Goals" value={data?.summary.openGoals} suffix={data?.summary.overdueGoals?` · ${data.summary.overdueGoals} overdue`:""} risk={Boolean(data?.summary.overdueGoals)}/></div>
  <AdminCard><div className="cms-section-head"><div><small>POSITION ROOMS</small><h2>Offense · Defense · Special Teams</h2></div></div><div className="td-groups">{data?.groups.map(g=><a key={g.key} href={`/admin/development/positions?group=${encodeURIComponent(g.key)}&season=${encodeURIComponent(seasonId)}`}><div><small>{g.unit.toUpperCase()}</small><h3>{g.label}</h3><span>{g.players} Spieler · {g.coveragePct}% Coverage</span></div><div className="td-group-metrics"><em>CUR <b>{g.currentIndex??"–"}</b></em><em>NEED <b>{g.needIndex??"–"}</b></em><em>FOCUS <b>{g.focusSkills}</b></em><Trend value={g.trend}/></div></a>)}</div></AdminCard>
  <div className="td-main-grid"><AdminCard><div className="cms-section-head"><div><small>TEAM TRAINING NEEDS</small><h2>Top Entwicklungsfelder</h2></div><span className="cms-muted">Positionsübergreifend</span></div><div className="td-needs">{data?.topNeeds.map((n,i)=><article key={`${n.group}-${n.key}`}><b>{i+1}</b><div><strong>{n.label}</strong><span>{n.groupLabel} · {n.category}</span></div><em>{n.current||"–"} → {n.target||"–"}</em><Status state={n.state} score={n.needScore}/><strong>{n.coveragePct}%</strong></article>)}</div></AdminCard><AdminCard><div className="cms-section-head"><div><small>HEAD COACH WATCHLIST</small><h2>Highest Player Needs</h2></div></div><div className="td-watch">{data?.playerWatchlist.map(p=><a key={`${p.group}-${p.playerId}`} href={`/admin/development/positions?group=${p.group}&season=${encodeURIComponent(seasonId)}&player=${encodeURIComponent(p.playerId)}`}><span><b>#{p.jerseyNumber??"–"} {p.name}</b><small>{p.groupLabel} · {p.position} · {p.availability.toUpperCase()}</small></span><div><em>NEED {p.needIndex}</em><em>CUR {p.currentIndex}</em><em>{p.coveragePct}% COV</em><Trend value={p.trend}/></div></a>)}</div></AdminCard></div>
  <AdminCard><div className="cms-section-head"><div><small>DEVELOPMENT GOVERNANCE</small><h2>Offene Ziele</h2></div><span className="cms-muted">{data?.summary.overdueGoals??0} überfällig</span></div><div className="td-goals">{data?.goals.map(g=><article key={g.id}><div><b>{g.title}</b><small>{g.skillKey??"Allgemeines Development Goal"}</small></div><span>{g.status.toUpperCase()}</span><em>{g.dueDate?new Date(g.dueDate).toLocaleDateString("de-DE"):"Kein Termin"}</em></article>)}{!data?.goals.length&&<p className="cms-muted">Keine offenen Development Goals.</p>}</div></AdminCard>
 </AdminShell>
}
function Metric({label,value,suffix="",risk=false}:{label:string;value:number|null|undefined;suffix?:string;risk?:boolean}){return <div className={`td-metric ${risk?"risk":""}`}><small>{label}</small><b>{value==null?"–":`${value}${suffix}`}</b></div>}
function Trend({value}:{value:number|null}){return <span className={`td-trend ${value==null||value===0?"flat":value>0?"up":"down"}`}>{value==null?"–":value>0?`▲ +${value.toFixed(1)}`:value<0?`▼ ${value.toFixed(1)}`:"→ 0.0"}</span>}
function Status({state,score}:{state:string;score:number}){const label=state==="focus"?"FOCUS":state==="improve"?"IMPROVE":state==="evaluate-first"?"EVALUATE":"MAINTAIN";return <span className={`td-status ${state}`}>{label} · {score}</span>}
