"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminNotice, AdminShell } from "../_components/AdminShell";
import "./stats.css";

type Season={id:string;year:number;name:string;isCurrent:boolean};
type Game={id:string;opponent:string;kickoff:string|null;status:string;rascalsScore:number;opponentScore:number};
type Player={id:string;jerseyNumber:number|null;position:string;firstName:string;lastName:string};
type Definition={key:string;label:string;shortLabel:string;category:"offense"|"defense"|"special-teams";valueType:string;positions:string[]};
type StatRecord={id:string;playerId:string;gameId:string|null;seasonId:string|null;season:number;statKey:string;statValue:number;status:"provisional"|"reviewed"|"official";source:string;sourceEventId:string|null;note:string;createdBy:string;reviewedBy:string;reviewedAt:string|null;officialBy:string;officialAt:string|null;createdAt:string;updatedAt:string;firstName:string;lastName:string;jerseyNumber:number|null;position:string;definition:null|{key:string;label:string;shortLabel:string;category:string;valueType:string}};
type Leader={statKey:string;label:string;shortLabel:string;category:string;playerId:string;firstName:string;lastName:string;jerseyNumber:number|null;total:number};
type Payload={season:Season;seasons:Season[];games:Game[];players:Player[];definitions:Definition[];records:StatRecord[];counts:{provisional:number;reviewed:number;official:number};leaders:Leader[]};
type StatusFilter="all"|"provisional"|"reviewed"|"official";

export function StatsManager(){
 const[data,setData]=useState<Payload|null>(null);const[seasonId,setSeasonId]=useState("");const[gameId,setGameId]=useState("");const[status,setStatus]=useState<StatusFilter>("provisional");const[selected,setSelected]=useState<Set<string>>(new Set());const[notice,setNotice]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
 const[playerId,setPlayerId]=useState("");const[statKey,setStatKey]=useState("");const[value,setValue]=useState("1");const[note,setNote]=useState("");const[category,setCategory]=useState<"all"|"offense"|"defense"|"special-teams">("all");
 useEffect(()=>{void boot()},[]);
 async function boot(){const params=new URLSearchParams(window.location.search);setGameId(params.get("game")??"");await load(params.get("season")??undefined,params.get("game")??"",status)}
 async function load(nextSeason?:string,nextGame=gameId,nextStatus:StatusFilter=status){setLoading(true);setNotice("");try{const params=new URLSearchParams();if(nextSeason)params.set("seasonId",nextSeason);if(nextGame)params.set("gameId",nextGame);if(nextStatus!=="all")params.set("status",nextStatus);const r=await fetch(`/admin/api/stats?${params.toString()}`);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Stats konnten nicht geladen werden.")}const b=await r.json() as Payload;setData(b);setSeasonId(b.season.id);setSelected(new Set());if(!playerId&&b.players[0])setPlayerId(b.players[0].id);if(!statKey&&b.definitions[0])setStatKey(b.definitions[0].key)}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 async function changeSeason(id:string){setSeasonId(id);setGameId("");window.history.replaceState(null,"",`/admin/stats?season=${encodeURIComponent(id)}`);await load(id,"",status)}
 async function changeGame(id:string){setGameId(id);const qs=new URLSearchParams({season:seasonId});if(id)qs.set("game",id);window.history.replaceState(null,"",`/admin/stats?${qs.toString()}`);await load(seasonId,id,status)}
 async function changeStatus(next:StatusFilter){setStatus(next);await load(seasonId,gameId,next)}
 function toggle(id:string){setSelected(cur=>{const n=new Set(cur);n.has(id)?n.delete(id):n.add(id);return n})}
 function toggleAll(){setSelected(cur=>cur.size===visibleRecords.length?new Set():new Set(visibleRecords.map(x=>x.id)))}
 async function setBulkStatus(next:"provisional"|"reviewed"|"official"){if(!selected.size)return;setSaving(true);setNotice("");try{const r=await fetch("/admin/api/stats",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({action:"set-status",ids:[...selected],status:next})});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Status konnte nicht geändert werden.")}await load(seasonId,gameId,status);setNotice(next==="official"?"Ausgewählte Statistiken sind jetzt OFFICIAL.":next==="reviewed"?"Ausgewählte Statistiken wurden reviewed.":"Ausgewählte Statistiken wurden auf provisional zurückgesetzt.")}catch(e){setNotice(e instanceof Error?e.message:"Statusänderung fehlgeschlagen.")}finally{setSaving(false)}}
 async function addManual(){if(!playerId||!gameId||!statKey)return setNotice("Für eine manuelle Statistik bitte Spiel, Spieler und Stat auswählen.");setSaving(true);setNotice("");try{const r=await fetch("/admin/api/stats",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({playerId,gameId,statKey,value:Number(value),note})});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Statistik konnte nicht gespeichert werden.")}setNote("");setValue("1");setStatus("provisional");await load(seasonId,gameId,"provisional");setNotice("Manuelle Statistik als PROVISIONAL gespeichert.")}catch(e){setNotice(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setSaving(false)}}
 const visibleRecords=useMemo(()=>data?.records.filter(r=>category==="all"||r.definition?.category===category)??[],[data,category]);
 const defs=useMemo(()=>data?.definitions.filter(d=>category==="all"||d.category===category)??[],[data,category]);
 const leaders=useMemo(()=>data?.leaders.filter(l=>category==="all"||l.category===category).slice(0,12)??[],[data,category]);
 return <AdminShell active="stats" title="Stats Review" eyebrow="RASCALS OS · FOOTBALL DATA" actions={<><a className="cms-button secondary" href={`/admin/stats/analytics${seasonId?`?season=${encodeURIComponent(seasonId)}${gameId?`&game=${encodeURIComponent(gameId)}`:""}`:""}`}>Box Score & Analytics</a><a className="cms-button secondary" href="/admin/gameday">Gameday</a><a className="cms-button secondary" href="/admin/performance">Performance</a></>}>
  {notice&&<AdminNotice tone={notice.includes("gespeichert")||notice.includes("reviewed")||notice.includes("OFFICIAL")||notice.includes("zurückgesetzt")?"success":"error"}>{notice}</AdminNotice>}
  <AdminCard className="stats-control"><div className="stats-control-grid"><label className="cms-field"><span>Saison</span><select value={seasonId} onChange={e=>void changeSeason(e.target.value)}>{data?.seasons.map(s=><option key={s.id} value={s.id}>{s.name}{s.isCurrent?" · AKTUELL":""}</option>)}</select></label><label className="cms-field"><span>Spiel</span><select value={gameId} onChange={e=>void changeGame(e.target.value)}><option value="">Alle Spiele</option>{data?.games.map(g=><option key={g.id} value={g.id}>{formatDate(g.kickoff)} · vs. {g.opponent}</option>)}</select></label><label className="cms-field"><span>Unit</span><select value={category} onChange={e=>setCategory(e.target.value as typeof category)}><option value="all">Alle Units</option><option value="offense">Offense</option><option value="defense">Defense</option><option value="special-teams">Special Teams</option></select></label></div></AdminCard>
  <div className="stats-kpis"><button className={status==="provisional"?"active provisional":"provisional"} onClick={()=>void changeStatus("provisional")}><small>PROVISIONAL</small><b>{data?.counts.provisional??0}</b><span>aus Live/Manual</span></button><button className={status==="reviewed"?"active reviewed":"reviewed"} onClick={()=>void changeStatus("reviewed")}><small>REVIEWED</small><b>{data?.counts.reviewed??0}</b><span>Coach geprüft</span></button><button className={status==="official"?"active official":"official"} onClick={()=>void changeStatus("official")}><small>OFFICIAL</small><b>{data?.counts.official??0}</b><span>freigegeben</span></button><button className={status==="all"?"active":""} onClick={()=>void changeStatus("all")}><small>ANSICHT</small><b>ALL</b><span>alle Status</span></button></div>
  <div className="stats-main-grid"><AdminCard className="stats-review-card"><div className="cms-section-head"><div><small>REVIEW QUEUE</small><h2>{visibleRecords.length} Stat-Einträge</h2></div><div className="stats-bulk"><button disabled={!selected.size||saving} onClick={()=>void setBulkStatus("provisional")}>Provisional</button><button disabled={!selected.size||saving} onClick={()=>void setBulkStatus("reviewed")}>Reviewed</button><button disabled={!selected.size||saving} onClick={()=>void setBulkStatus("official")}>Official</button></div></div><p className="cms-muted">Liveticker-Stats starten als provisional. Reviewed bedeutet fachlich geprüft; nur Official zählt in den offiziellen Season-Leadern.</p><div className="stats-table-wrap"><table className="stats-table"><thead><tr><th><input type="checkbox" checked={visibleRecords.length>0&&selected.size===visibleRecords.length} onChange={toggleAll}/></th><th>Spieler</th><th>Stat</th><th>Wert</th><th>Quelle</th><th>Status</th><th>Notiz</th></tr></thead><tbody>{visibleRecords.map(r=><tr key={r.id}><td><input type="checkbox" checked={selected.has(r.id)} onChange={()=>toggle(r.id)}/></td><td><b>#{r.jerseyNumber??"–"} {r.firstName} {r.lastName}</b><small>{r.position||"–"}</small></td><td><strong>{r.definition?.shortLabel??r.statKey}</strong><small>{r.definition?.label??r.statKey}</small></td><td className="stats-value">{r.statValue}</td><td><span className="stats-source">{r.source.toUpperCase()}</span></td><td><em className={`stats-status ${r.status}`}>{r.status.toUpperCase()}</em></td><td><span>{r.note||"–"}</span></td></tr>)}</tbody></table>{!visibleRecords.length&&<div className="stats-empty">Keine Statistiken für diesen Filter.</div>}</div></AdminCard>
   <div className="stats-side"><AdminCard><div className="cms-section-head"><div><small>MANUAL ENTRY</small><h2>Stat ergänzen</h2></div></div><div className="stats-manual"><label className="cms-field"><span>Spieler</span><select value={playerId} onChange={e=>setPlayerId(e.target.value)}><option value="">Spieler wählen</option>{data?.players.map(p=><option key={p.id} value={p.id}>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName} · {p.position}</option>)}</select></label><label className="cms-field"><span>Statistik</span><select value={statKey} onChange={e=>setStatKey(e.target.value)}>{defs.map(d=><option key={d.key} value={d.key}>{d.shortLabel} · {d.label}</option>)}</select></label><label className="cms-field"><span>Wert</span><input type="number" step="0.5" value={value} onChange={e=>setValue(e.target.value)}/></label><label className="cms-field"><span>Notiz</span><input value={note} onChange={e=>setNote(e.target.value)} placeholder="z. B. nach Film Review ergänzt"/></label><button className="cms-button" disabled={saving||!gameId} onClick={()=>void addManual()}>{saving?"Speichert…":"Als Provisional speichern"}</button>{!gameId&&<small className="cms-muted">Für manuelle Game Stats zuerst ein Spiel auswählen.</small>}</div></AdminCard>
   <AdminCard><div className="cms-section-head"><div><small>OFFICIAL LEADERS</small><h2>Season Leaders</h2></div></div><div className="stats-leaders">{leaders.map(l=><article key={l.statKey}><span><small>{l.shortLabel}</small><b>#{l.jerseyNumber??"–"} {l.firstName} {l.lastName}</b></span><strong>{l.total}</strong></article>)}{!leaders.length&&<p className="cms-muted">Noch keine Official Stats für diesen Filter.</p>}</div></AdminCard></div>
  </div>
 </AdminShell>
}
function formatDate(value:string|null){if(!value)return"ohne Datum";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",year:"2-digit"}).format(d)}
