"use client";
import {useEffect,useMemo,useState} from "react";
import {AdminCard} from "../_components/AdminShell";
import {ScoutField} from "./PlaybookFields";
import {loadStudioStore,opponentMarkers,routeLabels,saveStudioStore,scoutFormationOptions,scoutTags,type CustomRoute,type OpponentDiagramPlayer,type OpponentDiagramRoute,type RouteKind,type ScoutClip,type ScoutGame} from "./playbook-studio-model";

export function OpponentScouting({customRoutes,onNotice}:{customRoutes:CustomRoute[];onNotice:(message:string)=>void}){
 const[games,setGames]=useState<ScoutGame[]>([]),[gameId,setGameId]=useState(""),[selectedClipId,setSelectedClipId]=useState(""),[seasonFilter,setSeasonFilter]=useState("all"),[unitFilter,setUnitFilter]=useState("All"),[opponent,setOpponent]=useState(""),[gameDate,setGameDate]=useState("2026-08-10"),[gameSeason,setGameSeason]=useState(2026),[competition,setCompetition]=useState("Season"),[location,setLocation]=useState("home"),[rascalsScore,setRascalsScore]=useState(0),[opponentScore,setOpponentScore]=useState(0);
 const[editingClipId,setEditingClipId]=useState(""),[title,setTitle]=useState(""),[videoUrl,setVideoUrl]=useState(""),[localVideo,setLocalVideo]=useState(""),[unit,setUnit]=useState("Offense"),[quarter,setQuarter]=useState("Q1"),[clock,setClock]=useState("12:00"),[down,setDown]=useState(1),[distance,setDistance]=useState(10),[yards,setYards]=useState(0),[fieldHalf,setFieldHalf]=useState<"own"|"opponent">("own"),[yardLine,setYardLine]=useState(25),[hash,setHash]=useState<"Left"|"Middle"|"Right">("Middle"),[personnel,setPersonnel]=useState("11"),[formation,setFormation]=useState("Gun Trips Right"),[motion,setMotion]=useState("None"),[playType,setPlayType]=useState("Run"),[concept,setConcept]=useState(""),[result,setResult]=useState(""),[tags,setTags]=useState<string[]>([]),[notes,setNotes]=useState("");
 const[diagramPlayers,setDiagramPlayers]=useState<OpponentDiagramPlayer[]>(opponentMarkers("Offense","Gun Trips Right")),[diagramRoutes,setDiagramRoutes]=useState<OpponentDiagramRoute[]>([]),[routeTarget,setRouteTarget]=useState("WR1"),[routeKind,setRouteKind]=useState<RouteKind>("hook"),[routeDistance,setRouteDistance]=useState(5),[routeBreak,setRouteBreak]=useState(5),[routeAngle,setRouteAngle]=useState(45),[customRouteId,setCustomRouteId]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){const stored=await loadStudioStore<ScoutGame[]>("scouting");const next=stored??[];setGames(next);if(next[0]){setGameId(next[0].id);setSelectedClipId(next[0].clips[0]?.id??"")}}
 async function persist(next:ScoutGame[]){setGames(next);await saveStudioStore("scouting",next)}
 async function addGame(){if(!opponent.trim()||!gameDate)return onNotice("Bitte Gegner und Spieldatum eintragen.");const game:ScoutGame={id:crypto.randomUUID(),opponent:opponent.trim(),date:gameDate,season:gameSeason||Number(gameDate.slice(0,4))||2026,competition:competition.trim()||"Season",location,rascalsScore,opponentScore,clips:[]};const next=[game,...games].sort((a,b)=>b.date.localeCompare(a.date));await persist(next);setGameId(game.id);setSelectedClipId("");setOpponent("");onNotice(`Spiel gegen ${game.opponent} wurde im Gegnerarchiv angelegt.`)}
 function selectGame(id:string){setGameId(id);const next=games.find(g=>g.id===id);setSelectedClipId(next?.clips[0]?.id??"")}
 function changeUnit(value:string){setUnit(value);const next=scoutFormationOptions[value]?.[0]??"";setFormation(next);const players=opponentMarkers(value,next);setDiagramPlayers(players);setDiagramRoutes([]);setRouteTarget(players[0]?.label??"")}
 function changeFormation(value:string){setFormation(value);const players=opponentMarkers(unit,value),valid=new Set(players.map(p=>p.label));setDiagramPlayers(players);setDiagramRoutes(cur=>unit==="Offense"?cur.filter(r=>valid.has(r.target)):[]);setRouteTarget(players[0]?.label??"")}
 function addRoute(){if(!routeTarget)return;const route:OpponentDiagramRoute={id:crypto.randomUUID(),target:routeTarget,kind:routeKind,distance:routeDistance,breakDistance:routeBreak,angle:routeAngle,customRouteId:routeKind==="custom"?customRouteId||customRoutes[0]?.id:undefined};setDiagramRoutes(cur=>[...cur.filter(x=>x.target!==routeTarget),route]);onNotice(`${routeTarget}: ${routeKind==="custom"?customRoutes.find(x=>x.id===route.customRouteId)?.name||"Eigene Route":routeLabels[routeKind]} ins Gegnerdiagramm eingefügt.`)}
 function movePlayer(label:string,x:number,y:number){setDiagramPlayers(cur=>cur.map(p=>p.label===label?{...p,x,y}:p))}
 function resetClip(){setEditingClipId("");setTitle("");setVideoUrl("");setUnit("Offense");setQuarter("Q1");setClock("12:00");setDown(1);setDistance(10);setYards(0);setFieldHalf("own");setYardLine(25);setHash("Middle");setPersonnel("11");setFormation("Gun Trips Right");setMotion("None");setPlayType("Run");setConcept("");setResult("");setTags([]);setNotes("");setDiagramPlayers(opponentMarkers("Offense","Gun Trips Right"));setDiagramRoutes([]);setRouteTarget("WR1");if(localVideo)URL.revokeObjectURL(localVideo);setLocalVideo("")}
 function editClip(c:ScoutClip){setEditingClipId(c.id);setSelectedClipId(c.id);setTitle(c.title);setVideoUrl(c.videoUrl);setUnit(c.unit);setQuarter(c.quarter);setClock(c.gameClock);setDown(c.down);setDistance(c.distance);setYards(c.yardsGained);setFieldHalf(c.fieldHalf);setYardLine(c.yardLine);setHash(c.hash);setPersonnel(c.personnel);setFormation(c.formation);setMotion(c.motion);setPlayType(c.playType);setConcept(c.concept);setResult(c.result);setTags([...c.tags]);setNotes(c.notes);const players=c.diagramPlayers?.length?c.diagramPlayers:opponentMarkers(c.unit,c.formation);setDiagramPlayers(players.map(p=>({...p})));setDiagramRoutes((c.diagramRoutes??[]).map(r=>({...r,rawPath:r.rawPath?.map(p=>({...p}))})));setRouteTarget(players[0]?.label??"");onNotice(`„${c.title}“ ist zur Bearbeitung geladen.`)}
 async function saveClip(){const game=games.find(g=>g.id===gameId);if(!game||!title.trim())return onNotice("Spiel auswählen und Clip-Titel eintragen.");const previous=game.clips.find(c=>c.id===editingClipId);const clip:ScoutClip={id:previous?.id??crypto.randomUUID(),title:title.trim(),videoUrl,sourceFileName:previous?.sourceFileName??(localVideo?"Lokale Vorschau":""),unit,quarter,gameClock:clock,down:Math.max(1,Math.min(4,down)),distance:Math.max(1,Math.min(99,distance)),fieldHalf,yardLine:Math.max(1,Math.min(50,yardLine)),hash,personnel,formation,motion,playType,concept,result,yardsGained:yards,tags,notes,diagramPlayers,diagramRoutes,createdAt:previous?.createdAt??new Date().toISOString()};const next=games.map(g=>g.id===game.id?{...g,clips:[clip,...g.clips.filter(c=>c.id!==clip.id)].sort((a,b)=>a.quarter.localeCompare(b.quarter)||b.gameClock.localeCompare(a.gameClock))}:g);await persist(next);setSelectedClipId(clip.id);resetClip();onNotice(`Scouting-Clip „${clip.title}“ ${previous?"aktualisiert":"gespeichert"}.`)}
 async function deleteClip(id:string){const next=games.map(g=>g.id===gameId?{...g,clips:g.clips.filter(c=>c.id!==id)}:g);await persist(next);if(editingClipId===id)resetClip();if(selectedClipId===id){const game=next.find(g=>g.id===gameId);setSelectedClipId(game?.clips[0]?.id??"")}onNotice("Scouting-Sequenz entfernt.")}
 const seasons=useMemo(()=>[...new Set(games.map(g=>g.season))].sort((a,b)=>b-a),[games]),filteredGames=games.filter(g=>seasonFilter==="all"||String(g.season)===seasonFilter),game=(filteredGames.find(g=>g.id===gameId)||filteredGames[0]||games.find(g=>g.id===gameId)||games[0]||null),visibleClips=(game?.clips??[]).filter(c=>unitFilter==="All"||c.unit===unitFilter),selectedClip=visibleClips.find(c=>c.id===selectedClipId)||visibleClips[0]||null;
 const summary=useMemo(()=>{const clips=game?.clips??[],off=clips.filter(c=>c.unit==="Offense"),passes=off.filter(c=>["Pass","Screen","Play Action"].includes(c.playType)).length,average=off.length?Math.round(off.reduce((s,c)=>s+c.yardsGained,0)/off.length*10)/10:0;return{clips:clips.length,offense:off.length,passRate:off.length?Math.round(passes/off.length*100):0,average,topPersonnel:mostCommon(off.map(c=>c.personnel)),topFormation:mostCommon(off.map(c=>c.formation))}},[game]);
 const reviewPlayers=selectedClip?(selectedClip.diagramPlayers?.length?selectedClip.diagramPlayers:opponentMarkers(selectedClip.unit,selectedClip.formation)):[],reviewRoutes=selectedClip?.diagramRoutes??[];
 return <div className="pbs-grid">
  <AdminCard><div className="cms-section-head"><div><small>OPPONENT ARCHIVE</small><h2>Gegner & Spiele</h2></div></div><div className="pbs-route-form"><label>Saisonfilter<select value={seasonFilter} onChange={e=>{const value=e.target.value;setSeasonFilter(value);const first=games.find(g=>value==="all"||String(g.season)===value);if(first)selectGame(first.id)}}><option value="all">Alle Saisons</option>{seasons.map(s=><option key={s}>{s}</option>)}</select></label><label>Clip Unit<select value={unitFilter} onChange={e=>setUnitFilter(e.target.value)}><option>All</option><option>Offense</option><option>Defense</option><option>Special Teams</option></select></label></div><div className="pbs-scout-new"><input placeholder="Gegner" value={opponent} onChange={e=>setOpponent(e.target.value)}/><input type="date" value={gameDate} onChange={e=>{setGameDate(e.target.value);setGameSeason(Number(e.target.value.slice(0,4))||gameSeason)}}/><button className="cms-button" onClick={()=>void addGame()}>Spiel anlegen</button></div><div className="pbs-route-form"><label>Saison<input type="number" value={gameSeason} onChange={e=>setGameSeason(Number(e.target.value))}/></label><label>Wettbewerb<input value={competition} onChange={e=>setCompetition(e.target.value)}/></label><label>Ort<select value={location} onChange={e=>setLocation(e.target.value)}><option value="home">Heim</option><option value="away">Auswärts</option><option value="neutral">Neutral</option></select></label><label>Rascals<input type="number" min="0" value={rascalsScore} onChange={e=>setRascalsScore(Number(e.target.value))}/></label><label>Gegner<input type="number" min="0" value={opponentScore} onChange={e=>setOpponentScore(Number(e.target.value))}/></label></div><div className="pbs-game-list">{filteredGames.map(g=><button key={g.id} className={g.id===game?.id?"active":""} onClick={()=>selectGame(g.id)}><span><b>{g.opponent}</b><small>{g.date} · {g.competition} · {g.location}</small></span><em>{g.rascalsScore}:{g.opponentScore} · {g.clips.length} Clips</em></button>)}</div></AdminCard>
  <AdminCard className="pbs-scout-editor"><div className="cms-section-head"><div><small>FILM BREAKDOWN</small><h2>{editingClipId?"Sequenz bearbeiten":"Sequenz erfassen"}</h2></div>{editingClipId&&<button className="cms-button secondary" onClick={resetClip}>Neue Sequenz</button>}</div><label>Clip Titel<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Video URL / Cloudflare R2<input value={videoUrl} onChange={e=>setVideoUrl(e.target.value)}/></label><label>Lokale Datei · Sitzung<input type="file" accept="video/*" onChange={e=>{const file=e.target.files?.[0];if(localVideo)URL.revokeObjectURL(localVideo);setLocalVideo(file?URL.createObjectURL(file):"")}}/><small>Lokale Vorschau nur in dieser Sitzung; dauerhaft Video-URL/R2 verwenden.</small></label>{localVideo&&<video className="pbs-video" src={localVideo} controls/>}
   <div className="pbs-route-form"><label>Unit<select value={unit} onChange={e=>changeUnit(e.target.value)}><option>Offense</option><option>Defense</option><option>Special Teams</option></select></label><label>Quarter<select value={quarter} onChange={e=>setQuarter(e.target.value)}><option>Q1</option><option>Q2</option><option>Q3</option><option>Q4</option><option>OT</option></select></label><label>Clock<input value={clock} onChange={e=>setClock(e.target.value)}/></label><label>Down<input type="number" min="1" max="4" value={down} onChange={e=>setDown(Number(e.target.value))}/></label><label>Distance<input type="number" min="1" max="99" value={distance} onChange={e=>setDistance(Number(e.target.value))}/></label><label>Yards<input type="number" min="-99" max="99" value={yards} onChange={e=>setYards(Number(e.target.value))}/></label></div>
   <label>Formation<select value={formation} onChange={e=>changeFormation(e.target.value)}>{(scoutFormationOptions[unit]??[]).map(f=><option key={f}>{f}</option>)}</select></label><div className="pbs-route-form"><label>Personnel<input value={personnel} onChange={e=>setPersonnel(e.target.value)}/></label><label>Motion<select value={motion} onChange={e=>setMotion(e.target.value)}><option>None</option><option>Jet</option><option>Orbit</option><option>Return</option><option>Shift</option><option>Trade</option></select></label><label>Result<input value={result} onChange={e=>setResult(e.target.value)}/></label><label>Feldseite<select value={fieldHalf} onChange={e=>setFieldHalf(e.target.value as "own"|"opponent")}><option value="own">Own</option><option value="opponent">Opponent</option></select></label><label>Yard Line<input type="number" min="1" max="50" value={yardLine} onChange={e=>setYardLine(Number(e.target.value))}/></label><label>Hash<select value={hash} onChange={e=>setHash(e.target.value as "Left"|"Middle"|"Right")}><option>Left</option><option>Middle</option><option>Right</option></select></label></div>
   <label>Play Type<select value={playType} onChange={e=>setPlayType(e.target.value)}><option>Run</option><option>Pass</option><option>RPO</option><option>Screen</option><option>Play Action</option><option>Pressure</option><option>Coverage</option><option>Special Teams</option></select></label><label>Concept<input value={concept} onChange={e=>setConcept(e.target.value)}/></label><div className="pbs-tag-picker">{scoutTags.map(tag=><button type="button" key={tag} className={tags.includes(tag)?"active":""} onClick={()=>setTags(cur=>cur.includes(tag)?cur.filter(x=>x!==tag):[...cur,tag])}>{tag}</button>)}</div>
   <ScoutField players={diagramPlayers} routes={diagramRoutes} customRoutes={customRoutes} onMove={movePlayer}/><div className="pbs-route-form"><label>Diagram Target<select value={routeTarget} onChange={e=>setRouteTarget(e.target.value)}>{diagramPlayers.map(p=><option key={p.id}>{p.label}</option>)}</select></label><label>Route<select value={routeKind} onChange={e=>setRouteKind(e.target.value as RouteKind)}>{Object.entries(routeLabels).map(([k,l])=><option value={k} key={k}>{l}</option>)}</select></label>{routeKind==="custom"?<label>Eigene Route<select value={customRouteId} onChange={e=>setCustomRouteId(e.target.value)}>{customRoutes.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label>:<><label>Stem<input type="number" min="1" max="40" value={routeDistance} onChange={e=>setRouteDistance(Number(e.target.value))}/></label><label>Break<input type="number" min="1" max="25" value={routeBreak} onChange={e=>setRouteBreak(Number(e.target.value))}/></label><label>Winkel<input type="number" min="15" max="90" value={routeAngle} onChange={e=>setRouteAngle(Number(e.target.value))}/></label></>}<button className="cms-button secondary" type="button" onClick={addRoute}>Route / Assignment</button></div>{diagramRoutes.length>0&&<div className="pbs-route-list">{diagramRoutes.map(r=><button key={r.id} onClick={()=>setDiagramRoutes(cur=>cur.filter(x=>x.id!==r.id))}>{r.target} · {r.kind==="custom"?customRoutes.find(x=>x.id===r.customRouteId)?.name||"Eigene Route":routeLabels[r.kind]} <b>×</b></button>)}</div>}
   <label>Coach Notes<textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="cms-button" onClick={()=>void saveClip()}>{editingClipId?"Änderungen speichern":"Sequenz speichern"}</button>
  </AdminCard>
  <AdminCard className="pbs-scout-review"><div className="cms-section-head"><div><small>SCOUTING KPIS</small><h2>{game?`Rascals gegen ${game.opponent}`:"Gegner wählen"}</h2></div>{game&&<strong>{game.rascalsScore}:{game.opponentScore}</strong>}</div><div className="pbs-scout-kpis five"><span><small>Erfasste Spiele</small><b>{games.length}</b><em>{seasons.length} Saisons</em></span><span><small>Clips dieses Spiels</small><b>{summary.clips}</b><em>{summary.offense} Offense</em></span><span><small>Pass Rate</small><b>{summary.passRate}%</b><em>Offense Snaps</em></span><span><small>Top Personnel</small><b>{summary.topPersonnel}</b><em>{summary.topFormation}</em></span><span><small>Ø Gain</small><b>{summary.average}</b><em>Yards / Offense Clip</em></span></div>
   {selectedClip?<><div className="pbs-scout-viewer"><div className="pbs-video-pane">{selectedClip.videoUrl?<video controls src={selectedClip.videoUrl}/>:<div><b>VIDEO BREAKDOWN</b><span>{selectedClip.sourceFileName||"Noch kein Video-Link hinterlegt"}</span><small>{selectedClip.quarter} · {selectedClip.gameClock}</small></div>}</div><ScoutField players={reviewPlayers} routes={reviewRoutes} customRoutes={customRoutes} onMove={()=>{}}/></div><div className="pbs-clip-breakdown"><div><small>{selectedClip.unit}</small><h3>{selectedClip.title}</h3><p>{selectedClip.notes||"Keine Coach Notes hinterlegt."}</p></div><dl><div><dt>Situation</dt><dd>{selectedClip.down}. & {selectedClip.distance}</dd></div><div><dt>Ball</dt><dd>{selectedClip.fieldHalf==="own"?"Own":"Opp"} {selectedClip.yardLine}</dd></div><div><dt>Personnel</dt><dd>{selectedClip.personnel}</dd></div><div><dt>Formation</dt><dd>{selectedClip.formation}</dd></div><div><dt>Motion</dt><dd>{selectedClip.motion}</dd></div><div><dt>Concept</dt><dd>{selectedClip.concept||"–"}</dd></div><div><dt>Result</dt><dd>{selectedClip.result||`${selectedClip.yardsGained} Yards`}</dd></div><div><dt>Tags</dt><dd>{selectedClip.tags.join(" · ")||"–"}</dd></div></dl><button className="cms-button secondary" onClick={()=>editClip(selectedClip)}>Im Editor bearbeiten</button></div></>:<p className="cms-muted">Noch keine Filmsequenz für dieses Spiel.</p>}
   <div className="pbs-clip-filter">{["All","Offense","Defense","Special Teams"].map(filter=><button key={filter} className={unitFilter===filter?"active":""} onClick={()=>setUnitFilter(filter)}>{filter==="All"?"Alle":filter}</button>)}</div><div className="pbs-clip-list">{visibleClips.map(c=><article className={c.id===selectedClip?.id?"selected":""} key={c.id}><span><b>{c.title}</b><small>{c.quarter} {c.gameClock} · {c.down}.&{c.distance} · {c.formation}</small></span><em>{c.playType} · {c.yardsGained}Y</em><p>{c.concept}{c.notes?` · ${c.notes}`:""}</p>{c.tags.length>0&&<small>{c.tags.join(" · ")}</small>}{c.videoUrl&&<a href={c.videoUrl} target="_blank" rel="noreferrer">Video öffnen ↗</a>}<div className="pbs-clip-actions"><button onClick={()=>setSelectedClipId(c.id)}>Öffnen</button><button onClick={()=>editClip(c)}>Bearbeiten</button><button onClick={()=>void deleteClip(c.id)}>Entfernen</button></div></article>)}</div></AdminCard>
 </div>
}

function mostCommon(values:string[]){if(!values.length)return"–";const counts=new Map<string,number>();for(const value of values.filter(Boolean))counts.set(value,(counts.get(value)??0)+1);return[...counts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]??"–"}