"use client";

import { useEffect,useMemo,useState } from "react";
import { AdminCard,AdminNotice,AdminShell } from "../_components/AdminShell";
import "./playbook.css";

type Season={id:string;year:number;name:string;isCurrent:boolean};
type Formation={id:string;name:string;personnel:string;description:string;tags:string};
type Assignment={id:string;positionLabel:string;playerId:string|null;role:string;assignment:string;technique:string;keyRead:string;x:number;y:number;endX:number|null;endY:number|null;visualType:string};
type Play={id:string;formationId:string|null;formationName:string;unit:string;name:string;concept:string;callName:string;situation:string;objective:string;coachingPoints:string;status:string;version:number;updatedAt:string;assignments:Assignment[]};
type Player={id:string;jerseyNumber:number|null;firstName:string;lastName:string;primaryPosition:string;secondaryPosition:string;unit:string};
type Payload={seasons:Season[];season:Season;unit:string;formations:Formation[];plays:Play[];roster:Player[]};
type Unit="offense"|"defense"|"special-teams";

const defaults:Record<Unit,Array<{p:string;x:number;y:number}>>={
 offense:[{p:"LT",x:34,y:62},{p:"LG",x:42,y:62},{p:"C",x:50,y:62},{p:"RG",x:58,y:62},{p:"RT",x:66,y:62},{p:"X",x:13,y:58},{p:"Z",x:87,y:58},{p:"Y",x:74,y:58},{p:"QB",x:50,y:73},{p:"RB",x:50,y:84},{p:"H",x:27,y:67}],
 defense:[{p:"DE",x:34,y:43},{p:"DT",x:43,y:43},{p:"DT",x:57,y:43},{p:"DE",x:66,y:43},{p:"WILL",x:39,y:31},{p:"MIKE",x:50,y:29},{p:"SAM",x:61,y:31},{p:"CB",x:14,y:25},{p:"FS",x:50,y:13},{p:"SS",x:72,y:17},{p:"CB",x:86,y:25}],
 "special-teams":[{p:"LS",x:50,y:55},{p:"P",x:50,y:78},{p:"L1",x:20,y:50},{p:"L2",x:30,y:50},{p:"L3",x:40,y:50},{p:"R1",x:80,y:50},{p:"R2",x:70,y:50},{p:"R3",x:60,y:50},{p:"GUN L",x:8,y:48},{p:"GUN R",x:92,y:48},{p:"PP",x:50,y:68}]
};

export function PlaybookManager(){
 const[data,setData]=useState<Payload|null>(null),[seasonId,setSeasonId]=useState(""),[unit,setUnit]=useState<Unit>("defense"),[playId,setPlayId]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const[name,setName]=useState(""),[formationId,setFormationId]=useState(""),[concept,setConcept]=useState(""),[callName,setCallName]=useState(""),[situation,setSituation]=useState(""),[objective,setObjective]=useState(""),[coachingPoints,setCoachingPoints]=useState(""),[assignments,setAssignments]=useState<Assignment[]>([]);
 useEffect(()=>{void load()},[]);
 async function load(sid?:string,u:Unit=unit,keep?:string){setLoading(true);setNotice("");try{const p=new URLSearchParams();if(sid)p.set("seasonId",sid);p.set("unit",u);const r=await fetch(`/admin/api/playbook?${p}`);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||"Playbook konnte nicht geladen werden.")}const b=await r.json() as Payload;setData(b);setSeasonId(b.season.id);setUnit(u);const selected=b.plays.find(x=>x.id===keep)||b.plays[0]||null;if(selected)selectPlay(selected);else resetEditor()}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 function resetEditor(){setPlayId("");setName("");setFormationId("");setConcept("");setCallName("");setSituation("");setObjective("");setCoachingPoints("");setAssignments([])}
 function selectPlay(p:Play){setPlayId(p.id);setName(p.name);setFormationId(p.formationId||"");setConcept(p.concept);setCallName(p.callName);setSituation(p.situation);setObjective(p.objective);setCoachingPoints(p.coachingPoints);setAssignments(p.assignments.map(a=>({...a})))}
 async function changeUnit(u:Unit){setUnit(u);setPlayId("");await load(seasonId,u)}
 async function createFormation(){const n=prompt("Formationsname:",unit==="defense"?"4-2-5":"Trips Right");if(!n)return;const personnel=prompt("Personnel / Package:",unit==="defense"?"4 DL · 2 LB · 5 DB":"11 Personnel")||"";setSaving(true);try{const r=await fetch("/admin/api/playbook",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-formation",seasonId,unit,name:n,personnel})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Formation konnte nicht erstellt werden.");await load(seasonId,unit,playId);setFormationId(b.id);setNotice("Formation angelegt.")}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Anlegen.")}finally{setSaving(false)}}
 async function createPlay(){if(!seasonId)return;const n=prompt("Playname:",unit==="defense"?"Cover 3 Sky":"Inside Zone");if(!n)return;setSaving(true);try{const r=await fetch("/admin/api/playbook",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-play",seasonId,unit,formationId:formationId||null,name:n})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Play konnte nicht erstellt werden.");await load(seasonId,unit,b.id);setAssignments(defaults[unit].map((d,i)=>({id:crypto.randomUUID(),positionLabel:d.p,playerId:null,role:"",assignment:"",technique:"",keyRead:"",x:d.x,y:d.y,endX:null,endY:null,visualType:"stationary"})));setNotice("Play angelegt. Positionen können jetzt auf dem Feld bearbeitet werden.")}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Anlegen.")}finally{setSaving(false)}}
 async function save(publish=false){if(!playId)return;setSaving(true);try{const r=await fetch("/admin/api/playbook",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:publish?"publish-play":"save-play",playId,formationId:formationId||null,name,concept,callName,situation,objective,coachingPoints,assignments})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Speichern fehlgeschlagen.");await load(seasonId,unit,playId);setNotice(publish?`Play veröffentlicht · Version ${b.version}.`:`Play gespeichert · Version ${b.version}.`)}catch(e){setNotice(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setSaving(false)}}
 function patch(id:string,p:Partial<Assignment>){setAssignments(cur=>cur.map(a=>a.id===id?{...a,...p}:a))}
 function addAssignment(){setAssignments(cur=>[...cur,{id:crypto.randomUUID(),positionLabel:"POS",playerId:null,role:"",assignment:"",technique:"",keyRead:"",x:50,y:50,endX:null,endY:null,visualType:"stationary"}])}
 const selected=data?.plays.find(p=>p.id===playId)||null;
 const rosterById=useMemo(()=>new Map((data?.roster??[]).map(p=>[p.id,p])),[data]);
 return <AdminShell active="playbook" title="Playbook & Scheme" eyebrow="RASCALS OS · SCHEME CENTER" actions={<><button className="cms-button secondary" onClick={()=>void createFormation()} disabled={saving}>＋ Formation</button><button className="cms-button secondary" onClick={()=>void createPlay()} disabled={saving}>＋ Play</button>{playId&&<button className="cms-button" onClick={()=>void save(false)} disabled={saving}>Speichern</button>}{playId&&<button className="cms-button" onClick={()=>void save(true)} disabled={saving}>Veröffentlichen</button>}</>}>
  {notice&&<AdminNotice tone={notice.includes("fehl")||notice.includes("Fehler")?"error":"success"}>{notice}</AdminNotice>}
  <AdminCard className="pb-head"><div><small>SCHEME WORKSPACE</small><h2>Formation → Concept → Play → Assignment</h2><p>Aufstellungen, individuelle Aufgaben und Scheme Coaching Points werden visuell auf dem Football-Feld gepflegt und versioniert.</p></div><div className="pb-selectors"><label><span>Saison</span><select value={seasonId} onChange={e=>void load(e.target.value,unit)}>{data?.seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="pb-unit-tabs">{(["offense","defense","special-teams"] as Unit[]).map(u=><button key={u} className={unit===u?"active":""} onClick={()=>void changeUnit(u)}>{u==="special-teams"?"SPECIAL TEAMS":u.toUpperCase()}</button>)}</div></div></AdminCard>
  {loading?<AdminCard>Playbook wird geladen…</AdminCard>:<div className="pb-layout">
   <aside><AdminCard><div className="cms-section-head"><div><small>PLAYS</small><h2>{unit==="special-teams"?"Special Teams":unit[0].toUpperCase()+unit.slice(1)}</h2></div></div><div className="pb-play-list">{data?.plays.map(p=><button key={p.id} className={playId===p.id?"active":""} onClick={()=>selectPlay(p)}><span><b>{p.name}</b><small>{p.formationName||"Keine Formation"} · {p.concept||"Concept offen"}</small></span><em>{p.status.toUpperCase()} · V{p.version}</em></button>)}{!data?.plays.length&&<p className="cms-muted">Noch keine Plays vorhanden.</p>}</div></AdminCard></aside>
   <main>{!playId?<AdminCard><h2>Erstes Play anlegen</h2><p className="cms-muted">Lege zuerst eine Formation und anschließend ein Play an. Das Feld kann danach positionsgenau aufgebaut werden.</p></AdminCard>:<>
    <AdminCard><div className="pb-form"><label><span>Play Name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Formation</span><select value={formationId} onChange={e=>setFormationId(e.target.value)}><option value="">— keine —</option>{data?.formations.map(f=><option key={f.id} value={f.id}>{f.name}{f.personnel?` · ${f.personnel}`:""}</option>)}</select></label><label><span>Concept</span><input value={concept} onChange={e=>setConcept(e.target.value)} placeholder="z. B. Cover 3 / Inside Zone"/></label><label><span>Call</span><input value={callName} onChange={e=>setCallName(e.target.value)} placeholder="Sideline / Huddle Call"/></label><label><span>Situation</span><input value={situation} onChange={e=>setSituation(e.target.value)} placeholder="1st & 10 · Red Zone · 3rd & Long"/></label><label className="wide"><span>Objective</span><input value={objective} onChange={e=>setObjective(e.target.value)}/></label></div></AdminCard>
    <AdminCard><div className="cms-section-head"><div><small>VISUAL BOARD</small><h2>{selected?.formationName||"Formation"} · {name}</h2></div><button className="cms-button secondary" onClick={addAssignment}>＋ Position</button></div><div className={`pb-field ${unit}`}><div className="pb-los"/>{assignments.map(a=><div key={a.id} className="pb-player" style={{left:`${a.x}%`,top:`${a.y}%`}} title={a.assignment}><button>{a.positionLabel}</button>{a.endX!=null&&a.endY!=null&&<svg className="pb-route" viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="50" y1="50" x2={50+(a.endX-a.x)} y2={50+(a.endY-a.y)} /></svg>}</div>)}</div><p className="cms-muted">Positionen werden in normalisierten Feldkoordinaten gespeichert. So bleibt die Darstellung auf Desktop, Tablet und Mobile konsistent.</p></AdminCard>
    <AdminCard><div className="cms-section-head"><div><small>ASSIGNMENTS</small><h2>Positionen & Aufgaben</h2></div></div><div className="pb-assignments">{assignments.map((a,i)=>{const player=a.playerId?rosterById.get(a.playerId):null;return <article key={a.id}><b>{i+1}</b><input value={a.positionLabel} onChange={e=>patch(a.id,{positionLabel:e.target.value})}/><select value={a.playerId||""} onChange={e=>patch(a.id,{playerId:e.target.value||null})}><option value="">Depth-Chart Position</option>{data?.roster.map(p=><option key={p.id} value={p.id}>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName} · {p.primaryPosition}</option>)}</select><input placeholder="Role" value={a.role} onChange={e=>patch(a.id,{role:e.target.value})}/><input placeholder="Assignment" value={a.assignment} onChange={e=>patch(a.id,{assignment:e.target.value})}/><input placeholder="Key / Read" value={a.keyRead} onChange={e=>patch(a.id,{keyRead:e.target.value})}/><div className="coords"><input type="number" min={0} max={100} value={a.x} onChange={e=>patch(a.id,{x:Number(e.target.value)})}/><input type="number" min={0} max={100} value={a.y} onChange={e=>patch(a.id,{y:Number(e.target.value)})}/></div>{player&&<small>Aktuell: #{player.jerseyNumber??"–"} {player.firstName} {player.lastName}</small>}</article>})}</div></AdminCard>
    <AdminCard><label className="pb-notes"><span>Scheme Coaching Points</span><textarea rows={4} value={coachingPoints} onChange={e=>setCoachingPoints(e.target.value)} placeholder="Alignment · keys · leverage · communication · checks · finish"/></label></AdminCard>
   </>}</main>
  </div>}
 </AdminShell>
}
