"use client";

import { useEffect,useMemo,useRef,useState } from "react";
import { AdminCard,AdminNotice,AdminShell } from "../_components/AdminShell";
import "./playbook.css";

type Point={x:number;y:number};
type Season={id:string;year:number;name:string;isCurrent:boolean};
type Formation={id:string;name:string;personnel:string;description:string;tags:string};
type Assignment={id:string;positionLabel:string;playerId:string|null;role:string;assignment:string;technique:string;keyRead:string;x:number;y:number;endX:number|null;endY:number|null;visualType:string;path:Point[];preSnapPath:Point[];zoneWidth:number;zoneHeight:number};
type Play={id:string;formationId:string|null;formationName:string;unit:string;name:string;concept:string;callName:string;situation:string;objective:string;coachingPoints:string;strengthCall:string;frontCall:string;coverageCall:string;checksAlerts:string;status:string;version:number;updatedAt:string;assignments:Assignment[]};
type Player={id:string;jerseyNumber:number|null;firstName:string;lastName:string;primaryPosition:string;secondaryPosition:string;unit:string};
type Payload={seasons:Season[];season:Season;unit:string;formations:Formation[];plays:Play[];roster:Player[]};
type Unit="offense"|"defense"|"special-teams";
type VisualType="stationary"|"route"|"motion"|"blitz"|"fit"|"zone"|"man"|"block";
type DrawMode="none"|"post"|"presnap"|"zone";

const defaults:Record<Unit,Array<{p:string;x:number;y:number}>>={
 offense:[{p:"LT",x:34,y:62},{p:"LG",x:42,y:62},{p:"C",x:50,y:62},{p:"RG",x:58,y:62},{p:"RT",x:66,y:62},{p:"X",x:13,y:58},{p:"Z",x:87,y:58},{p:"Y",x:74,y:58},{p:"QB",x:50,y:73},{p:"RB",x:50,y:84},{p:"H",x:27,y:67}],
 defense:[{p:"DE",x:34,y:43},{p:"DT",x:43,y:43},{p:"DT",x:57,y:43},{p:"DE",x:66,y:43},{p:"WILL",x:39,y:31},{p:"MIKE",x:50,y:29},{p:"SAM",x:61,y:31},{p:"CB",x:14,y:25},{p:"FS",x:50,y:13},{p:"SS",x:72,y:17},{p:"CB",x:86,y:25}],
 "special-teams":[{p:"LS",x:50,y:55},{p:"P",x:50,y:78},{p:"L1",x:20,y:50},{p:"L2",x:30,y:50},{p:"L3",x:40,y:50},{p:"R1",x:80,y:50},{p:"R2",x:70,y:50},{p:"R3",x:60,y:50},{p:"GUN L",x:8,y:48},{p:"GUN R",x:92,y:48},{p:"PP",x:50,y:68}]
};
const visualTypes:Array<{value:VisualType;label:string}>=[{value:"stationary",label:"Stationary"},{value:"route",label:"Route"},{value:"motion",label:"Motion"},{value:"blitz",label:"Blitz"},{value:"fit",label:"Run Fit"},{value:"zone",label:"Coverage Zone"},{value:"man",label:"Man Assignment"},{value:"block",label:"Block"}];
const emptyAssignment=(p="POS",x=50,y=50):Assignment=>({id:crypto.randomUUID(),positionLabel:p,playerId:null,role:"",assignment:"",technique:"",keyRead:"",x,y,endX:null,endY:null,visualType:"stationary",path:[],preSnapPath:[],zoneWidth:12,zoneHeight:12});

export function PlaybookManager(){
 const[data,setData]=useState<Payload|null>(null),[seasonId,setSeasonId]=useState(""),[unit,setUnit]=useState<Unit>("defense"),[playId,setPlayId]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const[name,setName]=useState(""),[formationId,setFormationId]=useState(""),[concept,setConcept]=useState(""),[callName,setCallName]=useState(""),[situation,setSituation]=useState(""),[objective,setObjective]=useState(""),[coachingPoints,setCoachingPoints]=useState("");
 const[strengthCall,setStrengthCall]=useState(""),[frontCall,setFrontCall]=useState(""),[coverageCall,setCoverageCall]=useState(""),[checksAlerts,setChecksAlerts]=useState(""),[assignments,setAssignments]=useState<Assignment[]>([]);
 const[selectedAssignmentId,setSelectedAssignmentId]=useState(""),[drawMode,setDrawMode]=useState<DrawMode>("none");
 const fieldRef=useRef<HTMLDivElement|null>(null),dragRef=useRef<string|null>(null);
 useEffect(()=>{void load()},[]);

 async function load(sid?:string,u:Unit=unit,keep?:string){setLoading(true);setNotice("");try{const p=new URLSearchParams();if(sid)p.set("seasonId",sid);p.set("unit",u);const r=await fetch(`/admin/api/playbook?${p}`);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||"Playbook konnte nicht geladen werden.")}const b=await r.json() as Payload;setData(b);setSeasonId(b.season.id);setUnit(u);const selected=b.plays.find(x=>x.id===keep)||b.plays[0]||null;if(selected)selectPlay(selected);else resetEditor()}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 function resetEditor(){setPlayId("");setName("");setFormationId("");setConcept("");setCallName("");setSituation("");setObjective("");setCoachingPoints("");setStrengthCall("");setFrontCall("");setCoverageCall("");setChecksAlerts("");setAssignments([]);setSelectedAssignmentId("");setDrawMode("none")}
 function selectPlay(p:Play){setPlayId(p.id);setName(p.name);setFormationId(p.formationId||"");setConcept(p.concept);setCallName(p.callName);setSituation(p.situation);setObjective(p.objective);setCoachingPoints(p.coachingPoints);setStrengthCall(p.strengthCall||"");setFrontCall(p.frontCall||"");setCoverageCall(p.coverageCall||"");setChecksAlerts(p.checksAlerts||"");setAssignments(p.assignments.map(a=>({...a,path:[...(a.path||[])],preSnapPath:[...(a.preSnapPath||[])],zoneWidth:a.zoneWidth||12,zoneHeight:a.zoneHeight||12})));setSelectedAssignmentId(p.assignments[0]?.id||"");setDrawMode("none")}
 async function changeUnit(u:Unit){setUnit(u);setPlayId("");await load(seasonId,u)}
 async function createFormation(){const n=prompt("Formationsname:",unit==="defense"?"4-2-5":"Trips Right");if(!n)return;const personnel=prompt("Personnel / Package:",unit==="defense"?"4 DL · 2 LB · 5 DB":"11 Personnel")||"";setSaving(true);try{const r=await fetch("/admin/api/playbook",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-formation",seasonId,unit,name:n,personnel})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Formation konnte nicht erstellt werden.");await load(seasonId,unit,playId);setFormationId(b.id);setNotice("Formation angelegt.")}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Anlegen.")}finally{setSaving(false)}}
 async function createPlay(){if(!seasonId)return;const n=prompt("Playname:",unit==="defense"?"Cover 3 Sky":"Inside Zone");if(!n)return;setSaving(true);try{const r=await fetch("/admin/api/playbook",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-play",seasonId,unit,formationId:formationId||null,name:n})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Play konnte nicht erstellt werden.");await load(seasonId,unit,b.id);const seeded=defaults[unit].map(d=>emptyAssignment(d.p,d.x,d.y));setAssignments(seeded);setSelectedAssignmentId(seeded[0]?.id||"");setNotice("Play angelegt. Positionen und Bewegungen können jetzt direkt auf dem Feld bearbeitet werden.")}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Anlegen.")}finally{setSaving(false)}}
 async function save(publish=false){if(!playId)return;setSaving(true);try{const r=await fetch("/admin/api/playbook",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:publish?"publish-play":"save-play",playId,formationId:formationId||null,name,concept,callName,situation,objective,coachingPoints,strengthCall,frontCall,coverageCall,checksAlerts,assignments})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||"Speichern fehlgeschlagen.");await load(seasonId,unit,playId);setNotice(publish?`Play veröffentlicht · Version ${b.version}.`:`Play gespeichert · Version ${b.version}.`)}catch(e){setNotice(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setSaving(false)}}
 function patch(id:string,p:Partial<Assignment>){setAssignments(cur=>cur.map(a=>a.id===id?{...a,...p}:a))}
 function addAssignment(){const a=emptyAssignment();setAssignments(cur=>[...cur,a]);setSelectedAssignmentId(a.id)}
 function removeAssignment(id:string){setAssignments(cur=>cur.filter(a=>a.id!==id));if(selectedAssignmentId===id)setSelectedAssignmentId("")}
 function pointFromEvent(clientX:number,clientY:number){const rect=fieldRef.current?.getBoundingClientRect();if(!rect)return null;return{x:Math.max(0,Math.min(100,((clientX-rect.left)/rect.width)*100)),y:Math.max(0,Math.min(100,((clientY-rect.top)/rect.height)*100))}}
 function startDrag(id:string,e:React.PointerEvent<HTMLButtonElement>){if(drawMode!=="none")return;e.preventDefault();e.stopPropagation();dragRef.current=id;setSelectedAssignmentId(id);e.currentTarget.setPointerCapture(e.pointerId)}
 function moveDrag(e:React.PointerEvent<HTMLDivElement>){if(!dragRef.current)return;const p=pointFromEvent(e.clientX,e.clientY);if(p)patch(dragRef.current,{x:Math.round(p.x*10)/10,y:Math.round(p.y*10)/10})}
 function endDrag(){dragRef.current=null}
 function fieldClick(e:React.MouseEvent<HTMLDivElement>){if(drawMode==="none"||!selectedAssignmentId)return;const p=pointFromEvent(e.clientX,e.clientY);if(!p)return;const point={x:Math.round(p.x*10)/10,y:Math.round(p.y*10)/10};const a=assignments.find(x=>x.id===selectedAssignmentId);if(!a)return;if(drawMode==="post"){patch(a.id,{path:[...(a.path||[]),point],endX:point.x,endY:point.y})}else if(drawMode==="presnap"){patch(a.id,{preSnapPath:[...(a.preSnapPath||[]),point]})}else if(drawMode==="zone"){patch(a.id,{endX:point.x,endY:point.y,zoneWidth:Math.max(4,Math.abs(point.x-a.x)*2),zoneHeight:Math.max(4,Math.abs(point.y-a.y)*2)})}}
 function undoPoint(kind:"post"|"presnap"){const a=assignments.find(x=>x.id===selectedAssignmentId);if(!a)return;if(kind==="post"){const next=(a.path||[]).slice(0,-1),last=next[next.length-1];patch(a.id,{path:next,endX:last?.x??null,endY:last?.y??null})}else patch(a.id,{preSnapPath:(a.preSnapPath||[]).slice(0,-1)})}
 function clearVisual(){const a=assignments.find(x=>x.id===selectedAssignmentId);if(a)patch(a.id,{path:[],preSnapPath:[],endX:null,endY:null,zoneWidth:12,zoneHeight:12})}
 const selected=data?.plays.find(p=>p.id===playId)||null,selectedAssignment=assignments.find(a=>a.id===selectedAssignmentId)||null;
 const rosterById=useMemo(()=>new Map((data?.roster??[]).map(p=>[p.id,p])),[data]);

 return <AdminShell active="playbook" title="Playbook & Scheme" eyebrow="RASCALS OS · SCHEME CENTER" actions={<><button className="cms-button secondary" onClick={()=>void createFormation()} disabled={saving}>＋ Formation</button><button className="cms-button secondary" onClick={()=>void createPlay()} disabled={saving}>＋ Play</button>{playId&&<button className="cms-button" onClick={()=>void save(false)} disabled={saving}>Speichern</button>}{playId&&<button className="cms-button" onClick={()=>void save(true)} disabled={saving}>Veröffentlichen</button>}</>}>
  {notice&&<AdminNotice tone={notice.includes("fehl")||notice.includes("Fehler")?"error":"success"}>{notice}</AdminNotice>}
  <AdminCard className="pb-head"><div><small>SCHEME WORKSPACE</small><h2>Formation → Concept → Play → Assignment</h2><p>Mehrsegmentige Routes, Pre-Snap Motion, Blitzes, Run Fits, Coverage Zones, Calls und Checks werden in einem gemeinsamen Board gepflegt.</p></div><div className="pb-selectors"><label><span>Saison</span><select value={seasonId} onChange={e=>void load(e.target.value,unit)}>{data?.seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="pb-unit-tabs">{(["offense","defense","special-teams"] as Unit[]).map(u=><button key={u} className={unit===u?"active":""} onClick={()=>void changeUnit(u)}>{u==="special-teams"?"SPECIAL TEAMS":u.toUpperCase()}</button>)}</div></div></AdminCard>
  {loading?<AdminCard>Playbook wird geladen…</AdminCard>:<div className="pb-layout"><aside><AdminCard><div className="cms-section-head"><div><small>PLAYS</small><h2>{unit==="special-teams"?"Special Teams":unit[0].toUpperCase()+unit.slice(1)}</h2></div></div><div className="pb-play-list">{data?.plays.map(p=><button key={p.id} className={playId===p.id?"active":""} onClick={()=>selectPlay(p)}><span><b>{p.name}</b><small>{p.formationName||"Keine Formation"} · {p.concept||"Concept offen"}</small></span><em>{p.status.toUpperCase()} · V{p.version}</em></button>)}{!data?.plays.length&&<p className="cms-muted">Noch keine Plays vorhanden.</p>}</div></AdminCard></aside>
   <main>{!playId?<AdminCard><h2>Erstes Play anlegen</h2><p className="cms-muted">Lege zuerst eine Formation und anschließend ein Play an.</p></AdminCard>:<>
    <AdminCard><div className="pb-form"><label><span>Play Name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Formation</span><select value={formationId} onChange={e=>setFormationId(e.target.value)}><option value="">— keine —</option>{data?.formations.map(f=><option key={f.id} value={f.id}>{f.name}{f.personnel?` · ${f.personnel}`:""}</option>)}</select></label><label><span>Concept</span><input value={concept} onChange={e=>setConcept(e.target.value)}/></label><label><span>Call</span><input value={callName} onChange={e=>setCallName(e.target.value)}/></label><label><span>Strength Call</span><input value={strengthCall} onChange={e=>setStrengthCall(e.target.value)} placeholder="Field / Boundary / TE / Passing Strength"/></label><label><span>Front Call</span><input value={frontCall} onChange={e=>setFrontCall(e.target.value)} placeholder="Over · Under · Odd · Mint"/></label><label><span>Coverage Call</span><input value={coverageCall} onChange={e=>setCoverageCall(e.target.value)} placeholder="Cover 3 Buzz · Quarters · Match"/></label><label><span>Situation</span><input value={situation} onChange={e=>setSituation(e.target.value)} /></label><label className="wide"><span>Checks & Alerts</span><textarea rows={2} value={checksAlerts} onChange={e=>setChecksAlerts(e.target.value)} placeholder="Motion check · Trips alert · Empty adjustment · Red-zone check"/></label><label className="wide"><span>Objective</span><input value={objective} onChange={e=>setObjective(e.target.value)}/></label></div></AdminCard>
    <AdminCard><div className="cms-section-head"><div><small>INTERACTIVE VISUAL BOARD</small><h2>{selected?.formationName||"Formation"} · {name}</h2></div><div className="pb-board-actions"><span>{drawMode==="post"?"Post-Snap: Punkte nacheinander ins Feld klicken":drawMode==="presnap"?"Pre-Snap Motion: Punkte nacheinander klicken":drawMode==="zone"?"Zone-Ziel anklicken":"Spieler ziehen · Slot auswählen"}</span><button className="cms-button secondary" onClick={addAssignment}>＋ Position</button></div></div>
      <div ref={fieldRef} className={`pb-field ${unit} ${drawMode!=="none"?"target-mode":""}`} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag} onClick={fieldClick}><div className="pb-los"/><svg className="pb-overlay" viewBox="0 0 100 100" preserveAspectRatio="none">{assignments.map(a=><VisualMark key={a.id} assignment={a} selected={a.id===selectedAssignmentId}/>)}</svg>{assignments.map(a=><div key={a.id} className={`pb-player ${a.id===selectedAssignmentId?"selected":""}`} style={{left:`${a.x}%`,top:`${a.y}%`}}><button onPointerDown={e=>startDrag(a.id,e)} onClick={e=>{e.stopPropagation();setSelectedAssignmentId(a.id)}}>{a.positionLabel}</button>{a.playerId&&<small>#{rosterById.get(a.playerId)?.jerseyNumber??"–"}</small>}</div>)}</div>
      <div className="pb-legend"><span><i className="route"/> Route</span><span><i className="motion"/> Pre-Snap</span><span><i className="blitz"/> Blitz</span><span><i className="fit"/> Run Fit</span><span><i className="zone"/> Zone</span><span><i className="man"/> Man</span><span><i className="block"/> Block</span></div>
      {selectedAssignment&&<div className="pb-selected-tools"><div><small>SELECTED</small><b>{selectedAssignment.positionLabel}</b></div><label><span>Visual</span><select value={selectedAssignment.visualType} onChange={e=>patch(selectedAssignment.id,{visualType:e.target.value})}>{visualTypes.map(v=><option key={v.value} value={v.value}>{v.label}</option>)}</select></label><button className={drawMode==="presnap"?"active":""} onClick={()=>setDrawMode(drawMode==="presnap"?"none":"presnap")}>Pre-Snap Motion</button><button className={drawMode==="post"?"active":""} onClick={()=>setDrawMode(drawMode==="post"?"none":"post")} disabled={selectedAssignment.visualType==="stationary"||selectedAssignment.visualType==="zone"}>Post-Snap Pfad</button><button className={drawMode==="zone"?"active":""} onClick={()=>setDrawMode(drawMode==="zone"?"none":"zone")} disabled={selectedAssignment.visualType!=="zone"}>Zone setzen</button><button onClick={()=>undoPoint("presnap")} disabled={!selectedAssignment.preSnapPath.length}>↶ Motion</button><button onClick={()=>undoPoint("post")} disabled={!selectedAssignment.path.length}>↶ Pfad</button><button onClick={clearVisual}>Visual löschen</button></div>}
      {selectedAssignment?.visualType==="zone"&&<div className="pb-zone-controls"><label><span>Zone Breite</span><input type="range" min="4" max="60" value={selectedAssignment.zoneWidth} onChange={e=>patch(selectedAssignment.id,{zoneWidth:Number(e.target.value)})}/><b>{Math.round(selectedAssignment.zoneWidth)}%</b></label><label><span>Zone Tiefe</span><input type="range" min="4" max="60" value={selectedAssignment.zoneHeight} onChange={e=>patch(selectedAssignment.id,{zoneHeight:Number(e.target.value)})}/><b>{Math.round(selectedAssignment.zoneHeight)}%</b></label></div>}
      <p className="cms-muted">Routes und Bewegungen können aus mehreren Segmenten bestehen. Pre-Snap Motion wird separat vom Post-Snap Assignment gespeichert.</p>
    </AdminCard>
    <AdminCard><div className="cms-section-head"><div><small>ASSIGNMENTS</small><h2>Positionen & Aufgaben</h2></div></div><div className="pb-assignments">{assignments.map((a,i)=>{const player=a.playerId?rosterById.get(a.playerId):null;return <article key={a.id} className={a.id===selectedAssignmentId?"active":""} onClick={()=>setSelectedAssignmentId(a.id)}><b>{i+1}</b><input value={a.positionLabel} onChange={e=>patch(a.id,{positionLabel:e.target.value})}/><select value={a.playerId||""} onChange={e=>patch(a.id,{playerId:e.target.value||null})}><option value="">Depth-Chart Position</option>{data?.roster.map(p=><option key={p.id} value={p.id}>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName} · {p.primaryPosition}</option>)}</select><input placeholder="Role" value={a.role} onChange={e=>patch(a.id,{role:e.target.value})}/><input placeholder="Assignment" value={a.assignment} onChange={e=>patch(a.id,{assignment:e.target.value})}/><input placeholder="Key / Read" value={a.keyRead} onChange={e=>patch(a.id,{keyRead:e.target.value})}/><input placeholder="Technique" value={a.technique} onChange={e=>patch(a.id,{technique:e.target.value})}/><select value={a.visualType} onChange={e=>patch(a.id,{visualType:e.target.value})}>{visualTypes.map(v=><option key={v.value} value={v.value}>{v.label}</option>)}</select><div className="coords"><input type="number" min={0} max={100} value={a.x} onChange={e=>patch(a.id,{x:Number(e.target.value)})}/><input type="number" min={0} max={100} value={a.y} onChange={e=>patch(a.id,{y:Number(e.target.value)})}/></div><button className="pb-remove" onClick={e=>{e.stopPropagation();removeAssignment(a.id)}}>×</button>{player&&<small>Aktuell: #{player.jerseyNumber??"–"} {player.firstName} {player.lastName}</small>}</article>})}</div></AdminCard>
    <AdminCard><label className="pb-notes"><span>Scheme Coaching Points</span><textarea rows={4} value={coachingPoints} onChange={e=>setCoachingPoints(e.target.value)} placeholder="Alignment · keys · leverage · communication · checks · finish"/></label></AdminCard>
   </>}</main></div>}
 </AdminShell>
}

function VisualMark({assignment:a,selected}:{assignment:Assignment;selected:boolean}){
 const cls=`pb-mark ${a.visualType} ${selected?"selected":""}`;
 const post=[{x:a.x,y:a.y},...(a.path||[])];const pre=[{x:a.x,y:a.y},...(a.preSnapPath||[])];
 return <>
  {a.preSnapPath?.length>0&&<polyline className={`pb-mark motion ${selected?"selected":""}`} points={pre.map(p=>`${p.x},${p.y}`).join(" ")}/>} 
  {a.visualType==="zone"&&<ellipse className={cls} cx={a.endX??a.x} cy={a.endY??a.y} rx={a.zoneWidth/2} ry={a.zoneHeight/2}/>} 
  {a.visualType!=="stationary"&&a.visualType!=="zone"&&a.path?.length>0&&<g className={cls}><polyline points={post.map(p=>`${p.x},${p.y}`).join(" ")}/><circle cx={post[post.length-1].x} cy={post[post.length-1].y} r="1.3"/></g>}
 </>
}
