"use client";
import {useEffect,useMemo,useState} from "react";
import {AdminCard,AdminNotice,AdminShell} from "../_components/AdminShell";
import {OpponentScouting} from "./OpponentScouting";
import {PlayBuilder} from "./PlayBuilder";
import {PlaybookField} from "./PlaybookFields";
import {SchemeKpis} from "./SchemeKpis";
import {avg,loadStudioStore,norm,routeLabels,routePath,saveStudioStore,tabs,tone,unavailable,unitLabel,type CustomRoute,type Depth,type Formation,type LineupSnapshot,type Payload,type Play,type Rating,type RouteDraft,type RouteKind,type RouteSegment,type Slot,type SlotOverride,type Tab,type Unit} from "./playbook-studio-model";
import "./playbook-studio.css";

export function PlaybookStudio(){
 const[data,setData]=useState<Payload|null>(null),[ratings,setRatings]=useState<Rating[]>([]),[seasonId,setSeasonId]=useState(""),[unit,setUnit]=useState<Unit>("offense"),[tab,setTab]=useState<Tab>("lineup"),[formationId,setFormationId]=useState(""),[selectedSlot,setSelectedSlot]=useState(""),[playName,setPlayName]=useState("Blue Trips Bubble"),[routes,setRoutes]=useState<RouteDraft[]>([]),[customRoutes,setCustomRoutes]=useState<CustomRoute[]>([]),[snapshots,setSnapshots]=useState<LineupSnapshot[]>([]),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[compareA,setCompareA]=useState(""),[compareB,setCompareB]=useState("");
 const[routeKind,setRouteKind]=useState<RouteKind>("hook"),[routeDistance,setRouteDistance]=useState(5),[routeBreak,setRouteBreak]=useState(5),[routeAngle,setRouteAngle]=useState(45),[routeTarget,setRouteTarget]=useState(""),[customRouteId,setCustomRouteId]=useState("");
 const[customName,setCustomName]=useState(""),[segments,setSegments]=useState<RouteSegment[]>([{yards:5,angle:0}]),[editingRouteId,setEditingRouteId]=useState("");
 const[slotOverrides,setSlotOverrides]=useState<Record<string,SlotOverride>>({}),[starterOverrides,setStarterOverrides]=useState<Record<string,string>>({}),[lineOfScrimmageY,setLineOfScrimmageY]=useState(50),[command,setCommand]=useState("WR1 Post 20Y 45° 5Y"),[positionTarget,setPositionTarget]=useState("O-LINE"),[yardLine,setYardLine]=useState(40),[yardHalf,setYardHalf]=useState<"own"|"opponent">("own");
 useEffect(()=>{void boot()},[]);
 async function boot(){setLoading(true);try{const[routesStore,snapshotStore]=await Promise.all([loadStudioStore<CustomRoute[]>("routes"),loadStudioStore<LineupSnapshot[]>("plays")]);setCustomRoutes(routesStore??[]);setSnapshots(snapshotStore??[]);await load()}finally{setLoading(false)}}
 async function load(nextSeason?:string,nextUnit:Unit=unit){setLoading(true);setNotice("");try{const q=new URLSearchParams();if(nextSeason)q.set("seasonId",nextSeason);q.set("unit",nextUnit);const r=await fetch(`/admin/api/playbook?${q}`),b=await r.json();if(!r.ok)throw new Error(b.error||"Playbook konnte nicht geladen werden.");const payload=b as Payload;setData(payload);setSeasonId(payload.season.id);setUnit(nextUnit);const current=payload.formations.find(x=>x.id===formationId)||payload.formations[0]||null;setFormationId(current?.id||"");setSelectedSlot(current?.slots[0]?.slotKey||"");setRouteTarget(current?.slots[0]?.slotKey||"");setSlotOverrides({});setStarterOverrides({});setRoutes([]);const a=await fetch(`/admin/api/formation-analysis?${new URLSearchParams({seasonId:payload.season.id})}`);if(a.ok){const ab=await a.json();setRatings(ab.players??[])}if(payload.roster[0])setCompareA(v=>v||payload.roster[0].id);if(payload.roster[1])setCompareB(v=>v||payload.roster[1].id)}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 const formation=data?.formations.find(f=>f.id===formationId)||null;
 const effectiveFormation=formation?{...formation,slots:formation.slots.map(s=>({...s,...(slotOverrides[s.slotKey]??{})}))}:null;
 const ratingMap=useMemo(()=>new Map(ratings.map(r=>[r.playerId,r])),[ratings]);
 function candidates(slot:Slot){const aliases=[slot.positionLabel,...slot.eligiblePositions.split(/[,;/|]/)].map(norm).filter(Boolean);let rows=(data?.depthChart??[]).filter(d=>aliases.includes(norm(d.position)));if(!rows.length&&slot.positionGroup)rows=(data?.depthChart??[]).filter(d=>norm(d.positionGroup)===norm(slot.positionGroup));return [...rows].sort((a,b)=>a.rank-b.rank)}
 function baselineStarter(slot:Slot){const list=candidates(slot);return list.find(x=>!unavailable(x.availability))??list[0]??null}
 function starter(slot:Slot){const list=candidates(slot),override=starterOverrides[slot.slotKey];if(override){const chosen=list.find(x=>x.playerId===override&&!unavailable(x.availability));if(chosen)return chosen}return list.find(x=>!unavailable(x.availability))??list[0]??null}
 function backup(slot:Slot){const current=starter(slot);return candidates(slot).filter(x=>!unavailable(x.availability)&&x.playerId!==current?.playerId)[0]??null}
 function playerRating(id:string|undefined|null){return id?(ratingMap.get(id)?.compositeRating??null):null}
 const slotRows=useMemo(()=>effectiveFormation?.slots.map(s=>({slot:s,starter:starter(s),backup:backup(s)}))??[],[effectiveFormation,data?.depthChart,starterOverrides,ratings]);
 const starterRatings=slotRows.map(x=>playerRating(x.starter?.playerId)).filter((x):x is number=>x!=null),teamRating=avg(starterRatings),baselineRating=avg((effectiveFormation?.slots??[]).map(s=>playerRating(baselineStarter(s)?.playerId)).filter((x):x is number=>x!=null)),ready=(data?.roster??[]).filter(p=>!unavailable(p.availability)).length,depthCovered=slotRows.filter(x=>x.backup).length;
 const ranked=[...slotRows].filter(x=>playerRating(x.starter?.playerId)!=null).sort((a,b)=>Number(playerRating(b.starter?.playerId))-Number(playerRating(a.starter?.playerId))),strongest=ranked[0],weakest=ranked.at(-1),selected=slotRows.find(x=>x.slot.slotKey===selectedSlot)||slotRows[0]||null;
 const bestPlan=useMemo(()=>{const slots=effectiveFormation?.slots??[],used=new Set<string>(),overrides:Record<string,string>={},ratingsOut:number[]=[];const ordered=[...slots].sort((a,b)=>candidates(a).filter(x=>!unavailable(x.availability)).length-candidates(b).filter(x=>!unavailable(x.availability)).length);for(const slot of ordered){const pool=candidates(slot).filter(x=>!unavailable(x.availability)&&!used.has(x.playerId)).sort((a,b)=>(playerRating(b.playerId)??-1)-(playerRating(a.playerId)??-1)||a.rank-b.rank),pick=pool[0]??candidates(slot).find(x=>!unavailable(x.availability));if(pick){overrides[slot.slotKey]=pick.playerId;used.add(pick.playerId);const r=playerRating(pick.playerId);if(r!=null)ratingsOut.push(r)}}return{overrides,rating:avg(ratingsOut)}},[effectiveFormation,data?.depthChart,ratings]);
 const selectedSwapRating=useMemo(()=>{if(!selected?.starter||!selected.backup||teamRating==null)return null;const current=playerRating(selected.starter.playerId),replacement=playerRating(selected.backup.playerId);if(current==null||replacement==null||!starterRatings.length)return null;return Math.round((starterRatings.reduce((a,b)=>a+b,0)-current+replacement)/starterRatings.length)},[selected,teamRating,ratings,starterRatings.join(",")]);
 function impact(value:number|null,base=baselineRating){return value==null||base==null?"–":`${value-base>=0?"+":""}${value-base}`}
 function setFormation(id:string){setFormationId(id);const f=data?.formations.find(x=>x.id===id);setSelectedSlot(f?.slots[0]?.slotKey||"");setRouteTarget(f?.slots[0]?.slotKey||"");setRoutes([]);setSlotOverrides({});setStarterOverrides({})}
 function swapDepth(){if(!selected?.backup)return setNotice("Für diesen Slot ist kein verfügbarer Backup vorhanden.");setStarterOverrides(cur=>({...cur,[selected.slot.slotKey]:selected.backup!.playerId}));setNotice(`${selected.slot.positionLabel}: Starter und Backup für diese Formation getauscht.`)}
 function applyBestLineup(){setStarterOverrides(bestPlan.overrides);setNotice(`Bestes verfügbares Lineup angewendet${bestPlan.rating!=null?` · Rating ${bestPlan.rating}`:""}. Depth Chart bleibt unverändert.`)}
 function resetLineup(){setStarterOverrides({});setNotice("Aufstellung auf aktuellen Depth Chart zurückgesetzt.")}
 function targetSlots(target:string){const t=norm(target);if(t==="OLINE")return effectiveFormation?.slots.filter(s=>["LT","LG","C","RG","RT","OL"].includes(norm(s.positionLabel)))??[];const exact=effectiveFormation?.slots.filter(s=>norm(s.positionLabel)===t||norm(s.slotKey)===t)??[];if(exact.length)return exact;const match=t.match(/^([A-Z]+)(\d+)$/);if(match){const peers=effectiveFormation?.slots.filter(s=>norm(s.positionLabel)===match[1])??[];return peers[Number(match[2])-1]?[peers[Number(match[2])-1]]:[]}return[]}
 function positionPlayers(target=positionTarget,yard=yardLine,half=yardHalf){const targets=targetSlots(target);if(!targets.length)return setNotice(`Ziel „${target}“ wurde nicht gefunden.`);const y=half==="own"?85-Math.max(0,Math.min(50,yard))*.7:15+Math.max(0,Math.min(50,yard))*.7;setSlotOverrides(cur=>{const next={...cur};for(const slot of targets)next[slot.slotKey]={x:cur[slot.slotKey]?.x??slot.x,y};return next});setLineOfScrimmageY(y);setNotice(`${target} auf ${half==="own"?"eigene":"gegnerische"} ${yard} gesetzt.`)}
 function addRoute(target=routeTarget,kind=routeKind,distance=routeDistance,angle=routeAngle,breakDistance=routeBreak){if(!target)return setNotice("Bitte einen Spieler-Slot auswählen.");const route:RouteDraft={slotKey:target,kind,distance:Math.max(1,distance),breakDistance:Math.max(1,breakDistance),angle,customRouteId:kind==="custom"?customRouteId||customRoutes[0]?.id:undefined};setRoutes(cur=>[...cur.filter(x=>x.slotKey!==target),route]);setSelectedSlot(target);setNotice(`${effectiveFormation?.slots.find(x=>x.slotKey===target)?.positionLabel||target}: ${routeLabels[kind]} eingezeichnet.`)}
 function executeCommand(){const text=command.trim();if(!text)return;const p=text.match(/^(O[- ]?LINE|[A-Z]+\d*)\s+auf\s+(\d{1,2})(?:\s*[- ]?yards?)?(?:\s+(eigene|eigenen|gegner|gegnerische|gegnerischen))?/i);if(p){const target=p[1].toUpperCase().replace("O LINE","O-LINE"),yard=Math.min(50,Number(p[2])),half=p[3]?.toLowerCase().startsWith("gegner")?"opponent":"own";setPositionTarget(target);setYardLine(yard);setYardHalf(half);positionPlayers(target,yard,half);return}const r=text.match(/([A-Z]+\d*)\s+(HOOK|POST|GO|SLANT|OUT|BUBBLE|CORNER)/i);if(r){const slot=targetSlots(r[1])[0];if(!slot)return setNotice(`Routenziel „${r[1]}“ wurde nicht gefunden.`);const nums=text.slice((r.index??0)+r[0].length).match(/\d+(?:[.,]\d+)?/g)?.map(v=>Number(v.replace(",",".")))??[],kind=r[2].toLowerCase() as RouteKind,distance=nums[0]??(kind==="hook"?3:10),angle=nums[1]??45,breakDistance=nums[2]??5;setRouteTarget(slot.slotKey);setRouteKind(kind);setRouteDistance(distance);setRouteAngle(angle);setRouteBreak(breakDistance);addRoute(slot.slotKey,kind,distance,angle,breakDistance);return}setNotice('Befehl nicht erkannt. Beispiel: „O-Line auf 50 Yards“ oder „WR2 Hook 3Y“.')}
 async function saveCustomRoute(){if(!customName.trim()||!segments.length)return setNotice("Routenname und mindestens ein Segment sind erforderlich.");const existing=customRoutes.find(x=>x.id===editingRouteId),route:CustomRoute={id:existing?.id??crypto.randomUUID(),name:customName.trim(),segments:segments.map(s=>({yards:Math.max(1,s.yards),angle:Math.max(-90,Math.min(90,s.angle))})),createdAt:existing?.createdAt??new Date().toISOString()};const next=[route,...customRoutes.filter(x=>x.id!==route.id)].sort((a,b)=>a.name.localeCompare(b.name,"de"));setCustomRoutes(next);setCustomRouteId(route.id);await saveStudioStore("routes",next);setCustomName("");setSegments([{yards:5,angle:0}]);setEditingRouteId("");setNotice(`Eigene Route „${route.name}“ ${existing?"aktualisiert":"gespeichert"}.`)}
 function editCustomRoute(id:string){const route=customRoutes.find(x=>x.id===id);if(!route)return;setEditingRouteId(id);setCustomName(route.name);setSegments(route.segments.map(s=>({...s})));setNotice(`Route „${route.name}“ zur Bearbeitung geladen.`)}
 async function deleteCustomRoute(id:string){const next=customRoutes.filter(x=>x.id!==id);setCustomRoutes(next);if(customRouteId===id)setCustomRouteId("");if(editingRouteId===id){setEditingRouteId("");setCustomName("");setSegments([{yards:5,angle:0}])}await saveStudioStore("routes",next);setNotice("Eigene Route gelöscht.")}
 async function savePlay(){if(!data||!effectiveFormation||!playName.trim())return setNotice("Formation und Play-Name sind erforderlich.");setSaving(true);try{const create=await fetch("/admin/api/playbook",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"create-play",seasonId:data.season.id,unit,formationId:effectiveFormation.id,name:playName.trim()})}),cb=await create.json();if(!create.ok)throw new Error(cb.error||"Play konnte nicht angelegt werden.");const assignments=effectiveFormation.slots.map((slot,i)=>{const d=starter(slot),route=routes.find(x=>x.slotKey===slot.slotKey),path=route?routePath(slot,route,customRoutes):[];return{id:crypto.randomUUID(),positionLabel:slot.positionLabel,playerId:d?.playerId??null,role:slot.roleLabel,assignment:route?routeLabels[route.kind]:"",technique:"",keyRead:"",x:slot.x,y:slot.y,endX:path.at(-1)?.x??null,endY:path.at(-1)?.y??null,visualType:route?"route":"stationary",path,preSnapPath:[],zoneWidth:12,zoneHeight:12,sortOrder:i}});const save=await fetch("/admin/api/playbook",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save-play",playId:cb.id,formationId:effectiveFormation.id,name:playName.trim(),concept:routes.length?"Route Concept":"",assignments})}),sb=await save.json();if(!save.ok)throw new Error(sb.error||"Play konnte nicht gespeichert werden.");setNotice(`Play „${playName.trim()}“ gespeichert · Version ${sb.version}.`);await load(data.season.id,unit)}catch(e){setNotice(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setSaving(false)}}
 function loadPlay(p:Play){setPlayName(p.name);const f=(p.formationId?data?.formations.find(x=>x.id===p.formationId):formation)||formation;if(!f)return;if(p.formationId)setFormationId(p.formationId);const used=new Set<string>(),matches=p.assignments.map(a=>{const slot=f.slots.find(s=>!used.has(s.slotKey)&&norm(s.positionLabel)===norm(a.positionLabel));if(slot)used.add(slot.slotKey);return{a,slot}}),overrides:Record<string,SlotOverride>={},starters:Record<string,string>={};for(const x of matches)if(x.slot){overrides[x.slot.slotKey]={x:x.a.x,y:x.a.y};if(x.a.playerId)starters[x.slot.slotKey]=x.a.playerId}setSlotOverrides(overrides);setStarterOverrides(starters);setRoutes(matches.filter(x=>x.slot&&x.a.path?.length>1).map(x=>({slotKey:x.slot!.slotKey,kind:"custom",distance:10,breakDistance:5,angle:45,rawPath:x.a.path})));setSelectedSlot(f.slots[0]?.slotKey||"");setRouteTarget(f.slots[0]?.slotKey||"");setNotice(`Play „${p.name}“ geladen.`)}
 async function saveSnapshot(){if(!data||!effectiveFormation)return;const snap:LineupSnapshot={id:crypto.randomUUID(),label:`${effectiveFormation.name} · ${new Date().toLocaleDateString("de-DE")}`,seasonId:data.season.id,unit,formationId:effectiveFormation.id,rating:teamRating,createdAt:new Date().toISOString(),slots:slotRows.map(x=>({slotKey:x.slot.slotKey,x:x.slot.x,y:x.slot.y,playerId:x.starter?.playerId??null}))};const next=[snap,...snapshots].slice(0,30);setSnapshots(next);await saveStudioStore("plays",next);setNotice("Aufstellungs-Snapshot gespeichert.")}
 function resetPlay(){setRoutes([]);setSlotOverrides({});setLineOfScrimmageY(50);setNotice("Play Builder zurückgesetzt.")}
 const comparePlayers=[compareA,compareB].map(id=>data?.roster.find(p=>p.id===id)||null);
 return <AdminShell active="playbook" title="Playbook & Scheme" eyebrow="RASCALS OS · FOOTBALL" actions={<><a className="cms-button secondary" href="/admin/playbook/formations">Formation Library</a><a className="cms-button secondary" href="/admin/playbook/system">System Editor</a></>}>
  {notice&&<AdminNotice tone={/fehl|Fehler|nicht/i.test(notice)?"error":"success"}>{notice}</AdminNotice>}
  <div className="pbs-shell"><section className="pbs-head"><div><small>SCHEME COMMAND</small><h2>Aufstellung, Plays, Gegneranalyse und KPIs in einem Football Workspace.</h2><p>Formation Library, Depth Chart, Roster und Performance Ratings sind die Datenbasis. Plays werden in der bestehenden RASCALS-OS-Playbook-Datenbank versioniert.</p></div><div className="pbs-select"><label>Saison<select value={seasonId} onChange={e=>void load(e.target.value,unit)}>{data?.seasons.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><div>{(["offense","defense","special-teams"] as Unit[]).map(u=><button key={u} className={u===unit?"active":""} onClick={()=>void load(seasonId,u)}>{unitLabel(u)}</button>)}</div></div></section>
   <nav className="pbs-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
   <SchemeKpis seasonId={seasonId} unit={unit} teamRating={teamRating}/>
   {loading?<AdminCard>Playbook & Scheme wird geladen…</AdminCard>:<>
    {tab==="lineup"&&<div className="pbs-grid"><PlaybookField formation={effectiveFormation} rows={slotRows} routes={[]} customRoutes={customRoutes} selected={selectedSlot} onSelect={setSelectedSlot}/><AdminCard><div className="cms-section-head"><div><small>POSITION PERFORMANCE</small><h2>{selected?.slot.positionLabel||"Slot wählen"}</h2></div>{selected&&<b className={`pbs-rating ${tone(playerRating(selected.starter?.playerId))}`}>{playerRating(selected.starter?.playerId)??"–"}</b>}</div>{selected?<><PlayerRow label="STARTER" depth={selected.starter} rating={playerRating(selected.starter?.playerId)}/><PlayerRow label="BACKUP" depth={selected.backup} rating={playerRating(selected.backup?.playerId)}/><div className="pbs-inline-actions">{selected.backup&&<button className="cms-button secondary" onClick={swapDepth}>Backup einsetzen</button>}<button className="cms-button secondary" onClick={resetLineup}>Depth Chart laden</button></div><p className="cms-muted">{selected.slot.roleLabel||selected.slot.positionGroup||"Formation Slot"}</p></>:<p className="cms-muted">Formation mit Slots auswählen.</p>}</AdminCard><AdminCard><div className="cms-section-head"><div><small>AUFSTELLUNGS-IMPACT</small><h2>Simulation</h2></div><button className="cms-button secondary" onClick={applyBestLineup}>Bestes Lineup</button></div><div className="pbs-simulation"><span><b>Aktuelle Aufstellung</b><strong>{teamRating??"–"}</strong><em>{impact(teamRating)}</em></span><span><b>{selected?.backup?`${selected.slot.positionLabel} · ${selected.backup.lastName} statt ${selected.starter?.lastName||"Starter"}`:"Backup-Szenario"}</b><strong>{selectedSwapRating??"–"}</strong><em>{impact(selectedSwapRating)}</em></span><span className="best"><b>Bestes Lineup (Auto)</b><strong>{bestPlan.rating??"–"}</strong><em>{impact(bestPlan.rating)}</em></span></div><div className="pbs-intel"><span>Team Rating <b>{teamRating??"–"}</b></span><span>Game Ready <b>{ready}/{data?.roster.length??0}</b></span><span>Stärkster Slot <b>{strongest?.slot.positionLabel||"–"}</b></span><span>Entwicklungsfeld <b>{weakest?.slot.positionLabel||"–"}</b></span><span>Backup Coverage <b>{depthCovered}/{slotRows.length}</b></span><span>Simuliert <b>{Object.keys(starterOverrides).length} Wechsel</b></span></div><button className="cms-button secondary" onClick={()=>void saveSnapshot()}>Snapshot speichern</button></AdminCard></div>}
    {tab==="playbook"&&<PlayBuilder data={data} formation={effectiveFormation} formationId={formationId} setFormation={setFormation} slotRows={slotRows} selectedSlot={selectedSlot} setSelectedSlot={setSelectedSlot} routes={routes} setRoutes={setRoutes} customRoutes={customRoutes} customRouteId={customRouteId} setCustomRouteId={setCustomRouteId} routeTarget={routeTarget} setRouteTarget={setRouteTarget} routeKind={routeKind} setRouteKind={setRouteKind} routeDistance={routeDistance} setRouteDistance={setRouteDistance} routeBreak={routeBreak} setRouteBreak={setRouteBreak} routeAngle={routeAngle} setRouteAngle={setRouteAngle} addRoute={addRoute} playName={playName} setPlayName={setPlayName} savePlay={savePlay} loadPlay={loadPlay} saving={saving} command={command} setCommand={setCommand} executeCommand={executeCommand} positionTarget={positionTarget} setPositionTarget={setPositionTarget} yardLine={yardLine} setYardLine={setYardLine} yardHalf={yardHalf} setYardHalf={setYardHalf} positionPlayers={positionPlayers} resetPlay={resetPlay} lineOfScrimmageY={lineOfScrimmageY} setSlotOverrides={setSlotOverrides} customName={customName} setCustomName={setCustomName} segments={segments} setSegments={setSegments} saveCustomRoute={saveCustomRoute} deleteCustomRoute={deleteCustomRoute} editCustomRoute={editCustomRoute}/>} 
    {tab==="scouting"&&<OpponentScouting customRoutes={customRoutes} onNotice={setNotice}/>} 
    {tab==="depth"&&<AdminCard><div className="cms-section-head"><div><small>DEPTH SOURCE</small><h2>{data?.depthChartSnapshot?.label||"Current Depth Chart"}</h2></div></div><div className="pbs-depth-table">{slotRows.map(x=><article key={x.slot.id}><b>{x.slot.positionLabel}</b><PlayerRow label="1" depth={x.starter} rating={playerRating(x.starter?.playerId)}/><PlayerRow label="2" depth={x.backup} rating={playerRating(x.backup?.playerId)}/></article>)}</div></AdminCard>}
    {tab==="performance"&&<AdminCard><div className="cms-section-head"><div><small>PLAYER PERFORMANCE</small><h2>Roster Ratings</h2></div></div><div className="pbs-perf-grid">{(data?.roster??[]).map(p=><article key={p.id}><span>#{p.jerseyNumber??"–"} · {p.primaryPosition}</span><h3>{p.firstName} {p.lastName}</h3><strong className={tone(playerRating(p.id))}>{playerRating(p.id)??"–"}</strong><small>{p.availability.toUpperCase()}</small></article>)}</div></AdminCard>}
    {tab==="compare"&&<AdminCard><div className="cms-section-head"><div><small>PLAYER COMPARE</small><h2>Zwei Spieler direkt vergleichen</h2></div></div><div className="pbs-compare-select"><select value={compareA} onChange={e=>setCompareA(e.target.value)}>{data?.roster.map(p=><option key={p.id} value={p.id}>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName}</option>)}</select><b>VS</b><select value={compareB} onChange={e=>setCompareB(e.target.value)}>{data?.roster.map(p=><option key={p.id} value={p.id}>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName}</option>)}</select></div><div className="pbs-compare">{comparePlayers.map((p,i)=>p?<article key={p.id}><small>{i===0?"SPIELER A":"SPIELER B"}</small><h2>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName}</h2><b className={tone(playerRating(p.id))}>{playerRating(p.id)??"–"}</b><p>{p.primaryPosition} · {p.availability.toUpperCase()}</p><span>Performance {ratingMap.get(p.id)?.performanceRating??"–"}</span><span>Skill {ratingMap.get(p.id)?.skillRating??"–"}</span></article>:null)}</div></AdminCard>}
    {tab==="trends"&&<AdminCard><div className="cms-section-head"><div><small>TRENDS</small><h2>Team Rating Landscape</h2></div></div><div className="pbs-trends">{[...ratings].filter(r=>r.compositeRating!=null).sort((a,b)=>Number(b.compositeRating)-Number(a.compositeRating)).slice(0,20).map(r=>{const p=data?.roster.find(x=>x.id===r.playerId);return p?<article key={r.playerId}><span>#{p.jerseyNumber??"–"} {p.lastName}<small>{p.primaryPosition}</small></span><i><b style={{width:`${Math.max(3,Math.min(100,r.compositeRating??0))}%`}}/></i><strong>{r.compositeRating}</strong></article>:null})}</div><div className="pbs-snapshots"><div className="cms-section-head"><div><small>AUFSTELLUNGS-SNAPSHOTS</small><h2>Historie</h2></div></div>{snapshots.filter(x=>x.seasonId===seasonId).slice(0,10).map(s=><article key={s.id}><span><b>{s.label}</b><small>{new Date(s.createdAt).toLocaleString("de-DE")}</small></span><strong>{s.rating??"–"}</strong></article>)}</div></AdminCard>}
   </>}
  </div>
 </AdminShell>
}

function PlayerRow({label,depth,rating}:{label:string;depth:Depth|null|undefined;rating:number|null}){return <div className="pbs-player-row"><small>{label}</small><span>{depth?`#${depth.jerseyNumber??"–"} ${depth.firstName} ${depth.lastName}`:"Nicht besetzt"}</span><em>{depth?.availability?.toUpperCase()||"–"}</em><b className={tone(rating)}>{rating??"–"}</b></div>}