import { bindings } from "../../../lib/cms";
import { requireCmsPermission } from "../../../lib/permissions";

export type Sponsor = { id:string; name:string; logo:string; url:string; tier:"premium"|"gold"|"silver"|"partner"; sortOrder:number; active:boolean; startsAt:string|null; endsAt:string|null; createdAt:string; updatedAt:string };

async function ensureColumn(name:string,definition:string){const{DB}=bindings();const info=await DB.prepare("PRAGMA table_info(sponsors)").all<Record<string,unknown>>();if(!info.results.some(r=>String(r.name)===name))await DB.prepare(`ALTER TABLE sponsors ADD COLUMN ${name} ${definition}`).run()}
async function ensureSchema(){const{DB}=bindings();await DB.prepare(`CREATE TABLE IF NOT EXISTS sponsors (id TEXT PRIMARY KEY,name TEXT NOT NULL,logo TEXT NOT NULL DEFAULT '',url TEXT NOT NULL DEFAULT '',tier TEXT NOT NULL DEFAULT 'partner',sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,starts_at TEXT,ends_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();await ensureColumn("starts_at","TEXT");await ensureColumn("ends_at","TEXT")}
function mapRow(row:Record<string,unknown>):Sponsor{const raw=String(row.tier??"partner");const tier:["premium"|"gold"|"silver"|"partner"][number]=["premium","gold","silver"].includes(raw)?raw as Sponsor["tier"]:"partner";return{id:String(row.id),name:String(row.name),logo:String(row.logo??""),url:String(row.url??""),tier,sortOrder:Number(row.sort_order??0),active:Number(row.active??1)===1,startsAt:row.starts_at?String(row.starts_at):null,endsAt:row.ends_at?String(row.ends_at):null,createdAt:String(row.created_at),updatedAt:String(row.updated_at)}}
export async function GET(){const actor=await requireCmsPermission("sponsors");if(actor instanceof Response)return actor;await ensureSchema();const{DB}=bindings();const r=await DB.prepare("SELECT * FROM sponsors ORDER BY CASE tier WHEN 'premium' THEN 1 WHEN 'gold' THEN 2 WHEN 'silver' THEN 3 ELSE 4 END, sort_order, name").all();return Response.json({items:r.results.map(x=>mapRow(x as Record<string,unknown>))})}
export async function POST(request:Request){const actor=await requireCmsPermission("sponsors");if(actor instanceof Response)return actor;await ensureSchema();const b=await request.json() as Partial<Sponsor>;if(!b.name?.trim())return Response.json({error:"Name is required"},{status:400});const id=crypto.randomUUID(),{DB}=bindings();await DB.prepare("INSERT INTO sponsors (id,name,logo,url,tier,sort_order,active,starts_at,ends_at) VALUES (?,?,?,?,?,?,?,?,?)").bind(id,b.name.trim(),b.logo??"",b.url??"",b.tier??"partner",Number(b.sortOrder??0),b.active===false?0:1,b.startsAt??null,b.endsAt??null).run();const row=await DB.prepare("SELECT * FROM sponsors WHERE id=?").bind(id).first<Record<string,unknown>>();return Response.json({item:mapRow(row??{})},{status:201})}
export async function PUT(request:Request){const actor=await requireCmsPermission("sponsors");if(actor instanceof Response)return actor;await ensureSchema();const b=await request.json() as Partial<Sponsor>;if(!b.id||!b.name?.trim())return Response.json({error:"ID and name are required"},{status:400});const{DB}=bindings();await DB.prepare("UPDATE sponsors SET name=?,logo=?,url=?,tier=?,sort_order=?,active=?,starts_at=?,ends_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(b.name.trim(),b.logo??"",b.url??"",b.tier??"partner",Number(b.sortOrder??0),b.active===false?0:1,b.startsAt??null,b.endsAt??null,b.id).run();const row=await DB.prepare("SELECT * FROM sponsors WHERE id=?").bind(b.id).first<Record<string,unknown>>();if(!row)return Response.json({error:"Not found"},{status:404});return Response.json({item:mapRow(row)})}
export async function DELETE(request:Request){const actor=await requireCmsPermission("sponsors");if(actor instanceof Response)return actor;const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"ID is required"},{status:400});const{DB}=bindings();await DB.prepare("DELETE FROM sponsors WHERE id=?").bind(id).run();return Response.json({ok:true})}
