"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {AdminCard,AdminNotice,AdminShell} from "../../../_components/AdminShell";
import "./lineup-simulator.css";

type Unit="offense"|"defense"|"special-teams";
type Season={id:string;name:string;year:number;isCurrent:boolean};
type Slot={slotKey:string;positionLabel:string;positionGroup:string;eligiblePositions:string;x:number;y:number;sortOrder:number};
type Formation={id:string;name:string;personnel:string;family:string;slots:Slot[]};
type Depth={position:string;positionGroup:string;rank:number;playerId:string;firstName:string;lastName:string;jerseyNumber:number|null;availability:string};
type Rating={playerId:string;compositeRating:number|null;performanceRating:number|null;skillRating:number|null};
const norm=(v:string)=>v.toUpperCase().replace(/[^A-Z0-9]/g,"");
const blocked=(v:string)=>["out","return-to-play","inactive","unavailable"].includes(v.toLowerCase());
const availabilityPenalty=(v:string)=>v.toLowerCase()==="limited"?8:v.toLowerCase()==="injured"?14:0;

export function LineupSimulator(){
 const[seasons,setSeasons]=useState<Season[]>([]),[seasonId,setSeasonId]=useState(""),[unit,setUnit]=useState<Unit>("defense"),[formations,setFormations]=useState<Formation[]>([]),[formationId,setFormationId]=useState(""),[depth,setDepth]=useState<Depth[]>([]),[ratings,setRatings]=useState<Rating[]>([]),[forcedOut,setForcedOut]=useState<Set<string>>(new Set()),[manual,setManual]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[notice,setNotice]=useState(""),[optimized,setOptimized]=useState(false);
 useEffect(()=>{void bootstrap()},[]);
 async function bootstrap(){setLoading(true);try{const r=await fetch("/admin/api/playbook?unit=defense"),b=await r.json();if(!r.ok)throw new Error(b.error||"Saison konnte nicht geladen werden.");setSeasons(b.seasons||[]);const sid=b.season?.id||b.seasons?.find((s:Season)=>s.isCurrent)?.id||"";setSeasonId(sid);if(sid)await load(sid,"defense")}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 async function load(sid:string,u:Unit){setLoading(true);setNotice("");try{const q=new URLSearchParams({seasonId:sid,unit:u});const[pr,fr,ar]=await Promise.all([fetch(`/admin/api/playbook?${q}`),fetch(`/admin/api/playbook-foundation?${q}`),fetch(`/admin/api/formation-analysis?seasonId=${encodeURIComponent(sid)}`)]);const[p,f,a]=await Promise.all([pr.json(),fr.json(),ar.json()]);if(!pr.ok)throw new Error(p.error||"Depth Chart konnte nicht geladen werden.");if(!fr.ok)throw new Error(f.error||"Formationen konnten nicht geladen werden.");setDepth(p.depthChart||[]);setRatings(a.players||[]);setFormations(f.formations||[]);setFormationId((f.formations||[])[0]?.id||"");setForcedOut(new Set());setManual({});setOptimized(false)}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 const formation=useMemo(()=>formations.find(f=>f.id===formationId)||null,[formations,formationId]);
 function candidates(slot:Slot){const aliases=[slot.positionLabel,...slot.eligiblePositions.split(/[,;/|]/)].map(norm).filter(Boolean);let rows=depth.filter(d=>aliases.includes(norm(d.position)));if(!rows.length&&slot.positionGroup)rows=depth.filter(d=>norm(d.positionGroup)===norm(slot.positionGroup));return rows.sort((a,b)=>a.rank-b.rank)}
 function rating(id:string){return ratings.find(r=>r.playerId===id)?.compositeRating??null}
 function playerValue(p:Depth){return (rating(p.playerId)??50)-availabilityPenalty(p.availability)}
 const sim=useMemo(()=>{const used=new Set<string>();return (formation?.slots||[]).slice().sort((a,b)=>a.sortOrder-b.sortOrder).map(slot=>{const list=candidates(slot);const base=list[0]||null;const manualId=manual[slot.slotKey];let selected=manualId?list.find(p=>p.playerId===manualId)||null:null;if(!selected){selected=list.find(p=>!forcedOut.has(p.playerId)&&!blocked(p.availability)&&!used.has(p.playerId))||list.find(p=>!forcedOut.has(p.playerId)&&!blocked(p.availability))||null}if(selected)used.add(selected.playerId);const baseRating=base?rating(base.playerId):null;const simRating=selected?rating(selected.playerId):null;const delta=baseRating!=null&&simRating!=null?simRating-baseRating:null;return{slot,base,selected,list,baseRating,simRating,delta}})},[formation,depth,ratings,forcedOut,manual]);
 const baseRatings=sim.map(x=>x.baseRating).filter((v):v is number=>v!=null),simRatings=sim.map(x=>x.simRating).filter((v):v is number=>v!=null);const baseTotal=baseRatings.length?Math.round(baseRatings.reduce((a,b)=>a+b,0)/baseRatings.length):null;const simTotal=simRatings.length?Math.round(simRatings.reduce((a,b)=>a+b,0)/simRatings.length):null;const delta=baseTotal!=null&&simTotal!=null?simTotal-baseTotal:null;const unresolved=sim.filter(x=>!x.selected).length;const degraded=sim.filter(x=>x.delta!=null&&x.delta<0).length;
 function toggleOut(id:string){setForcedOut(c=>{const n=new Set(c);n.has(id)?n.delete(id):n.add(id);return n});setOptimized(false)}
 function optimizeLineup(){if(!formation)return;const source=formation.slots.slice().sort((a,b)=>{const ac=candidates(a).filter(p=>!forcedOut.has(p.playerId)&&!blocked(p.availability)).length,bc=candidates(b).filter(p=>!forcedOut.has(p.playerId)&&!blocked(p.availability)).length;return ac-bc||a.sortOrder-b.sortOrder});const pools=source.map(slot=>({slot,players:candidates(slot).filter(p=>!forcedOut.has(p.playerId)&&!blocked(p.availability)).sort((a,b)=>playerValue(b)-playerValue(a)).slice(0,8)}));let bestScore=-Infinity,best:Record<string,string>={};const maxRemaining=pools.map(p=>p.players[0]?playerValue(p.players[0]):0);const suffix=new Array(maxRemaining.length+1).fill(0);for(let i=maxRemaining.length-1;i>=0;i--)suffix[i]=suffix[i+1]+maxRemaining[i];function walk(i:number,used:Set<string>,score:number,picks:Record<string,string>){if(score+suffix[i]<=bestScore)return;if(i===pools.length){if(score>bestScore){bestScore=score;best={...picks}}return}const {slot,players}=pools[i];let placed=false;for(const p of players){if(used.has(p.playerId))continue;placed=true;used.add(p.playerId);picks[slot.slotKey]=p.playerId;walk(i+1,used,score+playerValue(p),picks);used.delete(p.playerId);delete picks[slot.slotKey]}if(!placed)walk(i+1,used,score-100,picks)}walk(0,new Set(),0,{});setManual(best);setOptimized(true);setNotice(Object.keys(best).length===formation.slots.length?"Best Lineup berechnet. Keine produktiven Depth-Chart-Daten wurden verändert.":`Best Lineup berechnet, aber ${formation.slots.length-Object.keys(best).length} Slot(s) konnten nicht eindeutig besetzt werden.`)}
 function reset(){setForcedOut(new Set());setManual({});setOptimized(false);setNotice("")}
 return <AdminShell active="playbook" title="Lineup Simulator" eyebrow="RASCALS OS · COACHING INTELLIGENCE" actions={<><Link className="cms-button secondary" href="/admin/playbook/formations">← Formation Library</Link><button className="cms-button" onClick={optimizeLineup} disabled={!formation||loading}>Best Lineup berechnen</button><button className="cms-button secondary" onClick={reset}>Simulation zurücksetzen</button></>}>
 {notice&&<AdminNotice tone={/nicht|aber|Fehler/i.test(notice)?"error":"success"}>{notice}</AdminNotice>}
 <AdminCard className="ls-head"><div><small>{optimized?"OPTIMIZED LINEUP":"WHAT-IF ENGINE"}</small><h2>{optimized?"Beste verfügbare Kombination für diese Formation.":"Ausfälle simulieren, ohne den Depth Chart zu verändern."}</h2><p>{optimized?"Die Engine maximiert das verfügbare Composite Rating über alle Slots, verhindert Doppelbesetzungen und berücksichtigt Availability.":"Starter auf OUT setzen, Replacement wählen und den unmittelbaren Einfluss auf die komplette Formation sehen."}</p></div><div className="ls-filters"><label><span>Saison</span><select value={seasonId} onChange={e=>{setSeasonId(e.target.value);void load(e.target.value,unit)}}>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span>Unit</span><select value={unit} onChange={e=>{const u=e.target.value as Unit;setUnit(u);void load(seasonId,u)}}><option value="offense">Offense</option><option value="defense">Defense</option><option value="special-teams">Special Teams</option></select></label><label><span>Formation</span><select value={formationId} onChange={e=>{setFormationId(e.target.value);setForcedOut(new Set());setManual({});setOptimized(false)}}>{formations.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></div></AdminCard>
 {loading?<AdminCard>Simulation wird geladen…</AdminCard>:!formation?<AdminCard>Keine Formation vorhanden.</AdminCard>:<>
 <div className="ls-kpis"><AdminCard><span>BASE LINEUP</span><b>{baseTotal??"–"}</b><small>/100</small></AdminCard><AdminCard><span>{optimized?"BEST LINEUP":"SIMULATED"}</span><b>{simTotal??"–"}</b><small>/100</small></AdminCard><AdminCard><span>IMPACT</span><b className={delta!=null&&delta<0?"bad":delta!=null&&delta>0?"good":""}>{delta==null?"–":delta>0?`+${delta}`:delta}</b><small>Punkte</small></AdminCard><AdminCard><span>RISKS</span><b>{unresolved+degraded}</b><small>{unresolved} unbesetzt · {degraded} schwächer</small></AdminCard></div>
 <div className="ls-grid"><AdminCard><div className="ls-section"><div><small>{optimized?"OPTIMIZED FORMATION":"FORMATION FIELD"}</small><h3>{formation.name}</h3></div><span>{formation.personnel||formation.family}</span></div><div className={`ls-field ${unit}`}><div className="ls-los"/>{[10,20,30,40,50,60,70,80,90].map(n=><i key={n} style={{top:`${n}%`}}/>)}{sim.map(x=><button key={x.slot.slotKey} className={!x.selected?"missing":x.delta!=null&&x.delta<0?"drop":""} style={{left:`${x.slot.x}%`,top:`${x.slot.y}%`}} title={x.slot.positionLabel}><strong>{x.slot.positionLabel||x.slot.slotKey}</strong><span>{x.selected?`#${x.selected.jerseyNumber??"–"} ${x.selected.lastName}`:"UNRESOLVED"}</span><em>{x.simRating??"–"}</em></button>)}</div></AdminCard>
 <AdminCard><div className="ls-section"><div><small>SIMULATION CONTROLS</small><h3>Availability & Overrides</h3></div></div><div className="ls-controls">{sim.map(x=><article key={x.slot.slotKey}><div className="ls-slot"><b>{x.slot.positionLabel||x.slot.slotKey}</b><span>{x.base?`Base: #${x.base.jerseyNumber??"–"} ${x.base.lastName}`:"Kein Starter"}</span></div>{x.base&&<button className={forcedOut.has(x.base.playerId)?"out active":"out"} onClick={()=>toggleOut(x.base!.playerId)}>{forcedOut.has(x.base.playerId)?"OUT aktiv":"Starter OUT"}</button>}<select value={manual[x.slot.slotKey]||""} onChange={e=>{setManual(c=>({...c,[x.slot.slotKey]:e.target.value}));setOptimized(false)}}><option value="">AUTO Replacement</option>{x.list.filter(p=>!forcedOut.has(p.playerId)&&!blocked(p.availability)).map(p=><option key={p.playerId} value={p.playerId}>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName} · {rating(p.playerId)??"–"}{p.availability.toLowerCase()!=="full"?` · ${p.availability}`:""}</option>)}</select><div className="ls-impact"><span>Sim</span><b>{x.simRating??"–"}</b><em className={x.delta!=null&&x.delta<0?"bad":x.delta!=null&&x.delta>0?"good":""}>{x.delta==null?"–":x.delta>0?`+${x.delta}`:x.delta}</em></div></article>)}</div></AdminCard></div>
 <AdminCard><div className="ls-section"><div><small>COACHING SUMMARY</small><h3>{optimized?"Best Lineup vs. Depth Chart":"Simulation Impact"}</h3></div></div><div className="ls-summary">{sim.filter(x=>optimized||forcedOut.has(x.base?.playerId||"")||x.delta!==0||!x.selected).map(x=><div key={x.slot.slotKey}><strong>{x.slot.positionLabel||x.slot.slotKey}</strong><span>{x.base?`#${x.base.jerseyNumber??"–"} ${x.base.lastName}`:"–"} → {x.selected?`#${x.selected.jerseyNumber??"–"} ${x.selected.lastName}`:"kein Replacement"}</span><em className={x.delta!=null&&x.delta<0?"bad":x.delta!=null&&x.delta>0?"good":""}>{x.delta==null?"DATA GAP":`${x.delta>0?"+":""}${x.delta} pts`}</em></div>)}{!optimized&&!sim.some(x=>forcedOut.has(x.base?.playerId||"")||x.delta!==0||!x.selected)&&<p>Noch keine Abweichung vom aktuellen Depth Chart simuliert.</p>}</div></AdminCard></>}
 </AdminShell>
}
