"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {AdminCard,AdminNotice,AdminShell} from "../../_components/AdminShell";
import "./formation-library.css";

type Unit="offense"|"defense"|"special-teams";
type Season={id:string;year:number;name:string;isCurrent:boolean};
type Slot={id?:string;slotKey:string;positionLabel:string;positionGroup:string;roleLabel:string;x:number;y:number;eligiblePositions:string;sortOrder:number};
type Formation={id:string;seasonId:string;unit:Unit;name:string;personnel:string;family:string;strengthRule:string;description:string;tags:string;active:boolean;updatedAt:string;slots:Slot[]};
type FoundationPayload={seasonId:string;unit:Unit;formations:Formation[];selectedFormation:Formation|null;plays:Array<{id:string;formationId:string|null}>};
const EMPTY_SLOT=():Slot=>({slotKey:"",positionLabel:"",positionGroup:"",roleLabel:"",x:50,y:50,eligiblePositions:"",sortOrder:0});
const unitLabel=(u:Unit)=>u==="special-teams"?"SPECIAL TEAMS":u.toUpperCase();

export function FormationLibrary(){
 const[seasons,setSeasons]=useState<Season[]>([]),[seasonId,setSeasonId]=useState(""),[unit,setUnit]=useState<Unit>("defense"),[formations,setFormations]=useState<Formation[]>([]),[selectedId,setSelectedId]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const[name,setName]=useState(""),[personnel,setPersonnel]=useState(""),[family,setFamily]=useState(""),[strengthRule,setStrengthRule]=useState(""),[description,setDescription]=useState(""),[tags,setTags]=useState(""),[slots,setSlots]=useState<Slot[]>([]);
 const selected=useMemo(()=>formations.find(f=>f.id===selectedId)||null,[formations,selectedId]);
 const linkedPlayCount=useMemo(()=>0,[]);
 useEffect(()=>{void bootstrap()},[]);
 async function bootstrap(){setLoading(true);try{const r=await fetch(`/admin/api/playbook?unit=${unit}`);const b=await r.json();if(!r.ok)throw new Error(b.error||"Saisondaten konnten nicht geladen werden.");setSeasons(b.seasons||[]);const sid=b.season?.id||b.seasons?.find((s:Season)=>s.isCurrent)?.id||b.seasons?.[0]?.id||"";setSeasonId(sid);if(sid)await load(sid,unit);}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 async function load(sid=seasonId,u=unit,keepId?:string){if(!sid)return;setLoading(true);try{const q=new URLSearchParams({seasonId:sid,unit:u});const r=await fetch(`/admin/api/playbook-foundation?${q}`);const b=await r.json() as FoundationPayload&{error?:string};if(!r.ok)throw new Error(b.error||"Formation Library konnte nicht geladen werden.");setFormations(b.formations||[]);const next=(keepId&&b.formations.find(f=>f.id===keepId))||b.formations.find(f=>f.id===selectedId)||b.formations[0]||null;if(next)apply(next);else clearEditor();}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 function apply(f:Formation){setSelectedId(f.id);setName(f.name);setPersonnel(f.personnel);setFamily(f.family);setStrengthRule(f.strengthRule);setDescription(f.description);setTags(f.tags);setSlots((f.slots||[]).map((s,i)=>({...s,sortOrder:Number.isFinite(s.sortOrder)?s.sortOrder:i})));}
 function clearEditor(){setSelectedId("");setName("");setPersonnel("");setFamily("");setStrengthRule("");setDescription("");setTags("");setSlots([])}
 async function api(body:Record<string,unknown>){const r=await fetch("/admin/api/playbook-foundation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Aktion fehlgeschlagen.");return b}
 async function createFormation(){if(!seasonId)return;const candidate=prompt("Formationsname:",unit==="defense"?"4-2-5 Base":unit==="offense"?"Shotgun Trips Right":"Punt");if(!candidate?.trim())return;setSaving(true);try{const b=await api({action:"create-formation",seasonId,unit,name:candidate.trim(),personnel:"",family:""});await load(seasonId,unit,b.id);setNotice("Formation angelegt.")}catch(e){setNotice(e instanceof Error?e.message:"Fehler")}finally{setSaving(false)}}
 async function saveMeta(){if(!selectedId||!name.trim())return;setSaving(true);try{await api({action:"update-formation",formationId:selectedId,name,personnel,family,strengthRule,description,tags});await load(seasonId,unit,selectedId);setNotice("Formation gespeichert.")}catch(e){setNotice(e instanceof Error?e.message:"Speichern fehlgeschlagen.")}finally{setSaving(false)}}
 async function saveSlots(){if(!selectedId)return;setSaving(true);try{await api({action:"save-slots",formationId:selectedId,slots:slots.map((s,i)=>({...s,sortOrder:i}))});await load(seasonId,unit,selectedId);setNotice("Formation Slots gespeichert.")}catch(e){setNotice(e instanceof Error?e.message:"Slots konnten nicht gespeichert werden.")}finally{setSaving(false)}}
 async function duplicate(){if(!selectedId)return;setSaving(true);try{const b=await api({action:"duplicate-formation",formationId:selectedId});await load(seasonId,unit,b.id);setNotice(`Formation dupliziert: ${b.name}`)}catch(e){setNotice(e instanceof Error?e.message:"Duplizieren fehlgeschlagen.")}finally{setSaving(false)}}
 async function archive(){if(!selectedId||!confirm(`Formation „${name}“ archivieren?`))return;setSaving(true);try{const b=await api({action:"archive-formation",formationId:selectedId});await load(seasonId,unit);setNotice(b.linkedActivePlays?`Formation archiviert. ${b.linkedActivePlays} aktive Plays referenzieren sie noch.`:"Formation archiviert.")}catch(e){setNotice(e instanceof Error?e.message:"Archivieren fehlgeschlagen.")}finally{setSaving(false)}}
 function addSlot(){setSlots(c=>[...c,{...EMPTY_SLOT(),slotKey:`S${c.length+1}`,sortOrder:c.length}])}
 function patchSlot(index:number,patch:Partial<Slot>){setSlots(c=>c.map((s,i)=>i===index?{...s,...patch}:s))}
 function removeSlot(index:number){setSlots(c=>c.filter((_,i)=>i!==index))}
 function moveSlot(index:number,dir:-1|1){setSlots(c=>{const n=[...c],j=index+dir;if(j<0||j>=n.length)return c;[n[index],n[j]]=[n[j],n[index]];return n.map((s,i)=>({...s,sortOrder:i}))})}
 async function changeUnit(u:Unit){setUnit(u);setSelectedId("");await load(seasonId,u)}
 async function changeSeason(sid:string){setSeasonId(sid);setSelectedId("");await load(sid,unit)}
 return <AdminShell active="playbook" title="Formation Library" eyebrow="RASCALS OS · SCHEME CENTER" actions={<><Link className="cms-button secondary" href="/admin/playbook">← Playbook</Link><button className="cms-button secondary" onClick={()=>void createFormation()} disabled={saving}>＋ Formation</button>{selectedId&&<button className="cms-button" onClick={()=>void saveMeta()} disabled={saving}>Metadaten speichern</button>}{selectedId&&<button className="cms-button" onClick={()=>void saveSlots()} disabled={saving}>Slots speichern</button>}</>}>
  {notice&&<AdminNotice tone={/fehl|Fehler|nicht/i.test(notice)?"error":"success"}>{notice}</AdminNotice>}
  <AdminCard className="fl-head"><div><small>FORMATION SOURCE OF TRUTH</small><h2>Eine Formation definieren. Überall wiederverwenden.</h2><p>Personnel, Family, Strength Rules und Positions-Slots werden zentral gespeichert und später von Playbook, Gameplan, Depth Chart Mapping und Training konsumiert.</p></div><div className="fl-filters"><label><span>Saison</span><select value={seasonId} onChange={e=>void changeSeason(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="fl-unit-tabs">{(["offense","defense","special-teams"] as Unit[]).map(u=><button key={u} className={u===unit?"active":""} onClick={()=>void changeUnit(u)}>{unitLabel(u)}</button>)}</div></div></AdminCard>
  {loading?<AdminCard>Formation Library wird geladen…</AdminCard>:<div className="fl-grid">
   <aside><AdminCard><div className="fl-card-head"><div><small>LIBRARY</small><h3>{unitLabel(unit)}</h3></div><b>{formations.length}</b></div><div className="fl-list">{formations.length?formations.map(f=><button key={f.id} className={f.id===selectedId?"active":""} onClick={()=>apply(f)}><span><strong>{f.name}</strong><small>{[f.family,f.personnel].filter(Boolean).join(" · ")||"Noch nicht klassifiziert"}</small></span><em>{f.slots.length} Slots</em></button>):<p className="fl-empty">Noch keine Formation in dieser Unit.</p>}</div></AdminCard></aside>
   <main>{selected?<><AdminCard><div className="fl-section-title"><div><small>FORMATION META</small><h3>{selected.name}</h3></div><div className="fl-actions"><button onClick={()=>void duplicate()} disabled={saving}>Duplizieren</button><button className="danger" onClick={()=>void archive()} disabled={saving}>Archivieren</button></div></div><div className="fl-form"><label><span>Name</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Personnel / Package</span><input value={personnel} onChange={e=>setPersonnel(e.target.value)} placeholder="z. B. 4 DL · 2 LB · 5 DB"/></label><label><span>Formation Family</span><input value={family} onChange={e=>setFamily(e.target.value)} placeholder="z. B. Nickel / Shotgun"/></label><label><span>Strength Rule</span><input value={strengthRule} onChange={e=>setStrengthRule(e.target.value)} placeholder="z. B. TE / Field / Passing Strength"/></label><label className="wide"><span>Tags</span><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="base, nickel, field, pressure"/></label><label className="wide"><span>Beschreibung</span><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Coaching-Kontext und Einsatzbereich der Formation"/></label></div></AdminCard>
   <div className="fl-workspace"><AdminCard><div className="fl-section-title"><div><small>SLOT CONFIGURATION</small><h3>{slots.length} Positions-Slots</h3></div><button className="fl-add" onClick={addSlot}>＋ Slot</button></div><div className="fl-slots">{slots.map((s,i)=><article key={`${s.id||"new"}-${i}`}><div className="fl-order"><button onClick={()=>moveSlot(i,-1)}>↑</button><b>{i+1}</b><button onClick={()=>moveSlot(i,1)}>↓</button></div><label><span>Slot Key</span><input value={s.slotKey} onChange={e=>patchSlot(i,{slotKey:e.target.value})}/></label><label><span>Position</span><input value={s.positionLabel} onChange={e=>patchSlot(i,{positionLabel:e.target.value})}/></label><label><span>Group</span><input value={s.positionGroup} onChange={e=>patchSlot(i,{positionGroup:e.target.value})}/></label><label><span>Role</span><input value={s.roleLabel} onChange={e=>patchSlot(i,{roleLabel:e.target.value})}/></label><label><span>X</span><input type="number" min="0" max="100" value={s.x} onChange={e=>patchSlot(i,{x:Number(e.target.value)})}/></label><label><span>Y</span><input type="number" min="0" max="100" value={s.y} onChange={e=>patchSlot(i,{y:Number(e.target.value)})}/></label><label className="eligible"><span>Eligible Positions</span><input value={s.eligiblePositions} onChange={e=>patchSlot(i,{eligiblePositions:e.target.value})} placeholder="LB, OLB, WILL"/></label><button className="fl-remove" onClick={()=>removeSlot(i)}>×</button></article>)}{!slots.length&&<div className="fl-empty-block"><strong>Noch keine Slots definiert</strong><p>Lege die taktischen Positionen dieser Formation an. Jeder Slot erhält später Assignment, Depth-Chart-Mapping und Spielerzuordnung.</p><button onClick={addSlot}>Ersten Slot anlegen</button></div>}</div></AdminCard>
   <AdminCard><div className="fl-section-title"><div><small>FORMATION PREVIEW</small><h3>Coordinate Map</h3></div><span className="fl-badge">Field Editor next</span></div><div className={`fl-preview ${unit}`}><div className="fl-los"/>{slots.map((s,i)=><div className="fl-marker" key={`${s.slotKey}-${i}`} style={{left:`${Math.max(0,Math.min(100,s.x))}%`,top:`${Math.max(0,Math.min(100,s.y))}%`}} title={`${s.slotKey} · ${s.positionLabel}`}><b>{s.positionLabel||s.slotKey||i+1}</b><small>{s.slotKey}</small></div>)}</div><p className="fl-preview-note">Diese Vorschau nutzt bereits exakt dieselben X/Y-Koordinaten, die später an den visuellen Formation Editor übergeben werden.</p></AdminCard></div></>:<AdminCard><div className="fl-empty-block"><strong>Formation auswählen oder neu anlegen</strong><p>Links findest du alle aktiven Formationen der gewählten Saison und Unit.</p><button onClick={()=>void createFormation()}>Neue Formation</button></div></AdminCard>}</main>
  </div>}
 </AdminShell>
}
