import { bindings } from "../../../lib/cms";
import { ensureTrainingOperationsSchema } from "../../../lib/training-operations";
import { developmentNeedScore, getGroupSkills, matchesPositionGroup, POSITION_GROUPS } from "../../../lib/position-development";
import { requireCmsPermission } from "../../../lib/permissions";

type Row = Record<string, unknown>;
type PeriodInput = { id?:string; phase:string; unit:string; positionGroup:string; title:string; drillId?:string|null; minutes:number; sourceType?:string; sourceKey?:string; sourceScore?:number|null; coachingPoints?:string; note?:string };
type Body = { action?:"create-session"|"save-session"|"generate-plan"|"complete-session"; sessionId?:string; seasonId?:string; title?:string; startsAt?:string|null; durationMinutes?:number; status?:string; objective?:string; coachNote?:string; periods?:PeriodInput[]; review?:{completionPct?:number;executionRating?:number|null;intensityRating?:number|null;objectiveMet?:boolean;whatWorked?:string;nextFocus?:string} };
const avg=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;

async function selectedSeason(url:URL){const{DB}=bindings();const r=await DB.prepare("SELECT id,year,name,is_current FROM seasons ORDER BY year DESC").all<Row>();const seasons=r.results.map(x=>({id:String(x.id),year:Number(x.year),name:String(x.name??""),isCurrent:Number(x.is_current??0)===1}));return{seasons,season:seasons.find(s=>s.id===url.searchParams.get("seasonId"))??seasons.find(s=>s.isCurrent)??seasons[0]??null}}

export async function GET(request:Request){const actor=await requireCmsPermission("performance");if(actor instanceof Response)return actor;await ensureTrainingOperationsSchema();const{DB}=bindings();const url=new URL(request.url);const{seasons,season}=await selectedSeason(url);if(!season)return Response.json({error:"Keine Saison vorhanden."},{status:404});
 const sessionsRes=await DB.prepare("SELECT * FROM training_sessions WHERE season_id=? ORDER BY COALESCE(starts_at,'9999-12-31') DESC,created_at DESC LIMIT 40").bind(season.id).all<Row>();
 const sessions=[] as Array<Record<string,unknown>>;for(const s of sessionsRes.results){const periodsRes=await DB.prepare("SELECT * FROM training_periods WHERE session_id=? ORDER BY sort_order,id").bind(String(s.id)).all<Row>();const review=await DB.prepare("SELECT * FROM training_session_reviews WHERE session_id=?").bind(String(s.id)).first<Row>();sessions.push({id:String(s.id),title:String(s.title??"Training"),startsAt:s.starts_at?String(s.starts_at):null,durationMinutes:Number(s.duration_minutes??120),status:String(s.status??"draft"),objective:String(s.objective??""),coachNote:String(s.coach_note??""),createdBy:String(s.created_by??""),updatedBy:String(s.updated_by??""),updatedAt:String(s.updated_at??""),periods:periodsRes.results.map(p=>({id:String(p.id),phase:String(p.phase??"team"),unit:String(p.unit??"team"),positionGroup:String(p.position_group??""),title:String(p.title??""),drillId:p.drill_id?String(p.drill_id):null,minutes:Number(p.minutes??10),sourceType:String(p.source_type??"manual"),sourceKey:String(p.source_key??""),sourceScore:p.source_score==null?null:Number(p.source_score),coachingPoints:String(p.coaching_points??""),note:String(p.note??"")})),review:review?{completionPct:Number(review.completion_pct??0),executionRating:review.execution_rating==null?null:Number(review.execution_rating),intensityRating:review.intensity_rating==null?null:Number(review.intensity_rating),objectiveMet:Number(review.objective_met??0)===1,whatWorked:String(review.what_worked??""),nextFocus:String(review.next_focus??""),reviewedBy:String(review.reviewed_by??""),reviewedAt:String(review.reviewed_at??"")}:null})}
 const rosterRes=await DB.prepare(`SELECT rm.player_id,rm.primary_position,rm.secondary_position,rm.availability,rm.roster_status FROM roster_memberships rm JOIN players p ON p.id=rm.player_id WHERE rm.season_id=? AND rm.team_id='mens' AND rm.roster_status NOT IN ('left','alumni') AND p.active=1`).bind(season.id).all<Row>();
 const roster=rosterRes.results.map(r=>({id:String(r.player_id),primaryPosition:String(r.primary_position??""),secondaryPosition:String(r.secondary_position??""),availability:String(r.availability??"full")}));
 const evalRes=await DB.prepare("SELECT * FROM player_skill_evaluations WHERE season_id=? ORDER BY evaluated_at DESC,created_at DESC").bind(season.id).all<Row>();const latest=new Map<string,Row>();for(const e of evalRes.results){const k=`${e.player_id}|${e.skill_key}`;if(!latest.has(k))latest.set(k,e)}
 const needs=[] as Array<Record<string,unknown>>;for(const group of POSITION_GROUPS){const players=roster.filter(p=>matchesPositionGroup(group,p.primaryPosition,p.secondaryPosition));const skills=await getGroupSkills(group.key);for(const skill of skills){const rows=players.map(p=>latest.get(`${p.id}|${skill.key}`)).filter(Boolean) as Row[];if(!rows.length)continue;const current=avg(rows.map(r=>Number(r.current_rating??0))),target=avg(rows.map(r=>Number(r.target_rating??0))),priority=avg(rows.map(r=>Number(r.priority??2))),confidence=avg(rows.map(r=>Number(r.confidence??3))),coveragePct=players.length?Math.round(rows.length/players.length*100):0,needScore=developmentNeedScore(current,target,priority),trainingScore=Math.round(needScore*(coveragePct/100)*(confidence/5));const drills=await DB.prepare(`SELECT d.id,d.title,d.phase,d.intensity,d.min_minutes,d.max_minutes,d.description,d.coaching_points,sd.relevance FROM development_skill_drills sd JOIN development_drills d ON d.id=sd.drill_id WHERE sd.skill_key=? AND d.active=1 ORDER BY sd.relevance DESC,d.title LIMIT 3`).bind(skill.key).all<Row>();needs.push({group:group.key,groupLabel:group.label,unit:group.unit,skillKey:skill.key,skillLabel:skill.label,category:skill.category,current:Math.round(current*10)/10,target:Math.round(target*10)/10,coveragePct,needScore,trainingScore,state:coveragePct<40?"evaluate-first":needScore>=50?"focus":needScore>=25?"improve":"maintain",drills:drills.results.map(d=>({id:String(d.id),title:String(d.title),phase:String(d.phase),intensity:String(d.intensity),minMinutes:Number(d.min_minutes),maxMinutes:Number(d.max_minutes),description:String(d.description??""),coachingPoints:String(d.coaching_points??""),relevance:Number(d.relevance??0)}))})}}
 needs.sort((a,b)=>Number(b.trainingScore)-Number(a.trainingScore));
 const attendance=await DB.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN attendance='present' THEN 1 ELSE 0 END) present,SUM(CASE WHEN attendance='absent' THEN 1 ELSE 0 END) absent,SUM(CASE WHEN attendance='excused' THEN 1 ELSE 0 END) excused,SUM(CASE WHEN attendance='injured' THEN 1 ELSE 0 END) injured FROM player_performance_entries WHERE context='training' AND substr(occurred_at,1,4)=?`).bind(String(season.year)).first<Row>().catch(()=>null);
 return Response.json({current:actor,seasons,season,sessions,needs:needs.slice(0,30),summary:{players:roster.length,gameReady:roster.filter(p=>!["out"].includes(p.availability)).length,focusNeeds:needs.filter(n=>n.state==="focus").length,evaluateFirst:needs.filter(n=>n.state==="evaluate-first").length,attendancePct:attendance&&Number(attendance.total)>0?Math.round(Number(attendance.present??0)/Number(attendance.total)*100):null}})}

export async function POST(request:Request){const actor=await requireCmsPermission("performance");if(actor instanceof Response)return actor;await ensureTrainingOperationsSchema();const body=await request.json() as Body;const{DB}=bindings();
 if(body.action==="create-session"){if(!body.seasonId)return Response.json({error:"Saison fehlt."},{status:400});const id=crypto.randomUUID();await DB.prepare(`INSERT INTO training_sessions (id,season_id,title,starts_at,duration_minutes,status,objective,coach_note,created_by,updated_by) VALUES (?,?,?,?,?,'draft',?,?,?,?)`).bind(id,body.seasonId,body.title?.trim()||"Team Training",body.startsAt??null,Math.max(30,Math.min(240,Number(body.durationMinutes??120))),body.objective?.trim()??"",body.coachNote?.trim()??"",actor.email,actor.email).run();return Response.json({ok:true,id},{status:201})}
 if(!body.sessionId)return Response.json({error:"Training fehlt."},{status:400});const session=await DB.prepare("SELECT * FROM training_sessions WHERE id=?").bind(body.sessionId).first<Row>();if(!session)return Response.json({error:"Training nicht gefunden."},{status:404});
 if(body.action==="save-session"){await DB.prepare(`UPDATE training_sessions SET title=?,starts_at=?,duration_minutes=?,status=?,objective=?,coach_note=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(body.title?.trim()||String(session.title),body.startsAt??session.starts_at,Math.max(30,Math.min(240,Number(body.durationMinutes??session.duration_minutes??120))),body.status??session.status,body.objective??session.objective,body.coachNote??session.coach_note,actor.email,body.sessionId).run();const periods=body.periods??[];await DB.batch([DB.prepare("DELETE FROM training_periods WHERE session_id=?").bind(body.sessionId),...periods.map((p,i)=>DB.prepare(`INSERT INTO training_periods (id,session_id,sort_order,phase,unit,position_group,title,drill_id,minutes,source_type,source_key,source_score,coaching_points,note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(p.id||crypto.randomUUID(),body.sessionId,i,p.phase||"team",p.unit||"team",p.positionGroup||"",p.title||"Period",p.drillId??null,Math.max(1,Math.min(60,Number(p.minutes??10))),p.sourceType||"manual",p.sourceKey||"",p.sourceScore??null,p.coachingPoints||"",p.note||""))]);return Response.json({ok:true,count:periods.length})}
 if(body.action==="generate-plan"){const seasonId=String(session.season_id);const baseUrl=new URL(request.url);baseUrl.searchParams.set("seasonId",seasonId);const fakeReq=new Request(baseUrl.toString(),{headers:request.headers});const data=await GET(fakeReq);const payload=await data.json() as {needs?:Array<any>};const needs=(payload.needs??[]).filter(n=>n.state!=="evaluate-first"&&n.drills?.length).slice(0,8);const duration=Math.max(60,Math.min(180,Number(session.duration_minutes??120)));const reserve=Math.min(45,Math.max(25,Math.round(duration*.3)));const alloc=Math.max(20,duration-reserve);const weights=needs.reduce((s,n)=>s+Math.max(1,Number(n.trainingScore||1)),0);const suggested=needs.map((n:any,i:number)=>{const drill=n.drills[0];const raw=Math.round(alloc*Math.max(1,Number(n.trainingScore||1))/Math.max(1,weights));const minutes=Math.max(drill.minMinutes||6,Math.min(drill.maxMinutes||18,raw));return{id:crypto.randomUUID(),phase:drill.phase||"group",unit:n.unit,positionGroup:n.group,title:drill.title,drillId:drill.id,minutes,sourceType:"development-need",sourceKey:n.skillKey,sourceScore:n.trainingScore,coachingPoints:drill.coachingPoints||"",note:`${n.skillLabel} · Need ${n.needScore} · Coverage ${n.coveragePct}%`}});const used=suggested.reduce((s,p)=>s+p.minutes,0);const general=Math.max(0,duration-used);if(general>0)suggested.push({id:crypto.randomUUID(),phase:"team",unit:"team",positionGroup:"",title:"Team / Scheme / Situational Period",drillId:null,minutes:general,sourceType:"baseline",sourceKey:"team",sourceScore:null,coachingPoints:"Install · communication · situational execution",note:"Restzeit für Team- und Scheme-Arbeit."});await DB.batch([DB.prepare("DELETE FROM training_periods WHERE session_id=?").bind(body.sessionId),...suggested.map((p,i)=>DB.prepare(`INSERT INTO training_periods (id,session_id,sort_order,phase,unit,position_group,title,drill_id,minutes,source_type,source_key,source_score,coaching_points,note) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(p.id,body.sessionId,i,p.phase,p.unit,p.positionGroup,p.title,p.drillId,p.minutes,p.sourceType,p.sourceKey,p.sourceScore,p.coachingPoints,p.note))]);await DB.prepare("UPDATE training_sessions SET status='planned',updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(actor.email,body.sessionId).run();return Response.json({ok:true,count:suggested.length,duration:suggested.reduce((s,p)=>s+p.minutes,0)})}
 if(body.action==="complete-session"){const r=body.review??{};await DB.prepare(`INSERT INTO training_session_reviews (session_id,completion_pct,execution_rating,intensity_rating,objective_met,what_worked,next_focus,reviewed_by,reviewed_at) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(session_id) DO UPDATE SET completion_pct=excluded.completion_pct,execution_rating=excluded.execution_rating,intensity_rating=excluded.intensity_rating,objective_met=excluded.objective_met,what_worked=excluded.what_worked,next_focus=excluded.next_focus,reviewed_by=excluded.reviewed_by,reviewed_at=CURRENT_TIMESTAMP`).bind(body.sessionId,Math.max(0,Math.min(100,Number(r.completionPct??100))),r.executionRating??null,r.intensityRating??null,r.objectiveMet?1:0,r.whatWorked??"",r.nextFocus??"",actor.email).run();await DB.prepare("UPDATE training_sessions SET status='completed',updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(actor.email,body.sessionId).run();return Response.json({ok:true})}
 return Response.json({error:"Unbekannte Aktion."},{status:400})}
