"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminCard, AdminNotice, AdminShell } from "../_components/AdminShell";
import "./player-analysis.css";

type Season={id:string;year:number;name:string;isCurrent:boolean;status:string};
type Player={id:string;firstName:string;lastName:string;nickname:string;portrait:string;jerseyNumber:number|null;primaryPosition:string;secondaryPosition:string;unit:string;rosterStatus:string;availability:string;starter:boolean;captain:boolean;rookie:boolean;leadershipRole:string;heightCm:number|null;weightKg:number|null;birthDate:string|null;joinedYear:number|null;bio:string};
type Stat={key:string;label:string;shortLabel:string;category:string;value:number};
type Perf={id:string;context:string;occurredAt:string;attendance:string;effort:number|null;execution:number|null;discipline:number|null;impact:number|null;overall:number|null;note:string;index:number|null};
type Skill={key:string;label:string;category:string;description:string;current:number|null;target:number|null;priority:number|null;confidence:number|null;note:string;evaluatedAt:string|null;evaluatedBy:string;delta:number|null};
type Goal={id:string;skillKey:string|null;title:string;targetRating:number|null;dueDate:string|null;status:string;note:string;updatedAt:string};
type Game={id:string;opponent:string;kickoff:string|null;status:string;rascalsScore:number;opponentScore:number;hasOfficialStats:boolean};
type Career={year:number;items:Array<{key:string;shortLabel:string;label:string;value:number}>};
type Payload={seasons:Season[];season:Season;players:Player[];player:Player|null;positionGroup:{key:string;label:string};summary:{performanceIndex:number|null;attendancePct:number|null;currentSkillIndex:number|null;developmentNeedIndex:number|null;evaluationCoveragePct:number;openGoals:number;officialStatCategories:number;gamesWithStats:number};performance:Perf[];stats:Stat[];career:Career[];skills:Skill[];goals:Goal[];games:Game[];perfTrend:Array<{date:string;value:number;context:string}>};
type Tab="overview"|"stats"|"performance"|"development"|"goals"|"career";

export function PlayerAnalysisManager(){
 const[data,setData]=useState<Payload|null>(null);const[seasonId,setSeasonId]=useState("");const[playerId,setPlayerId]=useState("");const[tab,setTab]=useState<Tab>("overview");const[loading,setLoading]=useState(true);const[notice,setNotice]=useState("");
 useEffect(()=>{void boot()},[]);
 async function boot(){const q=new URLSearchParams(window.location.search);const initialTab=(q.get("tab")||"overview") as Tab;setTab(["overview","stats","performance","development","goals","career"].includes(initialTab)?initialTab:"overview");await load(q.get("season")||undefined,q.get("player")||undefined)}
 async function load(nextSeason?:string,nextPlayer?:string){setLoading(true);setNotice("");try{const q=new URLSearchParams();if(nextSeason)q.set("seasonId",nextSeason);if(nextPlayer)q.set("playerId",nextPlayer);const r=await fetch(`/admin/api/player-analysis?${q}`);if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error??"Spieleranalyse konnte nicht geladen werden.")}const b=await r.json() as Payload;setData(b);setSeasonId(b.season?.id??"");setPlayerId(b.player?.id??"")}catch(e){setNotice(e instanceof Error?e.message:"Fehler beim Laden.")}finally{setLoading(false)}}
 function syncUrl(s=seasonId,p=playerId,t=tab){const q=new URLSearchParams();if(s)q.set("season",s);if(p)q.set("player",p);q.set("tab",t);window.history.replaceState(null,"",`/admin/player-analysis?${q}`)}
 async function changeSeason(s:string){setSeasonId(s);setPlayerId("");syncUrl(s,"",tab);await load(s,undefined)}
 async function changePlayer(p:string){setPlayerId(p);syncUrl(seasonId,p,tab);await load(seasonId,p)}
 function changeTab(t:Tab){setTab(t);syncUrl(seasonId,playerId,t)}
 const topStats=useMemo(()=>data?.stats.filter(x=>x.value!==0).slice(0,8)??[],[data]);
 const topNeeds=useMemo(()=>data?.skills.filter(x=>x.current!=null&&x.target!=null).sort((a,b)=>((b.target??0)-(b.current??0))-((a.target??0)-(a.current??0))).slice(0,6)??[],[data]);
 const latestPerf=useMemo(()=>data?.performance.slice(0,6)??[],[data]);
 return <AdminShell active="playeranalysis" title="Spieler & Analyse" eyebrow="RASCALS OS · PLAYER PERFORMANCE CENTER" actions={<><a className="cms-button secondary" href="/admin/development/team">Team Analyse</a><a className="cms-button secondary" href="/admin/development/positions">Position Rooms</a></>}>
  {notice&&<AdminNotice tone="error">{notice}</AdminNotice>}
  <AdminCard className="pa-control"><div><small>PLAYER 360</small><h2>Eine Ansicht. Der komplette Spieler.</h2><p>Roster-Kontext, Official Stats, Training, Performance, Skill-Entwicklung, Goals und Karriere werden hier in einem konsistenten Spielerprofil zusammengeführt.</p></div><div className="pa-filters"><label className="cms-field"><span>Saison</span><select disabled={loading} value={seasonId} onChange={e=>void changeSeason(e.target.value)}>{data?.seasons.map(s=><option key={s.id} value={s.id}>{s.name}{s.isCurrent?" · AKTUELL":""}</option>)}</select></label><label className="cms-field"><span>Spieler</span><select disabled={loading||!data?.players.length} value={playerId} onChange={e=>void changePlayer(e.target.value)}>{data?.players.map(p=><option key={p.id} value={p.id}>#{p.jerseyNumber??"–"} {p.firstName} {p.lastName} · {p.primaryPosition}</option>)}</select></label></div></AdminCard>
  {!data?.player?<AdminNotice tone="info">Für diese Saison ist aktuell kein Spieler im Season Roster vorhanden.</AdminNotice>:<>
   <AdminCard className="pa-player-head"><div className="pa-avatar">{data.player.portrait?<img src={data.player.portrait} alt=""/>:<span>#{data.player.jerseyNumber??"–"}</span>}</div><div className="pa-player-id"><small>{data.positionGroup.label.toUpperCase()}</small><h2>#{data.player.jerseyNumber??"–"} {data.player.firstName} {data.player.lastName}</h2><p>{data.player.primaryPosition}{data.player.secondaryPosition?` / ${data.player.secondaryPosition}`:""} · {data.player.availability.toUpperCase()} · {data.player.rosterStatus.toUpperCase()}</p><div>{data.player.starter&&<span>STARTER</span>}{data.player.captain&&<span>CAPTAIN</span>}{data.player.rookie&&<span>ROOKIE</span>}{data.player.leadershipRole&&<span>{data.player.leadershipRole.toUpperCase()}</span>}</div></div><div className="pa-biofacts"><span><small>GRÖSSE</small><b>{data.player.heightCm?`${data.player.heightCm} cm`:"–"}</b></span><span><small>GEWICHT</small><b>{data.player.weightKg?`${data.player.weightKg} kg`:"–"}</b></span><span><small>IM TEAM</small><b>{data.player.joinedYear??"–"}</b></span></div></AdminCard>
   <div className="pa-kpis"><Metric label="Performance" value={data.summary.performanceIndex} suffix="/100"/><Metric label="Attendance" value={data.summary.attendancePct} suffix="%"/><Metric label="Skill Index" value={data.summary.currentSkillIndex} suffix="/100"/><Metric label="Development Need" value={data.summary.developmentNeedIndex} suffix="/100" risk/><Metric label="Eval Coverage" value={data.summary.evaluationCoveragePct} suffix="%"/><Metric label="Open Goals" value={data.summary.openGoals}/></div>
   <div className="pa-tabs">{(["overview","stats","performance","development","goals","career"] as Tab[]).map(t=><button key={t} className={tab===t?"active":""} onClick={()=>changeTab(t)}>{labelTab(t)}</button>)}</div>
   {tab==="overview"&&<div className="pa-grid-main"><AdminCard><Section eyebrow="CURRENT FORM" title="Performance Verlauf"/><MiniBars values={data.perfTrend.map(x=>x.value)}/><div className="pa-feed">{latestPerf.map(p=><article key={p.id}><span><b>{p.index??"–"}</b><small>{p.context.toUpperCase()}</small></span><div><strong>{formatDate(p.occurredAt)}</strong><p>{p.note||`${attendanceLabel(p.attendance)} · Execution ${p.execution??"–"}/5 · Effort ${p.effort??"–"}/5`}</p></div></article>)}{!latestPerf.length&&<p className="cms-muted">Noch keine Performance-Einträge.</p>}</div></AdminCard><AdminCard><Section eyebrow="TOP DEVELOPMENT NEEDS" title="Woran arbeiten wir?"/><div className="pa-needs">{topNeeds.map(s=><article key={s.key}><div><b>{s.label}</b><small>{s.category}</small></div><span>{s.current} → {s.target}</span><Trend value={s.delta}/></article>)}{!topNeeds.length&&<p className="cms-muted">Noch keine Skill-Evaluationen.</p>}</div><a className="cms-button secondary pa-link" href={`/admin/development/positions?group=${data.positionGroup.key}&season=${data.season.id}&player=${data.player.id}`}>Evaluation bearbeiten →</a></AdminCard><AdminCard><Section eyebrow="OFFICIAL SEASON STATS" title={data.season.name}/><div className="pa-stat-grid">{topStats.map(s=><span key={s.key}><small>{s.shortLabel}</small><b>{formatNumber(s.value)}</b></span>)}{!topStats.length&&<p className="cms-muted">Noch keine Official Stats.</p>}</div><a className="cms-button secondary pa-link" href="/admin/stats">Stats Review →</a></AdminCard><AdminCard><Section eyebrow="DEVELOPMENT PLAN" title="Goals"/><div className="pa-goals-short">{data.goals.slice(0,5).map(g=><article key={g.id}><Status value={g.status}/><div><b>{g.title}</b><small>{g.dueDate?`Fällig ${formatDate(g.dueDate)}`:"Ohne Deadline"}</small></div></article>)}{!data.goals.length&&<p className="cms-muted">Keine Development Goals.</p>}</div></AdminCard></div>}
   {tab==="stats"&&<><AdminCard><Section eyebrow="OFFICIAL ONLY" title={`Season Stats · ${data.season.name}`}/><div className="pa-stat-grid large">{data.stats.filter(s=>s.value!==0).map(s=><span key={s.key}><small>{s.shortLabel}</small><b>{formatNumber(s.value)}</b><em>{s.label}</em></span>)}{!data.stats.some(s=>s.value!==0)&&<p className="cms-muted">Noch keine offiziellen Saisonstatistiken.</p>}</div></AdminCard><AdminCard><Section eyebrow="GAME AVAILABILITY" title="Games mit offiziellen Spieler-Stats"/><div className="pa-games">{data.games.map(g=><article key={g.id}><div><b>{g.opponent}</b><small>{g.kickoff?formatDate(g.kickoff):"Datum offen"}</small></div><span>{g.status==="final"?`${g.rascalsScore}:${g.opponentScore}`:g.status.toUpperCase()}</span><strong className={g.hasOfficialStats?"ok":"muted"}>{g.hasOfficialStats?"OFFICIAL DATA":"NO DATA"}</strong></article>)}</div></AdminCard></>}
   {tab==="performance"&&<AdminCard><Section eyebrow="TRAINING · GAME · REVIEW" title="Performance History"/><div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>Datum</th><th>Kontext</th><th>Attendance</th><th>Effort</th><th>Execution</th><th>Discipline</th><th>Impact</th><th>Index</th><th>Note</th></tr></thead><tbody>{data.performance.map(p=><tr key={p.id}><td>{formatDate(p.occurredAt)}</td><td>{p.context}</td><td>{attendanceLabel(p.attendance)}</td><td>{p.effort??"–"}</td><td>{p.execution??"–"}</td><td>{p.discipline??"–"}</td><td>{p.impact??"–"}</td><td><b>{p.index??"–"}</b></td><td>{p.note||"–"}</td></tr>)}</tbody></table></div></AdminCard>}
   {tab==="development"&&<AdminCard><Section eyebrow={`${data.positionGroup.label.toUpperCase()} SKILL MODEL`} title="Skill Development"/><div className="pa-skill-grid">{data.skills.map(s=><article key={s.key}><div className="pa-skill-top"><div><small>{s.category}</small><h3>{s.label}</h3></div><Trend value={s.delta}/></div><p>{s.description}</p><div className="pa-rating"><span><small>CURRENT</small><b>{s.current??"–"}</b></span><span><small>TARGET</small><b>{s.target??"–"}</b></span><span><small>PRIORITY</small><b>{s.priority??"–"}</b></span><span><small>CONF</small><b>{s.confidence??"–"}</b></span></div>{s.note&&<blockquote>{s.note}</blockquote>}<small className="cms-muted">{s.evaluatedAt?`${formatDate(s.evaluatedAt)} · ${s.evaluatedBy}`:"Noch nicht bewertet"}</small></article>)}</div></AdminCard>}
   {tab==="goals"&&<AdminCard><Section eyebrow="INDIVIDUAL DEVELOPMENT PLAN" title="Goals & Status"/><div className="pa-goal-list">{data.goals.map(g=><article key={g.id}><Status value={g.status}/><div><h3>{g.title}</h3><p>{g.note||"Kein Maßnahmenkommentar hinterlegt."}</p><small>{g.dueDate?`Deadline ${formatDate(g.dueDate)}`:"Keine Deadline"}{g.targetRating?` · Zielrating ${g.targetRating}/5`:""}</small></div></article>)}{!data.goals.length&&<p className="cms-muted">Für diesen Spieler gibt es noch keine Development Goals.</p>}</div></AdminCard>}
   {tab==="career"&&<><AdminCard><Section eyebrow="MULTI-SEASON" title="Career Timeline"/><div className="pa-career">{data.career.map(y=><article key={y.year}><header><b>{y.year}</b><small>OFFICIAL STATS</small></header><div className="pa-stat-grid">{y.items.filter(i=>i.value!==0).map(i=><span key={i.key}><small>{i.shortLabel}</small><b>{formatNumber(i.value)}</b></span>)}</div></article>)}{!data.career.length&&<p className="cms-muted">Noch keine Career-Daten vorhanden.</p>}</div></AdminCard></>}
  </>}
 </AdminShell>
}

function Metric({label,value,suffix="",risk=false}:{label:string;value:number|null|undefined;suffix?:string;risk?:boolean}){return <div className={`pa-metric ${risk?"risk":""}`}><small>{label}</small><b>{value??"–"}{value!=null?suffix:""}</b></div>}
function Section({eyebrow,title}:{eyebrow:string;title:string}){return <div className="cms-section-head"><div><small>{eyebrow}</small><h2>{title}</h2></div></div>}
function Trend({value}:{value:number|null}){return <span className={`pa-trend ${value==null||value===0?"flat":value>0?"up":"down"}`}>{value==null?"–":value>0?`▲ +${value}`:value<0?`▼ ${value}`:"→ 0"}</span>}
function Status({value}:{value:string}){return <span className={`pa-status ${value}`}>{value.replace("-"," ").toUpperCase()}</span>}
function MiniBars({values}:{values:number[]}){const max=Math.max(100,...values);return <div className="pa-mini-bars">{values.length?values.map((v,i)=><span key={i} style={{height:`${Math.max(8,(v/max)*100)}%`}} title={String(v)}/>):<em>Keine Trenddaten</em>}</div>}
function formatDate(v:string){return new Date(v).toLocaleDateString("de-DE")}
function formatNumber(v:number){return Number.isInteger(v)?String(v):v.toFixed(1)}
function attendanceLabel(v:string){return ({present:"Anwesend",absent:"Fehlt",excused:"Entschuldigt",injured:"Verletzt",none:"–"} as Record<string,string>)[v]??v}
function labelTab(t:Tab){return ({overview:"Übersicht",stats:"Stats",performance:"Performance",development:"Development",goals:"Goals",career:"Career"} as Record<Tab,string>)[t]}
